### ISSUE TITLE
Hypothesis randomly says you aren't logged in

### ISSUE THREAD

**Issue by ghost** [hypothesis/client#1005]
### Steps to reproduce
1. Create a series of annotations
2. Random intervals, hypothesis will prompt you to log in before making an annotation
3. Refreshing the page sometimes fixes the problem

### Expected behaviour
Tell us what should happen.
Annotation should be made, with no prompting to log in when in the middle of a paper.
### Actual behaviour
Tell us what happens instead.
Hypothesis doesn't think you are logged in, and will not let you make an annotation
### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

Google Chrome, most recent one?, Windows 10

### Additional details
If you have other information which might be helpful, please include it. If a
screenshot will help to illustrate the issue you are reporting, please include
one.

**Comment by g-pine** [comment]
@tgbugs

**Comment by klemay** [comment]
Hi @ghost - we are closing out old issues and are just now seeing this one. If you're still having trouble with your login persisting, please email support@hypothes.is to get help.
