### ISSUE TITLE
unable to select text for annotation at http://www.nytimes.com/2016/04/17/magazine/the-minecraft-generation.html

### ISSUE THREAD

**Issue by judell** [hypothesis/client#102]
The console error is:

Uncaught (in promise) TypeError: Cannot read property 'nodeType' of undefined(…)

It happens here in annotator.js:

  Util.getFirstTextNodeNotBefore = function(n) {
    var result;
 -->   switch (n.nodeType) {

Version: 0.41.0
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36
URL: http://www.nytimes.com/2016/04/17/magazine/the-minecraft-generation.html
Username: judell
Date: 13 Sep 2016 08:28:42 -0700

**Comment by judell** [comment]
At http://www.nytimes.com/2016/09/13/opinion/campaign-stops/did-you-hear-the-latest-about-hillary.html I am seeing a different pathology that is not an H bug (i.e. happens with or without H). 

In this case no JS error. And something jumps out from the right side of the screen in response to efforts to select text.  

http://jonudell.net/h/nytimes-win-10-cannot-select-to-annotate.mp4

**Comment by nickstenning** [comment]
I can't reproduce either of these issues. Perhaps you have other browser extensions which might be conflicting with h?

Does it still happen for you, @judell?

**Comment by judell** [comment]
Today: Yes. No other extensions active.

**Comment by judell** [comment]
Aha.

https://www.quora.com/Why-cant-I-highlight-text-on-The-New-York-Times-website-when-using-Chrome

> I finally figured it out. Looks like this only happens on Windows computers with touchscreens. The New York Times goes into touchscreen mode on such computers even when you are using the browser in regular desktop mode as opposed to tablet mode. This is a nasty bug in NYT and as a result you can't select text by dragging the mouse and double-clicking changes the font-size instead of selecting the word under the mouse.

> There is a workaround, however.  In Chrome go to chrome://flags and change Enable Touchscreen Events to disabled. Note that this impacts all sites, not just the New York Times website.
