### ISSUE TITLE
Very long group names result in ugly overflow on group drop down header

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/client#1041]
When there is a very long group name, it results in the group logo getting cut off on the sidebar drop down menu header.
![image](https://user-images.githubusercontent.com/30059933/55597917-dbc33580-5704-11e9-9315-6917a3bb3a01.png)
Two possible ways to fix this:
1. Make the space between the logo and the name slightly smaller.
2. Make the sidebar slightly wider.

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/client/issues/2160
