### ISSUE TITLE
When click on name of out of scope group it links to activity page

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/client#1059]
When the user clicks on the name of out of scope group it links to activity page instead of opening the group details. It should only link to the group activity page once the details and the group activity link is visible.
![image](https://user-images.githubusercontent.com/30059933/55840680-1b14cc00-5ae1-11e9-8f55-2c367d3242bf.png)

**Comment by lyzadanger** [comment]
I believe this is no longer valid as the UI has changed quite a bit in the meantime.

Now, clicking on an out-of-scope group's name will expand its submenu:

![image](https://user-images.githubusercontent.com/439947/102396870-14737300-3fab-11eb-8345-a09193ce763a.png)

(excuse the focus ring; it's a side effect of taking a screenshot. It doesn't show normally unless one is using keyboard).
