### ISSUE TITLE
Annotation deletion not reflected in realtime update

### ISSUE THREAD

**Issue by gmcatalin** [hypothesis/client#1071]
### Steps to reproduce
1. Have two users in a group
2. Create an annotation with one of the users, reload (or apply update) with the second user
    to see the annotation and highlight
3. Delete the annotation with the initial user and apply the (push) update with the second

### Expected behaviour
The annotation and highlight should be deleted for the second user.

### Actual behaviour
The annotation is deleted but the highlight is not removed.

### Browser/system information
Chrome/ Windows 10 (but happens the same on any browser)

### Additional details
I believe the issue is https://github.com/hypothesis/client/blob/734e3a25318364819a8c38ef881e4788a2b06365/src/annotator/guest.coffee#L304
Since the test is by reference, two annotation objects created at different times, initial annotation object creation (load of page or push update) and the delete push, will never be equal. I guess using the annotation id to compare annotation would be a better option ?

**Comment by robertknight** [comment]
There is a related issue being worked on in the backend: https://github.com/hypothesis/h/pull/6214

Re-reading this issue description it sounds like it is unrelated to any backend issues.

**Comment by gmcatalin** [comment]
Nope, it's a frontend issue :)  Like i said in the description, the message is received but the annotation objects are tested by reference.

**Comment by robertknight** [comment]
A number of backend issues relating to deleted annotations have now been resolved. I am no longer able to reproduce the client issue mentioned in the description. Please let me know if you still experience a problem.

> Like i said in the description, the message is received but the annotation objects are tested by reference.

I can see why this looks like a problem, but actually the part of the code that you mentioned in the description is not comparing local copies with annotations received via the WebSocket. It is comparing local objects from a collection for which there is one per ID, so comparing by reference is equivalent to comparing by ID.
