### ISSUE TITLE
Cannot delete annotation from the UI

### ISSUE THREAD

**Issue by ArthurFlageul** [hypothesis/client#1107]
### Steps to reproduce
1. Add an annotation to a private group using the extension.
2. Go to the webclient: either to the group page or to your user page.
3. There is no button to delete the listed annotations.

### Expected behaviour
Only the browser extension offers a delete button, I expect the same button to be available on the webclient.

### Additional details
This UI workflow means that it's impossible to delete annotations that refer to content that does not exist anymore.

**Comment by klemay** [comment]
Hi @ArthurFlageul - you can delete annotations from the web app by following these steps:

1. Find the annotation on your user page or the group page
2. Click on the date stamp:
<img width="896" alt="Screen Shot 2020-09-10 at 3 49 05 PM" src="https://user-images.githubusercontent.com/12087705/92794163-51f9ac00-f37d-11ea-8505-1292483a0d04.png">
3. You'll be taken to a single-page view of the annotation, where you'll have the option to delete it:
<img width="669" alt="Screen Shot 2020-09-10 at 3 50 48 PM" src="https://user-images.githubusercontent.com/12087705/92794293-7d7c9680-f37d-11ea-919d-e133cb9d50c1.png">

I agree that this could be simplified and more discoverable - but we have an upcoming redesign of activity pages that will account for this. For that reason, I'm closing this issue.
