### ISSUE TITLE
URLs appearing to push right side of cards beyond sidebar

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#115]
### Steps to reproduce
1. Click here: https://hyp.is/JdFEBHt7Eeaa3t8X5vHvgQ/notes.wtk.io/2016/09/15/replies
### Expected behaviour

Cards should sit within sidebar panel
### Actual behaviour

Right side of card hangs over
### Browser/system information

About this version
Version:
0.43.0
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
URL:
https://notes.wtk.io/2016/09/15/replies
Username:
dwhly
Date:
16 Sep 2016 08:41:46 -0700
### Additional details

This appears to correspond to the presence of the URL in the card. The pathology begins when the sidebar is shrunk below the width of the URL.

![screen shot 2016-09-16 at 8 40 10 am](https://cloud.githubusercontent.com/assets/1413074/18591858/3bd19862-7be9-11e6-9a6a-e1b77978dff6.png)

**Comment by lyzadanger** [comment]
Fixed by https://github.com/hypothesis/client/pull/2120
