### ISSUE TITLE
Creating a highlight while logged out deletes any other highlights created while logged out

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#12]
1. While logged out, create a highlight.
2. Still logged out, create another highlight.

Result: creating the second highlight deletes the first.

Expected: the way this used to work was:
- You could create as many highlights as you want while logged out
- These would stack up as multiple "You must be signed in to create annotations" cards in the sidebar which you wouldn't see because the sidebar is closed
- If you have the sidebar open while you're highlighting don't worry - it'll close itself! :)
- When you do finally sign in all your highlights are saved to the server
- But if you browse to another page or close the window or tab all your highlights are silently deleted

![untitled screencast - edited 26](https://cloud.githubusercontent.com/assets/22498/16526387/fb03f7b6-3fa8-11e6-9245-b20a5c2e4152.gif)

**Comment by karlicoss** [comment]
Hey, looks like a pretty annoying issue. Especially if you highlight bunch of things while logged out, and never realize they would be gone after you close the page.
I think the way you are describing it used to work is exactly my problem!
I'd be happy to contribute and fix it. I think the simplest and most reliable thing to do would be to show some sort of notification or just expand the sidebar and show the warning when you try to highlight or annotate while not logged in. Currently, it would only do that when you annotate, but that I think is just a collateral effect of sidebar trying to prompt you for annotation. What do you think?

**Comment by hmstepanek** [comment]
It appears that by clicking on the annotations tab after logging in, it triggers a grab of the highlights that were made when the user was logged out and the highlights are then saved after refreshing the page. Notice the highlights don't show up there after logging in which makes me think that's the part that broke at some point. There ought to be a way to trigger that grab of the highlights upon logging in.
<div style='position:relative; padding-bottom:calc(55.84% + 44px)'><iframe src='https://gfycat.com/ifr/NecessarySpectacularLarva' frameborder='0' scrolling='no' width='100%' height='100%' style='position:absolute;top:0;left:0;' allowfullscreen></iframe></div>

**Comment by lyzadanger** [comment]
No more highlighting while not logged in and the magical behavior that entailed. Now you'll get a login prompt if you attempt to create a highlight anonymously.
