### ISSUE TITLE
Migrate NewNoteBtn to Preact

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#1206]
Note from team discussion: because of the number of (Angular) components that still rely on the broadcast `BEFORE_ANNOTATION_CREATE` event, we decided to, for the first go-around here, use `$rootScope` via `withServices` and retain the broadcasting for now (instead of moving this to the store, e.g.).

**Comment by lyzadanger** [comment]
In looking at this, I'm not clear where (or, really, if) this is getting used. It's only present if `enableExperimentalNewNoteButton` is set. I'd like to chat before setting out on this one.

**Comment by lyzadanger** [comment]
@LMS007 Note that this component (see its current template) uses the old `h-branding` directive. There is a new `util/theme` that will allow you to accomplish the same thing.

**Comment by robertknight** [comment]
The "New note button" is a UI element that we put in as a way to create notes when using the "clean" theme and when the button in the edge of the sidebar for creating new notes is hidden.

The `experimental` part of the name reflects the fact that we never came to a solid conclusion as to whether we should:

- Always have this in the UI
- Only have it in the UI under particular conditions
- Make it a configuration option that the publisher must set permanently

For the purposes of this task and the overall migration away from Angular, it might help to separate out the work of just converting the existing code as-is from resolving the design/config issue.
