### ISSUE TITLE
Migrate ShareDialog to Preact

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#1209]
Migrate this component, and, as part of this process, update the UX to take advantage of group-scoped sharing via community groups. See https://github.com/hypothesis/product-backlog/issues/1030

**Comment by robertknight** [comment]
It may or may not be easier to tackle the migration in two stages -  convert the existing UI and then modernize it as per the mocks in https://github.com/hypothesis/product-backlog/issues/1030, or just implement the new design directly. I leave it up to whoever takes this on to figure out which approach will be easier.

**Comment by klemay** [comment]
As part of #1030, we've reached consensus on the UI changes, which will look like this:

![image](https://user-images.githubusercontent.com/12087705/62737446-cdac5b00-b9fd-11e9-8311-04686e54b457.png)

In addition to the visual design changes, we also decided on a behavior change: the share link should be formatted such that it scopes to the currently-focused group in all cases.

**Comment by lyzadanger** [comment]
Fixed as of https://github.com/hypothesis/client/pull/1420
