### ISSUE TITLE
Rewrite TagEditor component for Preact

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#1210]
Our Angular variant of this component uses a third-party Angular library for this. This migration process will require us to spec desired behavior and re-implement from scratch.

**Comment by robertknight** [comment]
> This migration process will require us to spec desired behavior and re-implement from scratch.

There are of course tag editor-like widgets available for React. My instinct based on past experience though is that implementing from-scratch will be best for producing a polished result that works well in the context of the sidebar and ticks the boxes with respect to design, a11y etc.

I suggest that whoever takes this on should search the issues across the Hypothesis organization for ones that [mention tag input](https://github.com/search?q=org%3Ahypothesis+tag+input&type=Issues) (currently 12 at the time of writing, though several are not related to tag input in the client), as there are probably existing UX issues that can be fixed while we're at it.
