### ISSUE TITLE
Logo PRoposal for client

### ISSUE THREAD

**Issue by memoryskull** [hypothesis/client#1214]
Hi! @hypothesis
I'm interested in collaborating with this project by delivering a series of logotype options that fits this project for the best!

If interested let me know so we can get started!

Cheers!

**Comment by robertknight** [comment]
This user has created a number of very similar issues for an assortment of unrelated GitHub repos recently. That looks a little spammy to me.

**Comment by memoryskull** [comment]
Hello @robertknight 
It is not spam, I am creating my portfolio and for this I am collaborating with open source projects.
I show you some of my previous works
![IMG-20190629-WA0137](https://user-images.githubusercontent.com/52359514/60621052-b947c380-9daa-11e9-9627-b81455121f89.jpg)

![flyer nuevo de la final](https://user-images.githubusercontent.com/52359514/60620093-476e7a80-9da8-11e9-890c-3a06e9ad4a1b.jpg)
![Screenshot_20190703-141958_Gmail](https://user-images.githubusercontent.com/52359514/60620928-71c13780-9daa-11e9-8d13-89e9555c67f8.jpg)
![Screenshot_20190703-141950_Gmail](https://user-images.githubusercontent.com/52359514/60620961-830a4400-9daa-11e9-92f1-8614ea73209a.jpg)
![alexandra-d´muchez](https://user-images.githubusercontent.com/52359514/60621004-9fa67c00-9daa-11e9-89aa-b9450169e4cb.jpg)
