### ISSUE TITLE
Moderation banner shows on non-flagged annotations

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1224]
### Expected behaviour
As a moderator, the banner should not be shown if the message is not flagged, or we should not arrive in a conflicted state of both hidden and un-flagged.

### Actual behaviour
As a moderator, this annotation (reply) is hidden and has not been flagged. I'm not sure how exactly to arrive at this state since we don't have a UI feature that un-flags an annotation.

The banner should probably not be shown when the annotation is not flagged, or we need to better understand how an annotation can be both un-flagged and hidden?

![Screen Shot 2019-07-02 at 12 51 26 PM](https://user-images.githubusercontent.com/3939074/60542172-220a3f80-9cc8-11e9-810b-bca86c7c7a88.png)

Additionally there is a random "0" node injected into the dom, but this may be related to a preact bug or idiosyncrasy with inline conditionals in jsx, but upon code inspection, this element is a total mystery.

Additionally, if a moderator clicks "Unhide" the entire banner goes away.

### Browser/system information
Chrome

**Comment by LMS007** [comment]
Live DOM
![Screen Shot 2019-07-02 at 12 56 40 PM](https://user-images.githubusercontent.com/3939074/60542455-dc01ab80-9cc8-11e9-832d-e9dcce2765ae.png)

**Comment by robertknight** [comment]
> Additionally there is a random "0" node injected into the dom, but this may be related to a preact bug or idiosyncrasy with inline conditionals in jsx, but upon code inspection, this element is a total mystery.

I think the second of the two possibilities is what is happening here. In this code...

```js
{flagCount && !annotation.hidden && (
  <span>Flagged for review x{flagCount}</span>
)}
```

If `flagCount` is 0 then this expression evaluates to `0`, and in React numbers get translated to text nodes (even zero apparently). Demo with React: https://codesandbox.io/s/compassionate-murdock-px2nf. The code that actually implements this in Preact: https://github.com/preactjs/preact/blob/01d1317b64522f8367c6b79e8972bd6b4324b0b8/src/create-element.js#L89

**Comment by robertknight** [comment]
> As a moderator, this annotation (reply) is hidden and has not been flagged. I'm not sure how exactly to arrive at this state since we don't have a UI feature that un-flags an annotation.

Hmm. I can't immediately think how that happened either. Can you have a look at the JSON data that is returned from the API in the `/api/search` call and verify that the backend is definitely returning an annotation which is hidden but not flagged?

**Comment by LMS007** [comment]
Flag count is 0 from service

![Screen Shot 2019-07-05 at 11 26 55 AM](https://user-images.githubusercontent.com/3939074/60739727-e82f7800-9f17-11e9-9f9a-f4ebf4682659.png)
