### ISSUE TITLE
"Message not available." in /stream

### ISSUE THREAD

**Issue by sean-roberts** [hypothesis/client#123]
### Steps to reproduce
1. Go to https://hypothes.is/stream 
2. Leave the tab open for a while
### Expected behaviour

We resume seeing the list of items that were displayed before leaving
### Actual behaviour

![screen shot 2016-09-21 at 1 49 23 pm](https://cloud.githubusercontent.com/assets/950274/18723182/943a7c9c-8005-11e6-90dd-e2d41e03adce.png)
### Browser/system information

Chrome Latest
### Additional details

Doing some investigating, @nickstenning found that we create this result when the web socket receives updates, real-time replies, to annotations that exist on the server but are not in the current user's list of items.

**Comment by lenazun** [comment]
Does this affect /stream only? Given that /stream is not a page we're advertising much these days (we maintain it only because removing it would break people's workflows), I would say this is even lower priority and perhaps a won't fix.

**Comment by sean-roberts** [comment]
Not entirely sure, but I feel like it doesn't. I can try to repro

**Comment by seanh** [comment]
Merged into https://github.com/hypothesis/product-backlog/issues/394
