### ISSUE TITLE
Fix UX bugs related to replying to annotations when the client is filtered

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#1244]
Apply a search filter to the sidebar (for example: `user:rob`) and then click on the <kbd>Reply</kbd> button on one of the matching annotations. Since your reply doesn't match the filter it isn't shown at first. It should be.

**Comment by LMS007** [comment]
@sea 
Should the reply be visible until you refresh or apply a new filter?

**Comment by seanh** [comment]
@LMS007 Yes, that sounds right to me

**Comment by lyzadanger** [comment]
This one has been fixed!
