### ISSUE TITLE
Karma throwing warnings when running tests

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1246]
### Steps to reproduce

run the client tests

### Expected behaviour

no warnings about invalid file types

### Actual behaviour
output looks a bit like this

```

...

11 07 2019 12:00:50.246:WARN [middleware:karma]: Invalid file type (coffee), defaulting to 
...

```

Could be related to config file issue
https://github.com/karma-runner/karma/issues/3271

**Comment by lyzadanger** [comment]
No more coffeescript in our codebase, so I'm not seeing these warnings anymore. Feel free to reopen if it's still wonky.
