### ISSUE TITLE
Bookmarklet can't authenticate

### ISSUE THREAD

**Issue by iwsmith** [hypothesis/client#1272]
### Steps to reproduce
1. Log in on https://hypothes.is
2. Go to http://ada.evergreen.edu/~arunc/texts/politics/socialism.pdf
3. Click the bookmarklet link
4. It shows as not logged in, clicking login opens a popup that goes away, but I am still not logged in.

### Expected behaviour
I should be logged in

### Actual behaviour
I am not logged in.

### Browser/system information
OSX 10.14.5
Firefox Nightly 70.0a1 (2019-07-24) (64-bit)

### Additional details
Webdev console reports:
`Rejected untrusted message from https://hypothes.is 29 viewer.js:11426:17`

**Comment by robertknight** [comment]
I was not able to reproduce the problem using the bookmarklet in the latest version of Firefox. I do see the "Rejected untrusted message" messages in the console, but those are expected warnings to do with communication between the Hypothesis sidebar and the host page in Firefox's built-in PDF viewer.
