### ISSUE TITLE
Remove circular dependency issue between drafts and annotations stores

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1280]
in `store/modules/drafts.js`, `deleteNewAndEmptyDrafts` imports the `annotations` store in the function because it can't do it before the `drafts` module is defined because they both import each other. Moving to ES6 `import` should fix this issue OR we refact these modules so they don't directly depend on each other.

**Comment by robertknight** [comment]
The circular dependency between the "drafts" and "annotations" store modules still exists, which is ugly, but the imports have been changed to ES imports which allows for circular imports, so the non-top level `require` is no longer needed.
