### ISSUE TITLE
Refactor events in root-thread.js that are just proxies

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1281]
After some refactoring, some of the event handlers in root-thread.js are just proxies for store actions. We can probably remove these events entirely now.

- ANNOTATION_DELETED
- ANNOTATIONS_UNLOADED

This may be a good time to look at refracting other events in this file into actions.

**Comment by robertknight** [comment]
This was addressed by https://github.com/hypothesis/client/pull/1993.
