### ISSUE TITLE
JS Error after searching while an annotation draft exists

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1290]
I'm not sure this is a recent regression or been around for longer, but there is js error when searching after creating a draft note annotation. *This does not happen when creating a highlight draft annotation.*

Steps to reproduce:
- Create a new page note
- Click the search bar and type a search phrase like "test"
- Click enter

![Screen Shot 2019-08-05 at 9 47 36 AM](https://user-images.githubusercontent.com/3939074/62481147-780a5100-b766-11e9-88d6-7229d94395e2.png)

**Comment by robertknight** [comment]
Fixed by https://github.com/hypothesis/client/pull/1307
