### ISSUE TITLE
real-time-updates module 

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1319]
The `real-time-updates` module is unique in that is imports selectors from adjacent modules. 

```
const { selectors: annotationSelectors } = require('./annotations');
const { selectors: groupSelectors } = require('./groups');
const { selectors: viewerSelectors } = require('./viewer');
```

Once we namespace this module #1235, these imported selectors will no longer operate the same since we will no longer have the same root state to pass to the selector as its first parameter. This causes the selectors to break.

One solution is to move the heavy handed logic that requires the selectors into the respective `receiveRealTimeUpdates` action by turning this into a thunk action that has access to the entire store.  This would eliminate the need to import the selectors as static stand alone methods and allow the module to be namespaced without the reducer state issue.

**Comment by robertknight** [comment]
Closed by https://github.com/hypothesis/client/pull/1327
