### ISSUE TITLE
Can't create the tag pages:8 if pages:85 is remembered in localStorage

### ISSUE THREAD

**Issue by judell** [hypothesis/client#132]
### Steps to reproduce
1. Create tag pages:85
2. Try to create tag pages:8

### Expected behaviour
I can create the tag pages:8 if pages:85 is a remembered tag

### Actual behaviour
It always becomes pages:85

### Additional details
http://jonudell.net/h/tag-pages8-vs-pages85.mp4

**Comment by sean-roberts** [comment]
The behavior is such that the tags are ordered by frequency of use and then by lexical asc. So, by testing this specific case, you are putting `pages:85` at a higher rank. Seems there could be some usability improvements to help the user understand this better. But functionally, I think it is working as designed.

**Comment by judell** [comment]
Yeah. For some reason I expected that hitting Enter after typing pages:8 would force that choice but of course once a completion list appears Enter selects from it. 

The interesting question is: Why in the world would I have expected that? Especially given that I have loads of experience using this control.

I think it's because I'd gotten into a flow where I was repeatedly tagging with pages:NN and it just happened to be the case that, up to a point, it was never necessary to navigate the completion list, because the first choice was always the right one.

Until it wasn't.

Weird.

**Comment by sean-roberts** [comment]
Well,  I don't think that is a wrong expectation. It seems the experience makes some big assumptions about how the user intends to use service. I imagine that is backed by some data somewhere. But it would be very interesting to know the hit/miss ratio on that feature
