### ISSUE TITLE
Annotations immediately orphan when selecting text in a PDF that includes last character on page

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#1329]
This issue was created as part of investigating https://github.com/hypothesis/lms/issues/875.

**Steps to reproduce**

1. Go to https://via.hypothes.is/https://arxiv.org/pdf/1908.04683v3.pdf, scroll down to page 5 and select the text beginning at the bottom of the page from "For our experiments" up to and _including_ the page number "5" at the bottom of the page.
2. Click "Annotate"

**Expected result:** The selected text is highlighted and a new annotation appears in the "Annotations" tab in the client
**Actual result:** The selected text is not highlighted and the annotation appears in the "Orphans" tab in the client

After reloading the page, the annotation continues to be an orphan instead of anchoring.

**Notes**

The issue occurs whenever a selection to annotate matches these criteria:

1. The text is unique enough within the document that it does not fuzzily/roughly match any other text
2. The selected text includes the last character in the page's text. More specifically, it needs to extend up to the end of the invisible `div.textLayer` element that PDF.js creates for each page to enable text selection.

**Comment by mkdir-washington-edu** [comment]
Also occurs here: https://hypothesis.zendesk.com/agent/tickets/5926

**Comment by robertknight** [comment]
The immediate problem here is an upstream issue in the `dom-anchor-text-position` library. In brief:

1. When anchoring a quote within a PDF, the client fetches the text of each page and attempts to locate the quote within the text
2. If successful, there are two possibilities: Either the page where the quote was found, in which case there will be a text layer `<div>` used for text selection, or it is not, in which case there will just be a placeholder for the text layer
3. If there is a text layer, the quote is mapped to a text position selector within the text layer, and the text position selector is mapped to a DOM `Range` using `dom-anchor-text-position`. This is basically the same as if we were doing HTML anchoring.

There is a problem in (3) if the generated text position includes the final character of the text layer `<div>` as this triggers an exception in `dom-anchor-text-quote`.

Although the basic problem is not actually specific to PDF annotation, it essentially never happens for HTML annotation because there are always some characters in an HTML document beyond what the user can actually select. With PDF annotation however, it is actually possible to select the last character in the text layer.

I've submitted a PR and test cases upstream. Depending on how soon Randall is able to take a look and whether any further changes are needed, we'll either upgrade the library or temporarily use a fork.
