### ISSUE TITLE
activity pages prompt says url: but should say uri:

### ISSUE THREAD

**Issue by judell** [hypothesis/client#139]
![image](https://cloud.githubusercontent.com/assets/46509/18846364/66c5d3a0-83da-11e6-9187-7749bbdd0022.png)

**Comment by dwhly** [comment]
If there's any way we can use URL instead, that would be awesome.  Since
people actually know what those are.

D

**Comment by judell** [comment]
That's a good point. Why not just alias /search?uri:https://... and /search?url:https:/...

**Comment by cove** [comment]
making them interchangeable could be confusing too, maybe a more generic term like "location:" or "link:"?

**Comment by sean-roberts** [comment]
Using facets will trigger a special style of lozenge. That logic is based on the selections available in the dropdown. Having an "alias" might not functionally make any sense to support.

**Comment by judell** [comment]
url: is now in effect
