### ISSUE TITLE
Client fails to load in IE 11

### ISSUE THREAD

**Issue by judell** [hypothesis/client#1391]
The client loads, but spins trying to render the sidebar. No console errors.

http://jonudell.info/h/ie11-breakage.mp4

![image](https://user-images.githubusercontent.com/46509/65914657-a3847300-e386-11e9-9ae5-3f874412eeba.png)

Browser has been reset to defaults.

IE is 1% in GA

![image](https://user-images.githubusercontent.com/46509/65915084-7edccb00-e387-11e9-9408-590bce33c63c.png)

IE 11 is most of that

![image](https://user-images.githubusercontent.com/46509/65915276-fad71300-e387-11e9-93a5-e61f3dc17830.png)

**Comment by robertknight** [comment]
I can reproduce this at https://via.hypothes.is/example.com and at https://hypothes.is/stream, which is just the sidebar app.

We still support IE 11, just not earlier versions of IE.

**Comment by robertknight** [comment]
`git bisect` using IE 11 hosted by Sauce Labs + Sauce Connect to view my local client shows that the regression was introduced in 542b96f0cd0b478b189efe7f0ee116527e4494d7.
