### ISSUE TITLE
The share group annotations button generates an incorrect share link

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/client#1392]
# Problem
The link that comes up in the share all annotations in the sidebar is missing the `&group=<groupid>` which bouncer appears to parse incorrectly and thus the url it spits out has the fragment `#annotations:query` aka a placeholder instead `#annotations:group:<groupid>`. 

# Details
The share all annotations link in the top menu of the sidebar generates a link that is missing the groupid information. 
```
https://hyp.is/go?url=http%3A%2F%2Fdocs.pylonsproject.org%2Fprojects%2Fpyramid-retry%2Fen%2Flatest%2Fapi.html
```
instead of:
```
https://hyp.is/go?url=http%3A%2F%2Fdocs.pylonsproject.org%2Fprojects%2Fpyramid-retry%2Fen%2Flatest%2Fapi.html&group=__world__
```
This in turn results in an incorrect fragment on the url being returned from bouncer.
```
https://docs.pylonsproject.org/projects/pyramid-retry/en/latest/api.html#annotations:query:
```
instead of:
```
https://docs.pylonsproject.org/projects/pyramid-retry/en/latest/api.html#annotations:group:__world__
```
![image](https://user-images.githubusercontent.com/30059933/66022219-10d8f680-e4a2-11e9-9231-0444c3e8ef1d.png)

**Comment by robertknight** [comment]
I don't think this is a regression as much as a feature that was never implemented. See Slack thread: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1570033729151400

**Comment by robertknight** [comment]
I updated the title to reflect the fact that this is not a regression, based on looking at the Git history of `share-dialog.js` in the client. We simply never updated the client's share link generation after adding support for linking to a group.

**Comment by hmstepanek** [comment]
I suspect this is a regression when you look at our whole product.  My suspicion here being bouncer was updated but the client was clearly not. Previously the client sent this url to bouncer and bouncer generated an annotations url from it, when the group was added to the fragment in bouncer I suspect it broke this url as it expected the group but the client was not passing it. So, if you run an old version of bouncer before group was added I suspect you will find that this worked and that this is indeed a regression in our overall product.

**Comment by lyzadanger** [comment]
See https://github.com/hypothesis/client/issues/1201
