### ISSUE TITLE
Config value showHighlights="whenSidebarOpen" does not seem to work as expected

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1422]
From the docs: https://h.readthedocs.io/projects/client/en/latest/publishers/config/?highlight=onLoginRequest#cmdoption-arg-showhighlights

When the config value is 
```
{
  showHighlights: "whenSidebarOpen"
} 
```

The highlights don't actually seem to turn on and off when the sidebar opens and shuts. The config documentation and corresponding code should be removed or we should fix this feature.

**Comment by robertknight** [comment]
Options works for me. Tested using this change to the client dev server configuration:

```diff
diff --git a/dev-server/templates/client-config.js.mustache b/dev-server/templates/client-config.js.mustache
index b258f6043..d61ab5b9a 100644
--- a/dev-server/templates/client-config.js.mustache
+++ b/dev-server/templates/client-config.js.mustache
@@ -2,7 +2,7 @@
   window.hypothesisConfig = function() {
     return {
       // enableExperimentalNewNoteButton: true,
-      // showHighlights: 'always',
+      showHighlights: 'whenSidebarOpen',
       // theme: 'clean',
 
       // Example branding:
```
