### ISSUE TITLE
Creating/Deleting annotation does not update extension badge count

### ISSUE THREAD

**Issue by sean-roberts** [hypothesis/client#144]
### Steps to reproduce
1. create an annotation
2. refresh page (see the count reflect number of annotations on the page)
3. open sidebar and delete/add annotation

### Expected behaviour
The count would properly update the new number of annotations

### Actual behaviour
Count is not changing in response to this

**Comment by nickstenning** [comment]
You're absolutely right, but this isn't a bug as much as a missing feature. The badge is managed by the extension, which knows nothing about real-time updates. Probably better to close this for now.

**Comment by sean-roberts** [comment]
@nickstenning why would we close it?

**Comment by nickstenning** [comment]
Because it's not a defect, and we don't track feature requests in GitHub!
