### ISSUE TITLE
Re-instate the Markdown help button

### ISSUE THREAD

**Issue by klemay** [hypothesis/client#1452]
A recent update/improvement to the annotation editor involved removing the Markdown help button because it linked to an external resource that no longer existed.

old version:
![image](https://user-images.githubusercontent.com/12087705/67428662-91c07500-f5ac-11e9-8ed3-e9315d07f7c8.png)

new version:
![image](https://user-images.githubusercontent.com/12087705/67428681-9b49dd00-f5ac-11e9-92d5-3a75837ccdac.png)

We've written the following KB article to replace the old content: https://web.hypothes.is/help/formatting-annotations-with-markdown/

Now that we have a KB article we should put this button back.

**Comment by robertknight** [comment]
Perhaps we should use a more general-purpose icon than the "Markdown" logo if we re-introduce a link. I would guess that the people who recognize the logo already know how to use markdown.

**Comment by klemay** [comment]
Good point - I'll coordinate with Design!

**Comment by lyzadanger** [comment]
@klemay Any update on how we should proceed with this design-wise? One idea: use a generic help (question-mark) icon here.

**Comment by klemay** [comment]
@lyzadanger whoops dropped the ball here. Yes, Jared [suggested in Slack](https://hypothes-is.slack.com/archives/C07NXBDNW/p1572018256010900?thread_ts=1571960978.002500&cid=C07NXBDNW) that we use a ? icon and I agree, especially since you independently came up with this solution as well!
