### ISSUE TITLE
bold function in the annotation editor does not work

### ISSUE THREAD

**Issue by judell** [hypothesis/client#147]
### Expected behaviour
Type asdf
Select it
Hit the Bold button
It becomes (asterisk)(asterisk)asdf(asterisk)(asterisk)
Hit Preview
It should be bold.

### Actual behaviour
It isn't.

### Other info
Note: I'm writing (asterisk)(asterisk)asdf(asterisk)(asterisk) here to indicate the text because if I actually put it here GitHub will bold it.

Manually typing  (asterisk)(asterisk)asdf(asterisk)(asterisk) does work.

### Browser/system information
Version:0.46.0
User agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36
URL:https://www.postgresql.org/docs/9.0/static/functions-matching.html
Username:judell
Date:13 Oct 2016 14:47:39 -0700

**Comment by robertknight** [comment]
I can reproduce with any of the editor actions that modify text:

1. Create annotation
2. Start editing, enter text `foo`, select it and press bold or italic buttons.
3. Click 'Preview'

**Expected Result**
Preview shows "foo" in bold

**Actual result**
Preview shows "foo" in plain text

Note that if the markup is entered _manually_ then the changes persist. They do not persist when making changes with the editor.
