### ISSUE TITLE
Creating a new highlight removes highlights which have not been saved to the server

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#150]
### Steps to reproduce
1. Activate Hypothesis on a page
2. Severely throttle the network connection (enough that you can perform step 4 before the network request triggered by step 3 has completed)
3. Select a piece of text and click 'Highlight' to create a highlight
4. Select a different piece of text and click 'Highlight' to create a second highlight. (_You can tell if the highlight created at step 3 has been saved to the server yet by looking at whether Reply/Edit actions are displayed underneath it in the sidebar_)

### Expected behaviour

The highlight created in step 3 should continue to exist after step 4
### Actual behaviour

The highlight created in step 3 is removed in step 4
### Browser/system information

Tested with Chrome v55 and Hypothesis v0.46

**Comment by robertknight** [comment]
The workaround for users is to wait until the highlight is saved, indicated by the Edit / Delete / Reply etc. actions appearing underneath the highlight in the sidebar.

**Comment by jonjitsu** [comment]
I experience this bug so much the extension is unusable. It is as though once you hit a certain number of highlights no more can be created for the page.

**Comment by robertknight** [comment]
This issue has been fixed. The code which autosaves new highlights to the server was rewritten: https://github.com/hypothesis/client/blob/e8488b43a71ff2c97a19a69c45ee57ea1582f975/src/sidebar/services/autosave.js#L28.
