### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined when logging out

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#1542]
On prod and qa, the following exception is reported when logging out _if at least one annotation is loaded_:

<img width="590" alt="annotation-share-control-logout-error" src="https://user-images.githubusercontent.com/2458/69611676-37d92200-1026-11ea-91df-3816f38ba27b.png">

Following the stack frame links to [this line](https://github.com/hypothesis/client/blob/398e04ddd78c7c70aa6a1cebc7037d9d65e58f28/src/sidebar/components/annotation-share-control.js#L62), the `group` prop is undefined.

This prop value ultimately comes from `vm.group()` in the `annotation.html` template. The `group` method in the annotation component calls `groups.get(annotation.group)`. If `groups.get` returns undefined here it means that there is an annotation card loaded which references a group that is not loaded, which is a logically inconsistent state for the application to be in, albeit briefly. We should figure out why that is happening and fix it.

**Comment by lyzadanger** [comment]
I spent some time this afternoon seeing if I could find a solid fix to this problem, but there is too much complexity and fragility in the related code to do this in a simple way. It's complex enough that summarizing the complexity is beyond what I'm able to do at this moment.

I think that a chipping-away-at approach is possibly called for: there is code that needs refactoring in some of the remaining legacy angular components, as well as some overcomplex services (`groups`, `session`) that need some attention before we can untangle this whole thing.

On a high level, the overarching problem is too many moving parts in the code and not enough clarity of responsibility.

As a first step for _something I can do today to have some impact on this bug_, I am going to refactor one method in the `groups` service to start making that service closer to wrangle-able.

**Comment by lyzadanger** [comment]
One note before I forget: If one removes the Band-Aid fix for this in `ShareAnnotationControl`, this bug will manifest on _login_ as well as on _logout_.

**Comment by robertknight** [comment]
I can't reproduce any more, which is not surprising given that the code has been radically rewritten since this issue was filed.
