### ISSUE TITLE
Change Google Analytics Property to send fewer hits

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/client#1563]
### Problem

We received a notice from Google Analytics about exceeding data limits. We need to change this ASAP so that Google doesn't stop processing our hits. We have until Jan 3, 2020 to fix this. 

### Possible Solutions
Google has proposed the following approaches. After speaking with @robertknight the second approach (of sending fewer hits) is the one we'll most likely take.  

- Upgrading your account to Google Analytics Premium. Google Analytics Premium is a paid service that includes SLAs, technical and implementation support, and additional Premium-only features. 
- Send us fewer hits. You can do this, for example, by using the__setSampleRate method or by removing excessive tracking code calls like__trackEvent.
- If you’re measuring a mobile app, upgrade to the new style of app reporting in Google Analytics. The new style of app reporting in Google Analytics works with Firebase – Google’s integrated app developer platform. By using the Firebase SDK, you get free and unlimited event reporting for up to 500 distinct events and app-first reporting all in Google Analytics. Refer to the developer documentation (Android or iOS) to learn how to replace your Google Analytics services mobile SDKs with the Firebase SDK.

**Comment by robertknight** [comment]
I just found https://github.com/hypothesis/client/issues/1566 which causes us to send a lot more hits than we should and needs to be fixed ASAP.

**Comment by lyzadanger** [comment]
#1566 is fixed

**Comment by robertknight** [comment]
This issue was resolved at the end of last year by simply disabling Google Analytics for the client. Slack thread: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1576676786053200
