### ISSUE TITLE
datalist does not work well in Safari

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1564]
We have used the `<datalist>` tag in the tag-editor component but it has poor results in Safari and less than perfect results in Firefox. It might be worth exploring if there is some simple tweaks to the various events we can use to make it behavior more like Chrome or we build out our own customs auto complete component.

In Safari, the datalist does not clear our the options results even if the DOM is wiped out. It also re-renders the last results if the user presses the down arrow which is confusing. Pressing 'esc' key does not clear them out either. 

![datalist](https://user-images.githubusercontent.com/3939074/70190105-f0980480-16a9-11ea-9aae-3d47a69d3b72.gif)

**Comment by robertknight** [comment]
Possibly relevant upstream bugs:

- https://bugs.webkit.org/show_bug.cgi?id=201121 (Displayed datalist dropdown is out of sync with datalist options elements after DOM update)

**Comment by robertknight** [comment]
In Firefox, there is this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1474137

For which there is a test case at https://github.com/mitchhentges/firefox-dynamic-datalist-bug. I was able to reproduce the buggy behaviour described in the Firefox bug report in both Safari and Firefox.

**Comment by LMS007** [comment]
Fixed with https://github.com/hypothesis/client/pull/1713
