### ISSUE TITLE
Tag editor freezes in Chrome on macOS if there are a large number of suggestions present

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#1606]
**Steps to reproduce**

1. Apply the following diff to the client code (I tested against the v1.261.0 tag)

```diff
diff --git a/src/sidebar/services/tags.js b/src/sidebar/services/tags.js
index a897251d..8024bf2b 100644
--- a/src/sidebar/services/tags.js
+++ b/src/sidebar/services/tags.js
@@ -19,6 +19,11 @@ function tags(localStorage) {
   const TAGS_LIST_KEY = 'hypothesis.user.tags.list';
   const TAGS_MAP_KEY = 'hypothesis.user.tags.map';
 
+  const testTags = [];
+  for (let i = 0; i < 1000; i++) {
+    testTags.push(`test-tag-${i}`);
+  }
+
   /**
    * Return a list of tag suggestions matching `query`.
    *
@@ -26,7 +31,7 @@ function tags(localStorage) {
    * @return {Tag[]} List of matching tags
    */
   function filter(query) {
-    const savedTags = localStorage.getObject(TAGS_LIST_KEY) || [];
+    const savedTags = testTags;
 
     return savedTags.filter(e => {
       return e.toLowerCase().indexOf(query.toLowerCase()) !== -1;
```
2. In Chrome, go to a page with the dev client loaded (eg. http://localhost:3000) and create an annotation or page note
3. Start typing in the tag editor input field

**Expected result**

Typing is smooth. Only suggestions matching typed text are shown.

**Actual result**

Chrome browser UI freezes. The whole browser, not just the active tab, is unresponsive.

**Notes**

- Tested with Chrome Version 80.0.3987.16 (Official Build) dev (64-bit) on macOS 10.15.2
- The issue is not observed in Safari or Firefox on macOS
- I don't know if the problem is macOS-specific or also affects Windows and/or Linux

**Comment by robertknight** [comment]
Related upstream issues:

1. https://bugs.chromium.org/p/chromium/issues/detail?id=789187 (When the datalist becomes to long, it will not display anymore)
2. https://bugs.chromium.org/p/chromium/issues/detail?id=721655 (Speed up dynamic updates to options in a datalist)
3. https://bugs.chromium.org/p/chromium/issues/detail?id=889960 (HTML 5 Datalist does not scoll when using the keyboard) - This is not about the freeze, but it is an annoying issue if there are many suggestions in Chrome because it means you can't use keyboard navigation to browse them

I couldn't find an issue which _exactly_ matches our scenario, where the list of `<option>`s is static rather than being dynamically changed, but (1) and (2) seem closely related.

**Comment by robertknight** [comment]
It looks like the issue only occurs if the datalist is populated _after_ the input is shown. Here is a minimal HTML-only reproduction:

```html
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    Enter tag: <input id="tag-input" list="tag-list">
    <datalist id="tag-list"></datalist>

    <script>
      function addOptions() {
        for (let i=0; i < 1000; i++) {
          const opt = document.createElement('option');
          opt.value = `this-is-a-test-tag-${i}`;
          datalistEl.appendChild(opt);
        }
      }

      const datalistEl = document.querySelector('#tag-list');
      const inputEl = document.querySelector('#tag-input');
      inputEl.addEventListener('input', e => {
        if (e.target.value.length === 0) {
          datalistEl.innerHTML = '';
        } else if (datalistEl.childNodes.length === 0) {
          addOptions();
        }
      });
    </script>
  </body>
</html>
```

If you change the above so that the datalist is populated immediately rather than only when the input becomes non-empty, everything is OK.

**Comment by judell** [comment]
The solution for the user who ran into this problem was to clear the tag-related keys from the Chrome extension's localStorage. Here's how:

![delete-hypothesis-remembered-tags-in-chrome](https://user-images.githubusercontent.com/46509/71125700-543b2b00-219c-11ea-938e-3b669bad9d72.gif)
