### ISSUE TITLE
Keyboard focus on menu arrow should work

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1629]
Tabbing to the menu arrow button should show the focus ring, but the button has a 0x0 size. This does not allow for the blue halo on keyboard navigation in spite of the mixin being used

```
.menu__toggle {
  @include focus.outline-on-keyboard-focus;
```

![focus](https://user-images.githubusercontent.com/3939074/71601568-d4e91800-2b08-11ea-8ed2-461dd8f4a5b2.gif)

![Screen Shot 2019-12-30 at 1 33 42 PM](https://user-images.githubusercontent.com/3939074/71601611-06fa7a00-2b09-11ea-99f7-d45d7b5fe231.png)

**Comment by robertknight** [comment]
Good spot! I just noticed this when trying to tab around the interface just now.
