### ISSUE TITLE
LaTeX in the annotations

### ISSUE THREAD

**Issue by nkgsv** [hypothesis/client#165]
Some LaTeX commands do not work in the annotations:

* `$a+b=c$` not rendered (but another option `\(a+b=c\)` works fine)

* `\(\mathbb R\)` does not work

* `\( \# \)` does not work

**Comment by robertknight** [comment]
Thank-you for the feedback! In terms of what _should_ work, the set of LaTeX commands that are supported is that which is supported by the [KaTeX library](https://khan.github.io/KaTeX/).

**Comment by nkgsv** [comment]
Well, in terms of what *should work from the user experience point of view*, `$\mathbb R$` should work. Please consider an option to enable [MathJax](https://github.com/mathjax/MathJax). I know that KaTeX is faster, but as you can see many important commands are missing in KaTeX. Thank you!

**Comment by robertknight** [comment]
> Please consider an option to enable MathJax ...
> Maybe just an update to the most recent version of KaTeX is needed?

I think an update to the latest version of KaTeX would be a good starting point. According to the last commit that mentions the vendor script in `h/static/scripts/vendor/katex.js`, [we're using a version from Dec 2014](https://github.com/hypothesis/client/commit/87c26e613d2662b0c7b8f547249ff145fc9aa820). I would hope that we could now just use the latest version via npm.

I would strongly prefer not to try juggling two different math rendering libraries in the Hypothesis client if we can avoid it.

**Comment by nkgsv** [comment]
Sure, I agree with you that the update of KaTeX would be a good start. For me this would solve the issue, basically.

**Comment by nkgsv** [comment]
@robertknight Would you have any ideas when the update of KaTeX will be available in the Hypothesis client? I'm looking forward to use it!

**Comment by robertknight** [comment]
Hi @nkgsv - We haven't scheduled anyone at Hypothesis to work on it at the moment. We'd be happy to have community help with it though.

**Comment by nkgsv** [comment]
@robertknight I see. I'd love to help, but these days I'm a bit overloaded, and moreover I haven't found detailed instructions on how to set up local development environment for your project, and to test my changes. But since this is a simple update of a third-party library, wouldn't it be easier and faster for someone at Hypothesis to do this?

**Comment by robertknight** [comment]
(This bug fix will ship in the next client release - v0.56.0)

**Comment by nkgsv** [comment]
Great, thank you a lot!

I’m looking forward to trying it in production!
