### ISSUE TITLE
Login attempt always yields "Session is invalid"

### ISSUE THREAD

**Issue by rsuhada** [hypothesis/client#167]
### Steps to reproduce
1. Install Chrome plugin
2. Use/wait for a while
3. After a while when plugin is activated the user is logged out
4. If a login is attemted from the extension, an error is displayed "Session is invalid"

### Expected behaviour
Login should be possible (or simply persists from last login)

### Actual behaviour
Can't login

### Browser/system information
Same issue happens both in Windows/Chrome and Linux/Chromium

This is not an issue with incorrect login/password - they work on hypothesis.io website.
Tried changing password/restarting/reinstalling plugin, nothing helps. 
Issue since about ~week.

**Comment by dwhly** [comment]
I've seen this.

**Comment by dwhly** [comment]
@rsuhada By any chance do you have privacy badger installed?

**Comment by rsuhada** [comment]
yes I do...

**Comment by dwhly** [comment]
If you disable privacy badger, or configure an exception for Hypothesis, things should work fine.

**Comment by rsuhada** [comment]
Fantastic, Dan, thank you! I can confirm this works both in chrome and chromium-browser.
