### ISSUE TITLE
Rectify (confusing) structure of `session` store module

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#1676]
The current `session` store module advertises a state structure like so in its `init`:

```
function init() {
  /**
   * Profile/session information for the active user.
   */
  return {
    /** A map of features that are enabled for the current user. */
    features: {},
    /** A map of preference names and values. */
    preferences: {},
    /**
     * The authenticated user ID or null if the user is not logged in.
     */
    userid: null,
  };
}
```

This is misleading on a couple of counts.

Firstly, the entire `session` state object is overwritten by a user `profile` object retrieved from the API. Secondly, the resulting properties in a "populated" session include several that are not declared here, e.g. `authority`, `groups`, `user_info`. This confusion is manifest in code: `store.getState().session.user_info`, e.g.

There are a few possibilities for mitigation. Tactics include:

* Renaming the `session` module to, say, `profile`
* And/Or, restructuring the `session` state objects to have a `profile` property object that is entirely controlled by the shape of whatever is returned by the API service
* And/Or, initializing all of the expected properties instead of a select few, though this is an arms race in keeping up with the API response shape.

**Comment by robertknight** [comment]
> And/Or, restructuring the session state objects to have a profile property object that is entirely controlled by the shape of whatever is returned by the API service

This was done in https://github.com/hypothesis/client/pull/2012

> Renaming the session module to, say, profile

https://github.com/hypothesis/client/pull/2012 kept the name of the module but it did update some of the method names and internal comments to be more consistent about using the term "profile" to refer to the data that comes back from `/api/profile`.

**Comment by lyzadanger** [comment]
I think the stuff cited by @robertknight above satisfies the main thrust of this ticket.
