### ISSUE TITLE
Horizontal scrollbar unexpectedly active for editor icons on Win 10 

### ISSUE THREAD

**Issue by judell** [hypothesis/client#1678]
Expected:

> You’ll only see it if not all the controls can fit AND the OS doesn’t use “overlay” scrolling (as iOS and macOS do). 

Actual:

![image](https://user-images.githubusercontent.com/46509/72380376-1f05f800-36ca-11ea-90fa-c7b249a1117d.png)

**Comment by LMS007** [comment]
I'm not seeing this issue manifest in 1.272.0 on Chrome, FF or Edge. @judell can you confirm you still see the issue on Win 10?

**Comment by judell** [comment]
Yes, still happening.

**Comment by robertknight** [comment]
From my distant memory, I think Jon might have been using a device with a touch screen. In the current version the buttons get larger so it is more obvious what is going on and the toolbar has a `touch:overflow-x-scroll` Tailwind style. With the default sidebar width, the scrollbar is very much needed, so I'm closing this as working-as-expected.

Here is what it currently looks like in Chrome with touch-device emulation enabled and the default sidebar width:

<img width="484" alt="Touch device sidebar" src="https://github.com/hypothesis/client/assets/2458/1850c24e-6a58-43cb-ab69-3ac837dcf116">
