### ISSUE TITLE
Adding a reply when logged out causes nested "You must be logged in..." messages

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1691]
A quick inspection of the DOM is showing that these elements grow each time a reply is clicked, but they don't seem render in Mac; however, on Window 10 (both in Chrome and FF) they show up for some strange reason.

![Image1](https://user-images.githubusercontent.com/3939074/72642041-5cfc5980-3920-11ea-8dd3-6b9bdcf9e594.png)

**Comment by lyzadanger** [comment]
@LMS007 Could you see if you can reproduce now? I have a hunch this was fixed by migration.

**Comment by robertknight** [comment]
The "Login required" message that shows when attempting to reply while logged out was moved to a panel at the top of the sidebar and we have logic in place to ensure that only one such panel is visible at a time:

<img width="482" alt="Must be logged in" src="https://user-images.githubusercontent.com/2458/102400390-c32ea800-3fd9-11eb-8ed5-4a802412d509.png">
