### ISSUE TITLE
Unable to align text directionality to RTL

### ISSUE THREAD

**Issue by nadavkav** [hypothesis/client#1716]
We are using Hebrew to write annotations, and we are unable to set text alignment to "right" and also unable to set text directionality to RTL.

![image](https://user-images.githubusercontent.com/231168/73119819-f60a2080-3f6f-11ea-8703-ef6f9150ea18.png)

Please see if you can add these buttons to the annotation editor.

**Comment by robertknight** [comment]
Great, thanks for confirming! We'll look into integrating this change into the Hypothesis client (and therefore also the Hypothesis LMS app) soon.

**Comment by robertknight** [comment]
This issue has been resolved as per the above comments in v1.298.0 of the client (go to Help => About this version). That is available now in the bookmarklet, LMS integration, and at https://via.hypothes.is. It will appear in the browser extension shortly.

Please let me know if you encounter any issues with it.
