### ISSUE TITLE
Add back "tab" to create a new tag (feature) back to the new TagEditor

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1736]
This feature was removed, but is sorely missed. The behavior should be that tabbing off the input after typing into it will add (or attempt to add) whatever tag you have typed.

**Update**
I'm going to leave this ticket open for now as the issue is partially resolved. Our new tag editor implementation does not by default have a selected index from the autocomplete list. In other words when you type `Tab`, we don't assume that the first one is the assumed selection. Therefore the tab feature will only add a tag when what you type exactly matches an option from the autocomplete list. That however may be missing the the value of the tab feature in the first place as users generally feel like its an autocomplete shortcut. e.g. typing  "dinosa" + `Tab` should add the tag "dinosaur" if and only if "dinosaur" exists in the autocomplete list.

The short of it is, we perhaps need to forgo the `-1` index and default that to `0` so when a user presses `Tab`, it picks the first option in the list. `Tab` would only not work when nothing is in the list. 
That is the case when
1. Nothing is typed.
2. Its a new tag that is not a subset of anything else

**Comment by robertknight** [comment]
https://github.com/hypothesis/client/issues/1954 raises a related but slightly different issue. The user is trying to create a tag by entering text in the tag editor and clicking "Post to ..." _without pressing Enter or Tab_ in the tag field.
