### ISSUE TITLE
LMS grader - clicking "View n more in conversation" keeps that thread open, even when switching to other students in the grading bar

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/client#1737]
You can see an assignment with threaded conversations in the Blackboard course "Example" assignment "test 1".

To replicate:
1) Use a Bb assignment with note replies from students
2) Select one student in the grading bar
3) Click "View n more in conversation".
4) Change to a new student in the grading bar.

User expectation: that the conversations would "reset" fo the new student, with the threads only showing that student's annotations.

What happens: threads that have been opened stay open, with all replies visible.

https://hypothesis.zendesk.com/agent/tickets/8171

**Comment by mkdir-washington-edu** [comment]
Tickets:
https://hypothesis.zendesk.com/agent/tickets/8233

**Comment by klemay** [comment]
Note: during backlog review today, our developers noted that upcoming migration work for our `annotation` and `thread` components will make this much easier to fix - so we're going to look at tackling this after both migrations are complete. I am going to keep tracking this until then.
