### ISSUE TITLE
Annotations aren't in location sort order

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#174]
### Steps to reproduce
1. Browse to: https://via.hypothes.is/http://www.dailymail.co.uk/news/article-3974846/Stunning-new-data-indicates-El-Nino-drove-record-highs-global-temperatures-suggesting-rise-not-man-emissions.html
2. Open sidebar.

### Expected behaviour
Annotations should be in proper location sort order 

### Actual behaviour
They're not.

### Browser/system information
Via / Chrome

![screen shot 2016-12-04 at 8 16 57 am](https://cloud.githubusercontent.com/assets/1413074/20867474/1482e208-b9fa-11e6-9bb9-359fe03d4db0.png)

**Comment by dwhly** [comment]
Might be related to https://github.com/hypothesis/client/issues/248

**Comment by sheetaluk** [comment]
I tested this out. I created a few annotations, and then restructed the host page. The annotations appeared in the same order that they were created even though the content of the page was shuffled around.

**Comment by sean-roberts** [comment]
Unless someone can point me to evidence to show differently, this is behaving exactly like #248 and is, unfortunately, working as designed. "Location" is not based on actual page location but rather the start value of the TextPositionSelector. That page must have had several changes and but the ordering is working as designed - though that design left us susceptible to this issue.

**Comment by dwhly** [comment]
Opened as a new issue: https://github.com/hypothesis/product-backlog/issues/266
