### ISSUE TITLE
Hover over time stamp no longer shows fully specified time

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#175]
### Steps to reproduce
1. Go to an annotation in the sidebar on a desktop/laptop computer
2. Hover over the timestamp.

### Expected behaviour
It used to be that the full date and time would be shown on hover.  This is useful for telling time of day for instance.

### Actual behaviour
Nothing.

### Browser/system information
Chrome / extension.

**Comment by robertknight** [comment]
Fixed in https://github.com/hypothesis/client/pull/546
