### ISSUE TITLE
group-list-item-common.js may not be a good name

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1754]
orgName() also get used in group-list.js so the file name is a bit misleading to assert that it is only for group-list-item.js

**Comment by lyzadanger** [comment]
There are two functions in this itty-bitty util. I would argue that the second (`trackViewGroupActivity`) doesn't provide any value in being abstracted, and the first, if we want to keep it in a util, could be in a util for organization metadata. But I don't know that it's worth abstracting it if it's only used in one place.

**Comment by robertknight** [comment]
Closing this issue as a very minor piece of tech debt in the grand scheme of things, and something we can address as and when we have other reasons to touch the code.
