### ISSUE TITLE
HTML in quote text is sanitized but not escaped

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#177]
### Steps to reproduce
1. Visit [this gist](https://gist.github.com/robertknight/f010d0793a0ded4476d380d267023bd2)
2. Activate Hypothesis and highlight the HTML markup for the `<img>` tag
3. Click Annotate

### Expected behaviour
The HTML markup highlighted appears as plain text in the quote of the annotation in the sidebar

### Actual behaviour

![html-in-quotes](https://cloud.githubusercontent.com/assets/2458/21041762/14653b4c-bde5-11e6-8a4e-89a2535a5ed7.png)

### Notes

Although the markup is not escaped, it is sanitized so only a whilelist of HTML elements can be rendered in quotes. Style and script tags in particular are removed.

**Comment by lyzadanger** [comment]
@robertknight Can't reproduce; have we fixed this?

![image](https://user-images.githubusercontent.com/439947/92791130-68eacf00-f37a-11ea-89c1-19615717e164.png)

**Comment by robertknight** [comment]
We rewrote this component entirely in Preact since the issue was opened, so I'm not surprised that it is fixed.
