### ISSUE TITLE
Help  panel navigation arrow buttons lose focus when toggling between them

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1783]
When changing between the help and version panel by clicking the button on the right side, the button itself looses focus and makes for a confusing experience when using a screen reader. One solution may be to migrate this to a tab structure so its less confusing when using just the keyboard navigation. Another good reason for that is the button themselves look like links but act like buttons which teaches away from our UX language when visually looking at the panel. In any case, we should fix the focus issue or move to a tab system.

![Screen Shot 2020-02-12 at 10 03 26 AM](https://user-images.githubusercontent.com/3939074/74363227-00555880-4d7f-11ea-9396-bd117521bc9a.png)

**Comment by robertknight** [comment]
> One solution may be to migrate this to a tab structure so its less confusing when using just the keyboard navigation

@acelaya implemented this solution in https://github.com/hypothesis/client/pull/5980.
