### ISSUE TITLE
Set appropriate language hints for the sidebar HTML page

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#1794]
## Problem

The sidebar HTML page, which is actually part of the h and browser-extension rather than client repos, does not currently specify the primary language of the UI. This causes several problems:

- Automated WCAG compliance checkers complain about the lack of `lang` attribute on the `<html>` element in the sidebar's HTML document
- When annotating a document that uses a non-English language (eg. https://lemonde.fr) the screen reader can end up reading UI elements with a voice appropriate for the language of the host document rather than the language of the UI (currently always English).

## Discussion

Solving this isn't quite as simple as slapping a `lang="en"` tag on the HTML page because that will apply to _all_ content in the sidebar, including annotation quotes and bodies. Having those read out with an English voice when they are not English would be, I imagine, quite annoying.

The ideal behavior would be that the UI is read with a voice for English (or whatever language it is in, when we add translation in future) but user-generated content is read in a voice appropriate for that content. There is a way to tell the browser that the language of an element is unknown (`lang=""`) and ideally, the browser would detect the language itself. Chrome does have an experimental option to auto-detect the language in that scenario, which produces the desired result:

<img width="913" alt="Screenshot 2020-02-14 15 22 25" src="https://user-images.githubusercontent.com/2458/74544558-3f320c80-4f3f-11ea-86fa-b549423f30a2.png">

Chrome (without this option) and Safari don't do this. I'm unclear as yet whether `lang=""` makes them default to the language of the host page (probably OK), the language of the sidebar's HTML document (not so good) or the user's default language (probably OK).

Twitter seems to do server-side processing of tweets to determine the language and it sets `lang="<code>"` appropriately on each tweet. We could do the same, but this will obviously require a fair amount of work.

Some simple approaches that we could potentially use to start with:

- Set `lang="en"` on the sidebar, `lang=""` on user-generated content and leave it up to the browser to do something appropriate or for the user to configure how unspecified languages are handled.
- Set `lang="en"` on the sidebar but for annotation quotes and bodies, use the language of the host page, or unknown if the host page doesn't specify. The assumption here is that most annotations are in the same language as the document
- Anything else?

**Comment by LMS007** [comment]
This is not easy to come up with a set of rules to apply.  Let me see if I can understand this more specifically.

Problem 1.
lang value for sidebar UI

Problem 2. 
lang value for annotations.

My understand is we'll generally see a single outer html tag for the page, then our html tag for the sidebar. I don't think we should be tampering with the lang value on the page itself. Some pages even allow users to change that around.

I also noticed twitter can take a `lang` value in the URL and it will change the UI to use that language.
example:
https://twitter.com/neiltyson?lang=fr

Perhaps we could allow a lang value for a logged in user tied either to a cookie or the hyp account and that could take president? I don't think harm is setting it to blank if that value is missing.

**Comment by robertknight** [comment]
> lang value for annotations. (are you talking about the highlights on the page?)

I'm referring specifically to _annotation cards_ in the sidebar, or other places in the sidebar that can display user-generated content. I'm not proposing to alter the language of the _document_ itself. What we might do is gather information _from_ the document about its language and use that to inform the browser of the language that quotes from the document, rendered in the sidebar, are in. As a first step though, I'm proposing just to tell the browser that user-generated content in the sidebar is in an "unknown" language (`lang=""`), which leaves it up to the browser to figure out. Does that make sense?

> Perhaps we could allow a lang value for a logged in user tied either to a cookie or the hyp account and that could take president?

Providing the user with the option to configure the default language assumed for annotation bodies and tags would be an option, although if we can make things "just work" I think that would be preferable.

**Comment by LMS007** [comment]
Okay that does make sense, and I'm hoping browsers can just make things work sooner than later. Sounds like Chrome is furthest along in that regard.

**Comment by robertknight** [comment]
The basic option of setting `lang="en"` on the sidebar HTML page and `lang=""` on any elements displaying user-generated content is now done. Possible work for the future is determining the language of quotes automatically based on the host document's language information, or doing server-side processing of annotation bodies to guess language from content.
