### ISSUE TITLE
annotations tab incorrectly selected at https://www.biorxiv.org/content/10.1101/871517v1.full

### ISSUE THREAD

**Issue by judell** [hypothesis/client#1827]
A biorxiv user compares the behavior of 3 urls for which only pagenotes exist, and where the pagenotes tab should be selected in all 3 cases.

1. https://www.biorxiv.org/content/10.1101/252593v4
2. https://www.biorxiv.org/content/10.1101/497495v2
3. https://www.biorxiv.org/content/10.1101/871517v1

In case 3, the annotations tab is incorrectly selected.

**Comment by lyzadanger** [comment]
The catalyst to this behavior appears to be the presence of at least one reply on one of the document's page notes. I can reproduce locally on `master` by creating a bunch of page notes in a group (`Page Notes` tab is correctly selected automatically) and then adding a reply to one of them (the app stays on the `Annotations` tab).

It looks like there is something in the threading logic that is involved, but more investigation is needed here...
