### ISSUE TITLE
Implement save-on-keystroke for `AnnotationOmega`

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#1838]
The legacy ng-1 `Annotation` controller currently allows the saving of an annotation by typing `ctrl - enter`.

A few things here:

* Is this feature known about or used by any large number of our users? We don't have the data to be able to answer that question, but, point being: let's simply make sure we want to re-implement this before we do so. It's not a big chunk of work, so it's probably fine. But is there some way to surface this capability to our users?
* Find a (p)react-ic way of implementing this keyboard-event handling and do it

Part of #1650

**Comment by lyzadanger** [comment]
An initial question I have when looking at this a little—and this touches on a11y—is what element the `keyDown` event handling should apply to.

In the legacy `Annotation` template, the entire annotation-card `div` has an event listener for this on it. That seems problematic because:

* A `div` is not an interactive element, so key* handling is not going to pass a11y-lint muster
* What does it mean to save an annotation if it's not in editing mode? I don't think there's value to that, as it won't have any changes to save

Is the idea that a user should be able to type in the main markdown editor for the annotation's content and type `ctrl/cmd enter` to save the annotation? Is it expected that this would work in the tag editor?

I think we need to circle back to what this is _supposed_ to do and then consider how to implement it in an accessible way, if we want it!

**Comment by dwhly** [comment]
> Is the idea that a user should be able to type in the main markdown editor for the annotation's content and type ctrl/cmd enter to save the annotation? Is it expected that this would work in the tag editor?

Yes-- I think what we were trying to do is move to a comprehensive set of keyboard shortcuts for the annotation client over time.  Is that goal compatible w/ a11y?

**Comment by dwhly** [comment]
(I just noticed that ctrl-enter works here in gh to enter as well)
