### ISSUE TITLE
Anchoring is very slow on certain documents/URLs

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#189]
### Steps to reproduce
1. Go to https://www.nytimes.com (which has 27 public annotations at the time of writing)
2. Activate Hypothesis

### Actual behaviour
The browser hangs for several seconds after annotations are fetched and before they are identified as Orphans. Firefox' profiler shows a large amount of time being spent in diff-match-patch's fuzzy string search.

### Additional details
Tested with Hypothesis v0.51 on Firefox 53, Chrome 57.

**Comment by robertknight** [comment]
Another and much worse instance of this was reported today by @jeremydean on https://www.nap.edu/read/9853/chapter/3 where the public channel as ~350 annotations. At a quick glance, it looks like many of the orphans might be from other chapters of the same book (?).

Just in case the annotations change in future, I've posted a dump of them at https://gist.github.com/robertknight/108ba6ae921ad567040ac0ef637f94f5

**Comment by robertknight** [comment]
I've been doing some work on improving how fuzzy string matching works in the dom-anchor-text-quote lib, which could be of use here. This is a profile from the current diff-match-patch based quote anchoring:

<img width="570" alt="bitap-string-match-profile" src="https://user-images.githubusercontent.com/2458/27547423-db92214a-5a8d-11e7-95b5-6ded292a0940.png">

Here is the profile from a version of dom-anchor-text-quote using a new approx string matching lib:

<img width="544" alt="approx-string-match-profile" src="https://user-images.githubusercontent.com/2458/27547372-ae31cf7a-5a8d-11e7-8059-91822aecd41e.png">

**Comment by lyzadanger** [comment]
I've re-verified that performance on https://www.nap.edu/read/9853/chapter/3 with the current production extension is unacceptable. Once anchoring is complete, the sidebar is responsive and scrolling is smooth, but the anchoring process is painful.

**Comment by robertknight** [comment]
Fixed by https://github.com/hypothesis/client/pull/2814 (client release >= v1.617.0).
