### ISSUE TITLE
editor toolbar scrolls on windows 10 2nd monitor

### ISSUE THREAD

**Issue by judell** [hypothesis/client#1981]
See https://jonudell.info/h/editor-toolbar-scroll-behavior.mp4

![image](https://user-images.githubusercontent.com/46509/78062062-fa253680-7342-11ea-8885-3cfc69aad5c3.png)

This does not happen on the primary monitor, only the secondary.

/cc @klemay

**Comment by klemay** [comment]
@judell is your 2nd monitor a touch screen? or does your browser potentially "think" it is? in today's backlog review @robertknight mentioned the client relies on info from the browser when determining whether to display the scroll bar or not

**Comment by judell** [comment]
The second monitor is not a touch screen. 

This became so annoying today that I discovered the following fix, which is to remove the following from sidebar.css.

/*
@media (pointer: coarse) {
  .markdown-editor__toolbar {
    padding: 0;
    padding-bottom: 10px;
    flex-wrap: unset;
    overflow-x: scroll;
  }

  .markdown-editor__toolbar-button {
    min-width: 44px;
    min-height: 44px;
  }
*/

**Comment by robertknight** [comment]
As noted above, we rely on the browser to tell us whether the device is a touch screen or not and adjust the size/hit targets of buttons accordingly. If the browser is providing incorrect information for any reason, I would suggest to create a minimal test case using `@media (pointer: coarse)` queries and take it up with them.
