### ISSUE TITLE
Annotate/Highlight buttons not visible on nzz.ch

### ISSUE THREAD

**Issue by 0x7969** [hypothesis/client#2009]
### Steps to reproduce
1. Visit https://www.nzz.ch/feuilleton/niall-ferguson-sechs-fragen-zum-coronavirus-an-xi-jinping-ld.1550428 (or any other page on nzz.ch)
2. Mark text

### Expected behaviour
The Annotate/Highlight speech-bubble-popup should appear.

### Actual behaviour
It appears to not appear, but then I noticed that when you mark text at the leftmost part of the screen, you can see small parts of the popup, so it seems to be opened _behind_ the .pageholder div.

### Browser/system information
Firefox 47.0.1 on Archlinux, both using via.hypothes.is and the bookmarklet.

**Comment by robertknight** [comment]
This looks like an issue with the z-index of the adder. On this particular page the `<hypothesis-adder>` element needs a minimum z-index of 10000 in order to be visible. It is currently 999. See https://github.com/hypothesis/client/blob/334bce32211e84317fec8b156ba3b2963eef2ddd/src/annotator/adder.js#L95.

**Comment by robertknight** [comment]
A smart solution might be to query `getComputedStyle(element).zIndex` for the element(s) containing the selected text and each of their ancestors. A trivial solution that will work on this site and probably a few others is just to change the `zIndex` value to 10000.

**Comment by esanzgar** [comment]
Siblings elements could also hide the view of the adder:
```
<ol>
    <li style="z-index: 20000000">I could obfuscate the view</li>
    <li>annotate me</li>
</ol>
```

Selecting `annotate me` could place the adder in the view of the the first sibling.

Alternative ideas:
* find the greatest z-index on the page once by looping through all the elements of the page and cache the value
* hit-test the area where the adder will show to determine the correct z-index
