### ISSUE TITLE
Deleting an annotation causes the page to scroll to top

### ISSUE THREAD

**Issue by kevinjalbert** [hypothesis/client#2035]
### Steps to reproduce

1. Create an annotation
2. Scroll down the page
3. Delete annotation

### Expected behaviour

Page's scroll position shouldn't change.

### Actual behaviour

Page's scrolls to the top of the page.

### Browser/system information

- macOS 10.15.4
- Brave (v 1.5.123 && v 1.7.92)

### Additional details

[GIF showing issue](https://monosnap.com/direct/rNANt1vJEat670oEF9diIwwEapOEFD)

This is pretty frustrating (especially on mobile), if I'm trying to correct a highlight (expanding/contracting the highlight itself).

I saw https://github.com/hypothesis/client/issues/566, although that seems to be before the delete of the annotation actually occurs.

**Comment by mkdir-washington-edu** [comment]
Also heard about this here: https://hypothesis.zendesk.com/agent/tickets/10064

I tested on MacOS 10.14, Chrome 81, FF 76. This occurs with the extension, the Bookmarklet, and in Via. It occurs with a single annotation on the page and multiple annotations on the page.
