### ISSUE TITLE
End support for Internet Explorer 11 (IE11)

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#2043]
This issue is about officially ending support for IE 11 in the Hypothesis client, so we can spend our development / testing efforts that go to supporting that browser on improvements for the vast majority of users that are using newer browsers.

Note that the LMS app definitely does not support IE 11, so we don't need to concern ourselves about that.

Things we need to address:

1. What is the time-frame for ending IE 11 support?
2. What will users experience if they visit a page that embeds the Hypothesis client if they are using a browser that the client definitely doesn't support?
3. Should we set up some kind of advance notice such as an in-app banner to tell users that support for IE 11 will end by a certain date?

Re point (1) I need to gather usage stats, but we've accidentally broken IE support on a couple of occasions recently and it took quite a while for someone to notice. This suggests to me that we can afford to make this happen pretty soon. Perhaps end of June 2020?

A thought I had re point (2) is that perhaps we could create a dummy version of the sidebar and the button that opens/closes it, where the sidebar shows a notice that Hypothesis annotations are not available in this browser and a link to view them on the "h" website.

**Comment by robertknight** [comment]
Related Slack thread: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1588062136439800

**Comment by klemay** [comment]
@robertknight checking in on the status of this - do we need to do anything else before we can say we have ended support for IE11, or can we close the issue?

**Comment by klemay** [comment]
Notes from backlog meeting: before closing this issue we'll need to remove IE-specific code from the client. This will have the advantage of making the client smaller + faster; however it's not urgent.

**Comment by robertknight** [comment]
We've now completed the removal of IE 11 support from the code. The boot scripts handles exactly what does happen when the client attempts to start in IE 11. Currently it just logs a console warning with a link to a knowledgebase article. We have discussed showing a banner in when the host page is an environment that we control (eg. Via, LMS, as opposed to a third-party publisher's page).

**Comment by klemay** [comment]
We have an issue (including a screenshot from an IE11 user) for showing a banner here: https://github.com/hypothesis/product-backlog/issues/1141

**Comment by robertknight** [comment]
This issue is resolved. We ended support for IE 11 last year and added code in the boot script to notify users about unsupported browsers.
