### ISSUE TITLE
Remove unused SVG icons

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#2053]
It looks like there are some unused icons in our code base. We should examine all icons and remove any svg objects that are no longer used. It also may be worth inventing a new name convention for svg files so they can be searched for more easily in the future so its very clear if they are not used. A search for something like "filter" is not terrible obvious.

**Possibly deprecated** 

- [ ] account.svg
- [ ] filter.svg

**Comment by robertknight** [comment]
I updated the description to remove a discussion about unifying icons in the LMS app and client. This has been done by making both use the `SvgIcon` component from the frontend-shared package.

**Comment by robertknight** [comment]
These icons were removed in 84cb056fd054ac37f67324e92def4652767f311a.
