### ISSUE TITLE
After IE11 support has ended, upgrade escape-string-regexp

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#2071]
Version 2.x of this package was incompatible with IE11, so it has not been upgraded. As soon as we no longer support IE11, we can upgrade this package.

_Simply open this PR and merge it after testing_
https://github.com/hypothesis/client/pull/2068

**Comment by robertknight** [comment]
IE 11 support was ended and this change was implemented in 32658efde14d767b81d53a4c07abbf1046cbd789.
