### ISSUE TITLE
Exception being thrown in FireFox

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#2080]
### Steps to reproduce
1. Open FireFox (version 75)
2. Create a highlight or annotation on localhost:3000
3. Observe an exception in the debugger 

![Screen Shot 2020-04-23 at 2 26 45 PM](https://user-images.githubusercontent.com/3939074/80151439-ea2dfa80-856e-11ea-82c3-70316c63a145.png)

### Expected behaviour
Should not throw an exception

### Actual behaviour
Throws an exception

### Browser/system information
Firefox v75

**Comment by robertknight** [comment]
I was able to reproduce this, with a couple of notes:

1. I didn't observe any errors in the console or broken behavior for users
2. I had to enable "Pause on exceptions" in the debugger.

(1) and (2) tells me that something is catching this exception and ignoring it. It still looks like an unexpected error though.

**Comment by LMS007** [comment]
Rob, I think considering this is non-breaking, then it can be lower priority

**Comment by robertknight** [comment]
I couldn't reproduce this with Firefox 91 and the current master branch of the client.
