### ISSUE TITLE
openSidebar is not working from via

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#2083]
### Steps to reproduce
Open up a pdf (or html) in via as follows

https://via.hypothes.is/https://arxiv.org/pdf/1908.04683v3.pdf?via.open_sidebar=false

or (new way)

https://via.hypothes.is/https://arxiv.org/pdf/1908.04683v3.pdf?via.client.openSidebar=false

### Expected behaviour
The sidebar should be closed

### Actual behaviour
Sidebar remains open.

### Additional details
It looks like the client is casting that value from the hypothesisConfig to a boolean in host-config, but the annotator gets its value in a different way than the sidebar itself, so it never sees the converted value from `host-config.js`. We may need to implement something similar what was done in host-config on the annotator itself.

**Comment by jon-betts** [comment]
Probably best to accept a few things as falsy:

* "False"
* "false"
* "0"
* ""
