### ISSUE TITLE
Don't show leave-group buttons in LMS

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#2084]
When there's more than one group in the client's dropdown menu (for example this happens in LMS when a teacher launches an assignment and we show them all of the course's section groups, if the course has multiple sections) the client shows leave-group buttons for each group:

![Screenshot from 2020-04-24 19-27-33](https://user-images.githubusercontent.com/22498/80356379-4e9fd100-8871-11ea-890e-f4fcb9deefc3.png)

These buttons shouldn't be shown in an LMS context since you can't leave LMS groups.

**Comment by LMS007** [comment]
The current thought is to add `allowLeavingGroups` to the .js-config object coming from LMS.
