### ISSUE TITLE
Group name and expanded search bar overlap

### ISSUE THREAD

**Issue by klemay** [hypothesis/client#2160]
Part of https://github.com/hypothesis/client/issues/1289. 

We currently have a 25-character limit on group name[s (which we would like to expand for our LMS users](https://github.com/hypothesis/lms/issues/1599)). One of the reasons for that limitation is that we didn't want group names to overlap with the search bar in the client when it's expanding... but that is already happening once a group name gets to 12 characters or so:

![image](https://user-images.githubusercontent.com/12087705/81851087-ed415880-9526-11ea-8cd1-022ec091f473.png)

Note that this affects all users, not just our LMS users.

If we can fix this issue, we'll be set up to expand the 25-char limit.

**Comment by robertknight** [comment]
Fixed as part of https://github.com/hypothesis/client/issues/6006.
