### ISSUE TITLE
"Show all annotations" button disappears when saving an annotation

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#2194]
If there is a selection in the sidebar (ie. only a subset of annotations are shown and a "Show all annotations" button is shown) and you edit and save a selected annotation, the "Show all annotations" button temporarily disappears while the annotation is being saved.

For example, if the sidebar looks like this:

<img width="486" alt="Screenshot 2020-05-22 10 34 42" src="https://user-images.githubusercontent.com/2458/82654155-345ed600-9c18-11ea-9797-6be10dec064a.png">

The "Show all annotations" button will disappear when I click "Post to Personal Reading".

**Steps to reproduce:**

1. Create an annotation and save it
2. Click on the annotation's highlight in the page in order to select the annotation in the sidebar
3. Click the Edit button on the annotation card and then click the "Post to ..." button

**Expected result:**

The "Show all annotations" button remains visible while the annotation is being saved.

**Actual result:**

The "Show all annotations" button disappears while the annotation is being saved and re-appears afterwards.

**Comment by LMS007** [comment]
Note, the same behavoir is seen for clear search, the fix should apply to both cases.
![search](https://user-images.githubusercontent.com/3939074/85473536-3fcf5500-b568-11ea-89fd-07ae5ac43e22.gif)
