### ISSUE TITLE
Sidebar script fails to load on firefox

### ISSUE THREAD

**Issue by aadilayub** [hypothesis/client#2291]
### Steps to reproduce
1. Install the Hypothesis bookmarklet on Firefox
2. Go to any webpage
3. Click on the hypothesis bookmarklet

### Expected behaviour
The hypothesis highlighter and sidebar load properly. The sidebar is visible on the page. Highlights made on the page persist. 

### Actual behaviour
Only the highlighter loads, but not the sidebar. The sidebar is not visible on the page. Highlights made in this state are not saved.

### Browser/system information
Firefox 77 on macOS

### Additional details
![image](https://user-images.githubusercontent.com/31581044/86084307-f2963a80-bab5-11ea-9cb8-9ca3cbed5893.png)

Looking in the console, I find this warning:
```
Loading failed for the <script> with source “https://cdn.hypothes.is/hypothesis/1.459.0/build/scripts/sidebar.bundle.js?521e5a”.
```

This only started happening last night. Before that, the bookmarklet was running as expected.

**Comment by aadilayub** [comment]
This error does not occur with the [unofficial extension](https://addons.mozilla.org/en-GB/firefox/addon/unofficial-hypothesis/) or when using `http://via.hypothes.is/$(url)`

**Comment by robertknight** [comment]
Hello,

I tested this morning with Firefox 77.0.1 on the same URL shown in your screenshot but was not able to reproduce:

<img width="800" alt="Screenshot 2020-06-30 at 10 02 21" src="https://user-images.githubusercontent.com/2458/86106939-1d35c280-bab9-11ea-8bb4-b780df2b04d0.png">

If you paste the URL from your console warning into a new browser tab, does it load successfully?

Also, does the network tab in the browser dev tools have any more information about _why_ the URL failed to load for you?

**Comment by aadilayub** [comment]
> If you paste the URL from your console warning into a new browser tab, does it load successfully?

@robertknight yes it does.

> Also, does the network tab in the browser dev tools have any more information about why the URL failed to load on your system?

The sidebar js and css files don't show up in the network tab

![image](https://user-images.githubusercontent.com/31581044/86109484-defeca00-badd-11ea-9b6c-a8ed0b9cc29f.png)

> I tested this morning with Firefox 77.0.1 on the same URL shown in your screenshot but was not able to reproduce

Hmm... it could be a network error on my end.

Several other resources are 404-ing for me as well. They seem to be related to hypothesis

```
Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/components/svg-icon.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/annotator/adder.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/variables.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/mixins/focus.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/annotator/bucket-bar.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/mixins/reset.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/mixins/utils.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/annotator/highlights.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/mixins/a11y.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/annotator/annotator.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/reset.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/components/svg-icon.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/annotator/adder.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/variables.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/mixins/focus.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/annotator/bucket-bar.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/mixins/reset.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/mixins/utils.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/annotator/highlights.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/mixins/a11y.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/annotator/annotator.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/reset.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/src/styles/annotator/pdfjs-overrides.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: file:///data/jenkins/workspace/client_master/node_modules/katex/dist/katex.min.css
```

**Comment by robertknight** [comment]
> Several other resources are 404-ing for me as well. They seem to be related to hypothesis

To build Hypothesis we compile many source files into a small number of JavaScript and CSS "bundles". The bundles contain links back to the input source files for debugging purposes, but these are not actually used when using the app normally. The errors in your log appear to be references to the source files, I'm guessing that was because you had the dev tools open and maybe went to the "Sources" tab?

> Hmm... it could be a network error on my end.

Hmm.. a few things to try:

1. Can you try clearing your browser cache via History => Clear Recent History and then only tick the "Cache" option
2. Test whether you can reproduce the issue in a Private Window
3. Have a look in the console to see whether there is any more information about why the sidebar failed to load other than the message you posted above

The fact that https://via.hypothes.is works is interesting, as it loads the sidebar from exactly the same URL as when using the bookmarklet.

**Comment by aadilayub** [comment]
It works now! Looks like it was a network issue.
