### ISSUE TITLE
Annotation fails on LinkedIn Pulse articles

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#233]
### Steps to reproduce
1. Go to https://www.linkedin.com/pulse/ai-rewriting-john-keynes-equation-employment-denis-sproten
2. Activate chrome extension or FF bookmarklet
3. Select text to annotate

### Expected behaviour
Adder should appear

### Actual behaviour
It does not until the blue circle at right is clicked.  There is some additional javascript on the page which is interfering.

### Browser/system information
Modern chrome / extension.  Or modern FF w/ Bookmarklet

**Comment by sean-roberts** [comment]
pretty sure they are capturing the selection event and not propagating it until their designated action happens. Then they allow it to go forward

**Comment by robertknight** [comment]
Content security policy prevents loading the bookmarklet on that article now, but using the Chrome extension I can no longer reproduce the issue. I don't know whether this was fixed on our side or by a change in their site.
