### ISSUE TITLE
H sidebar buttons all look the same on this site using FF bookmark

### ISSUE THREAD

**Issue by heatherstaines** [hypothesis/client#235]
### Steps to reproduce
1. Using the FF bookmark on URL https://backchannel.com/a-gourmet-guide-to-wifi-b9a308e662a9#.asa9xlpzv
2. The sidebar buttons and the buttons that pop up after you highlight text all look the same.
3.

### Expected behaviour
Tell us what should happen.

Buttons should look normal when H launches

### Actual behaviour
Tell us what happens instead.

All the buttons look the same.

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

FF 51.0.1
Sierra 10.12.2

### Additional details
If you have other information which might be helpful, please include it. If a
screenshot will help to illustrate the issue you are reporting, please include
one.
![image](https://cloud.githubusercontent.com/assets/24781335/23094433/c083d56e-f5c6-11e6-8751-989a6f48524e.png)

**Comment by nickstenning** [comment]
Thank you for reporting this! I've folded the details into a bug to track this and a number of closely related reports: hypothesis/client#244.
