### ISSUE TITLE
Pre-selecting text then launching extension no longer works.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#236]
### Steps to reproduce
1. Select some text, here for instance: https://www.nytimes.com/2017/02/17/opinion/the-downfall-of-kellyanne-conway.html
2. Activate the extension
3. Click adder to annotate

### Expected behaviour
The sidebar should open and an editor should appear.

### Actual behaviour
The sidebar opens but no editor appears.  There appears to be a ghost highlight now somewhere, which cannot be deleted, but cannot be viewed either.

### Browser/system information
Chrome extension

**Comment by chdorner** [comment]
@dwhly this seems to work fine for me with the current extension. Can you confirm that it's still an issue?

```
Version: 1.11.0
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
URL: https://www.nytimes.com/2017/02/17/opinion/the-downfall-of-kellyanne-conway.html
Username: chdorner
Date: 12 Apr 2017 12:26:46 +0200
```

**Comment by dwhly** [comment]
Works fine for me too now!
