### ISSUE TITLE
Disappearing highlights

### ISSUE THREAD

**Issue by heatherstaines** [hypothesis/client#237]
I know this isn't a new issue, but I can't find the previous mention. I'm having the disappearing highlights problem on this article, but it didn't start to happen until well into the article itself: 
https://medium.com/join-scout/the-rise-of-the-weaponized-ai-propaganda-machine-86dac61668b#.44j6b8b2n

### Steps to reproduce
1. I made highlights using H on Chrome
2. about 2/3 of the way through the article, my previous highlight would disappear when I made a new one--but not all of them, just the one immediately prior.
3.

### Expected behaviour
Tell us what should happen.

Highlights should stay

### Actual behaviour
Tell us what happens instead.
Highlights disappeared

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

Chrome 56.0.2924.87
Sierra 10.12.2

### Additional details
If you have other information which might be helpful, please include it. If a
screenshot will help to illustrate the issue you are reporting, please include
one.

**Comment by dwhly** [comment]
This has been reported here: https://github.com/hypothesis/h/issues/4298
And a fix is in flight here: https://github.com/hypothesis/client/pull/234
