### ISSUE TITLE
Annotation highlight not drawn

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/client#240]
_Original bug reports here: hypothesis/h#2707, and then hypothesis/h#2934._

### Steps to reproduce.
1. Open http://perseids.org/sites/smiths/A/artemis_1.html and activate Hypothesis.
2. Look for the annotations on the first instance of the word "Apollo", i.e. in "She was the sister of Apollo, and born with him".
3. Click on the annotation.

### Expected result

All three matching annotations on the text in question, namely

```
- [`gJ4nmXQmTru7CmkK0LpN_A`](https://hypothes.is/api/annotations/gJ4nmXQmTru7CmkK0LpN_A)
- [`RpP38w5gRO-BuhmSgHVq2A`](https://hypothes.is/api/annotations/RpP38w5gRO-BuhmSgHVq2A)
- [`vdk8AxjfQ5in579QnlUvCA`](https://hypothes.is/api/annotations/vdk8AxjfQ5in579QnlUvCA)
```

should be displayed in the sidebar as the "selection".

### Actual result

`RpP38w5gRO-BuhmSgHVq2A` is missing from the sidebar selection, and doesn't appear to have a highlight drawn for it in the page, despite having apparently identical annotation metadata (URI and selectors).

If you clear the selection and scroll through the annotations on the page, however, you will find it listed alongside the other two at the appropriate point.

**Comment by lyzadanger** [comment]
@klemay Your input requested! The original link cited in the description above is a 404. Thus this bug cannot be reproduced in its original environment.

**Comment by klemay** [comment]
@lyzadanger I'm going to close this - I can't find another page from that website that doesn't give a 404.
