### ISSUE TITLE
`appBackgroundColor` config setting is not correctly applied

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#2439]
On https://elifesciences.org/articles/55164 the Hypothesis client is configured with a custom `appBackgroundColor` setting:

<img width="377" alt="Screenshot 2020-08-14 at 10 02 46" src="https://user-images.githubusercontent.com/2458/90233250-c04a5d80-de15-11ea-88f9-7e38808d558f.png">

However this is not used for the sidebar's background color as it should be. The background color is the default grey instead of white:

<img width="509" alt="Screenshot 2020-08-14 at 09 58 59" src="https://user-images.githubusercontent.com/2458/90233285-cfc9a680-de15-11ea-9885-9f29030385ce.png">

There is also an issue with the background color of the right-hand side of the "Post to" button.

**Comment by nlisgo** [comment]
@robertknight when are we likely to see this code deployed so that we can verify that it fixes the issue for us?

**Comment by robertknight** [comment]
@nlisgo - The fix was deployed on Friday. On https://elifesciences.org/articles/55164 for example you should see this:

<img width="700" alt="Screenshot 2020-08-17 at 09 22 05" src="https://user-images.githubusercontent.com/2458/90374271-2380fd80-e06b-11ea-85b4-cf3eaff515cd.png">
