### ISSUE TITLE
Can't create annotation on site

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/client#245]
_Original issue: https://github.com/hypothesis/h/issues/2644._

### Steps to reproduce
1. Visit http://www.garyhall.info/journal/2015/10/18/does-academiaedu-mean-open-access-is-becoming-irrelevant.html
2. Select text and click to create an annotation.

### Expected behaviour
The annotation editor should appear in the sidebar

### Actual behaviour
A highlight is drawn but no annotation editor appears. The following stack trace is printed to the console:

```
Uncaught (in promise) TypeError: Cannot read property '$tag' of undefined
    at t.beforeAnnotationCreated (annotation-sync.coffee:55)
    at HTMLBodyElement.<anonymous> (global.js?CE=75:1)
    at HTMLBodyElement.o (annotator.js:446)
    at HTMLBodyElement.dispatch (jquery.js:4641)
    at HTMLBodyElement.g.handle (jquery.js:4309)
    at Object.trigger (jquery.js:4550)
    at ie.fn.init.triggerHandler (jquery.js:5266)
    at e.publish (annotator.js:439)
    at guest.coffee:327
    at <anonymous>
```

### Browser/system information
Chrome 58.0.3013.3 (Official Build) dev (64-bit)

**Comment by nickstenning** [comment]
@robertknight diagnosed this as a broken `Function.bind` polyfill on the site in question:

---

The page has a broken polyfill for `Function.prototype.bind` in `http://www.garyhall.info/universal/scripts/global.js` which returns a function that ignores any arguments passed to it:

```
Function.prototype.bind = function (I, N, M, L, J, H, G, F, C, B, A) {
  var K = this;
  return function () {
    K.apply(I, [
      N,
      M,
      L,
      J,
      H,
      G,
      F,
      C,
      B,
      A
    ]);
  };
};
```

The broken polyfill causes messages between different components of the part of H which lives in the host page to get corrupted.

**Comment by nickstenning** [comment]
As mentioned in previous discussions with @robertknight, one possible solution here is to ensure that all code executed by the Hypothesis client in the hosting page is executed in a "same-origin iframe", as in [this example](https://codepen.io/nickstenning/pen/NdQaGZ?editors=1011).

**Comment by seanh** [comment]
Another site that has this issue is http://www.matthewcornell.org/blog/2015/8/31/a-simple-fabricjs-based-web-app-for-annotating-svg-files.html (see https://github.com/hypothesis/client/issues/288)

**Comment by robertknight** [comment]
Looking at the code in `src/annotator` there are only a very small number of places where we use `bind`, so as an alternative to the same-origin iframe issue mentioned above, we could target just this _specific_ issue by using a function expression instead of bind or alternatively creating a new global environment and grabbing a reference to `Function.prototype.bind` off of that.

**Comment by robertknight** [comment]
To expand on the above, you can get a "clean" version of `{Function, Object, Array}.prototype`'s methods as follows:

```js
// Create an iframe and attach it to the current document to create a fresh global environment.
// Only do this once and then re-use it in future.
// This would probably live in its own module and export useful functions (eg. bind, hasOwnProperty)
var iframe = document.createElement('iframe');
document.body.appendChild(iframe);
var bind = iframe.contentWindow.Function.prototype.bind;

// Call the browser's own version of `bind`
bind.call(functionObject, ...);
```

**Comment by robertknight** [comment]
To enforce usage of the above, you could create an ESLint rule to ban usage of potentially affected methods on objects (eg. `functionObject.bind` instead of `bind.call`) within the `src/annotator` code.

**Comment by seanh** [comment]
Confirmed that this diff fixes the problem on <http://www.matthewcornell.org/blog/2015/8/31/a-simple-fabricjs-based-web-app-for-annotating-svg-files.html>:

```diff
diff --git a/src/annotator/annotation-sync.coffee b/src/annotator/annotation-sync.coffee
index b7507a7..e3a57a7 100644
--- a/src/annotator/annotation-sync.coffee
+++ b/src/annotator/annotation-sync.coffee
@@ -21,13 +21,17 @@ module.exports = class AnnotationSync
     @_on = options.on
     @_emit = options.emit
 
+    iframe = document.createElement('iframe')
+    document.body.appendChild(iframe)
+    bind = iframe.contentWindow.Function.prototype.bind
+
     # Listen locally for interesting events
     for event, handler of @_eventListeners
-      this._on(event, handler.bind(this))
+      this._on(event, bind.call(handler, this))
 
     # Register remotely invokable methods
     for method, func of @_channelListeners
-      @bridge.on(method, func.bind(this))
+      @bridge.on(method, bind.call(func, this))
 
   sync: (annotations) ->
     annotations = (this._format a for a in annotations)
```

@robertknight I think we can follow this approach, of getting a clean version of `<whatever>` from an iframe and using that, to patch up specific bugs in the short-term. But in the medium term, if there a broader change that we can make to eliminate this entire category of bugs? In particular, I'm wondering whether it would be possible for all, or at least almost all, of our `src/annotator` code to be _running in its own iframe_ all the time anyway?

**Comment by robertknight** [comment]
@seanh - We have different "generic" solutions available depending on the delivery mechanism:

1. In browser extensions, there is support for running content scripts in an [isolated world](https://developer.chrome.com/extensions/content_scripts#execution-environment), which avoids the problem entirely.
2. For the embed, I assume we don't have to worry about this too much on the basis that the publisher will notice if Hypothesis doesn't work on their pages.
3. For Via, we get to run JS code before any of the host page's code runs, so we could potentially block monkey-patching of certain pieces of the environment
4. Lastly, there is the same-origin iframe approach. The main potential complexity is finding all the places in the annotator code which expect the document in which the annotated content or the client's UI lives to be accessible as `document` and finding a way to inject references to a different document instead (the same-origin iframe's parent).

Feel free to spike (4), but I think there is value in the more specific hack^h^hfix above.
