### ISSUE TITLE
Scroll-to-annotation broken in Firefox

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/client#246]
_Originally reported as https://github.com/hypothesis/h/issues/3270 by @robertknight._

### Steps to reproduce
1. Visit http://www.justinobeirne.com/what-happened-to-google-maps
2. Scroll down and make an annotation
3. Hit "Post to Public" (or wherever)
4. Click on annotation card in sidebar

### Expected behaviour
At steps 3 and/or 4, the browser should scroll the document pane to centre the annotation.

### Actual behaviour
The browser scrolls to the very top of the page.

### Browser/system information
Originally reported as an issue with Firefox v49 and v46 on Linux. Verified as an issue with Firefox 51.0.1 (64-bit) on Mac OS X 10.12.3.

### Additional details
The issue does not repro in Chrome 50 or 58.0.3013.3 (Official Build) dev (64-bit).

**Comment by saurabhnanda** [comment]
Can confirm this bug and it can been verified on https://www.vacationlabs.com/haskell/basic-types-and-functions.html

**Comment by robertknight** [comment]
I cannot reproduce with Firefox v65 (current stable) on macOS.
