### ISSUE TITLE
Remove search input from top bar

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#2475]
Some UX research has been done and we're moving forward with removing the search input interface from the top bar and, in the current plan, putting it at the same horizontal level as the "tabs." Detailed UX notes [can be found here](https://docs.google.com/document/d/1JADFft0YEsHHXTaLPKn3lccz22Yquf-cWzcGWzwTwHk/edit) (requires Hypothesis Google team access). At time of writing, we are pursuing option 2.

Part of #2160 

## Wireframes

Search input, when inactive, will use available space to the right of sidebar tabs:

<img src="https://user-images.githubusercontent.com/439947/91178215-d4624a80-e6b2-11ea-9fec-fa920658ae74.png" width="400" />

or

<img src="https://user-images.githubusercontent.com/439947/91178326-fb208100-e6b2-11ea-8627-6700a763d980.png" width="400" />

When focused or otherwise active, the search input will expand "over the top" of the tabs (note that tabs are not relevant when search filters are applied, so this makes general sense):

<img src="https://user-images.githubusercontent.com/439947/91178446-21deb780-e6b3-11ea-8957-c246b233b9d9.png" width="400" />

And with a submitted search query:

<img src="https://user-images.githubusercontent.com/439947/91178518-39b63b80-e6b3-11ea-8583-7e17019f1bc3.png" width="400" />

-----

There are some UX nuances to solve as we work through this, but that's the high-level approach we're eyeing for now.

**Comment by robertknight** [comment]
Fixed as part of https://github.com/hypothesis/client/issues/6006.
