### ISSUE TITLE
Code refactor - xpath-util

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#2479]
This is a follow-up from https://github.com/hypothesis/client/issues/2340

1. [x] Move `findChild` from xpath-util to range-js as a private helper function and don't unit test it directly to avoid setting implementation details in tests that may need to be converted for future refactors.
2. [x] in xpath-util, replace `flatten` with Array.prototype.flat  and set up a polyfill for older browsers. 
3. [x] Eventually pull out jquery entirely from this file.
4. [x] xpath and xpath-utils can now be merged into a single module.

**Comment by robertknight** [comment]
Items 1-3 in the above list have been done. Regarding item 4, `xpath.js` and `xpath-util.js` are still separate modules. There is an `xpathFromNode` function in `xpath-util.js` which should be moved to `xpath.js`. There are also utility functions related to finding text nodes which are used in range normalization as well as XPath-related code in `range.js`. Those don't really belong in `xpath.js`. They are only used within `range.js` but we probably do want to keep them in a utility module for ease of testing separately.

**Comment by robertknight** [comment]
Item 4 on the list above is covered by https://github.com/hypothesis/client/pull/2831, which depends on the changes in https://github.com/hypothesis/client/pull/2830.

**Comment by robertknight** [comment]
Closing this as the PRs mentioned in the previous comment have now been merged.
