### ISSUE TITLE
Sidebar cards don't scroll on Safari

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/client#250]
_Originally reported as https://github.com/hypothesis/h/issues/3268 by @dwhly._

### Steps to reproduce
1. On iOS (9.3.1) Safari
2. Load via.hypothes.is/example.com
3. Open the sidebar
4. Try to scroll the cards with your finger
### Expected behaviour

The cards should scroll up so that you can see ones further down.
### Actual behaviour

The background page (example.com) scrolls up and down instead, but the cards stay fixed in the sidebar.
### Browser/system information

Current Safari, iOS 9.3.1
### Additional details

Screencast: https://www.youtube.com/watch?v=xEvTE3n9Vcw

**Comment by sean-roberts** [comment]
This is a pretty common problem with fixed overlays and mobile. The quick pragmatic solution is to:

- Add a container element around the iframe
- Set the following CSS properties for the element:

```
  height: 100%;
  overflow: scroll;
  -webkit-overflow-scrolling: touch;
```

I experimented locally and this is the least painful way to get the scrolling behavior running
