### ISSUE TITLE
Bug: Resizing can cause anchored annotations to disappear in PDFs

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#2502]
I believe that this issue is pre-existing, but is considerably exacerbated when in the new side-by-side mode.

To reproduce (I'm in Chrome, FWIW):

1. Load up a PDF in side-by-side mode (hint: you can do this on Via3 currently. Hit me up if you need instructions). See that the PDF has some annotations visible.
2. Ensure PDF zoom is set to "Automatic" (At least for Chrome)
3. Resize the browser window some
4. Notice that highlights/anchored annotations disappear from the PDF document

*Edited: This bug is orthogonal to side-by-side mode. Resizing a PDF with PDF.js and the client in any mode will cause this error eventually. It happens more frequently in side by side mode because more resizing is happening. I've updated the issue title to reflect this.*

**Comment by lyzadanger** [comment]
Ah! I think this might be a manifestation of the pre-existing bug that happens when you do a fair amount of resizing. It causes an error:

![image](https://user-images.githubusercontent.com/439947/92030860-a70e4000-ed35-11ea-8506-3661252526f1.png)

It looks like, from brief manual futzing, annotations disappear after this error happens.

**Comment by judell** [comment]
I think I've seen it before, it would be great if this exercise flushes it out.

**Comment by lyzadanger** [comment]
It looks like there is some...less-than-robust code in `range.coffee` that assumes the presence and node-i-ness of references that could be `null` or `undefined`. That section of annotator code is currently under refactor and migration to JavaScript. Hope to heck we can get to the bottom of this...

**Comment by judell** [comment]
I'm rooting for you from the sidelines :-)

**Comment by dwhly** [comment]
Pre-existing as you say.  I'd file it and maybe even prioritize it but ship side-by-side regardless.
