### ISSUE TITLE
Touching highlights doesn't open matching annotations in sidebar 

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/client#251]
_Originally reported as https://github.com/hypothesis/h/issues/3397 by me._

### Steps to reproduce
1. Visit an annotated page in Mobile Safari on iOS
2. Tap on a highlight
### Expected behaviour

The sidebar should pop up and show the matching annotation card.
### Actual behaviour

Nothing.
### Browser/system information

Mobile Safari, iOS 9.2?.

_This issue was split out from #2811._

**Comment by sean-roberts** [comment]
This is the old cursor optimization issue with mobile. Mobile OSs don't register any of the click events unless the element has `cursor: 'pointer'` specified in CSS. Anchors and buttons natively have this but everything else does not.

To fix this issue we need to add `cursor: pointer` to the `.annotator-hl` ruleset in inject.scss

**Comment by judell** [comment]
Thanks!
