### ISSUE TITLE
Make bucket bar/toolbar opaque

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#2526]
It's long been lamented that the bucket bar is partially transparent and shows content from the document through it. It looks a little shabby:

![image](https://user-images.githubusercontent.com/439947/92933229-0219f400-f414-11ea-8d45-5783363a92ef.png)

Let's make the bar full opacity.

**Comment by lyzadanger** [comment]
Note: the transparency needs to be retained when the sidebar is closed.

**Comment by robertknight** [comment]
> Note: the transparency needs to be retained when the sidebar is closed.

To expand on this, the transparency means that when the sidebar is closed, all of the content of the page is visible up until the right edge. I expect this will be important for some sites that have minimal margins between the edge of the content and the edge of the window.

**Comment by esanzgar** [comment]
This issue was solved by this PR: https://github.com/hypothesis/client/pull/2544
