### ISSUE TITLE
Make annotation-quote highlighting work when focused (hovered) in main document

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#2527]
Right now if you hover over an annotation card, the blockquote (quote) left-border turns blue and the corresponding annotation is highlighted in the main document:

![image](https://user-images.githubusercontent.com/439947/92934351-625d6580-f415-11ea-98d8-91295af32e81.png)

But the inverse is not the case: if you hover over the highlighted text in the main document, the annotation card does not visibly change state:

![image](https://user-images.githubusercontent.com/439947/92934465-81f48e00-f415-11ea-9e08-811566ec9f97.png)

This is because the `.is-focused` class is not applied correctly in `AnnotationQuote`.

Make the `is-focused` state work. We can discuss stronger visual emphasis as a follow-on (the current focus affordance is pretty subtle).

**Comment by esanzgar** [comment]
One easy fix would be to change this line: 
https://github.com/hypothesis/client/blob/06fe03c435123a5b1ceb574fc4bc46a913f4172a/src/styles/sidebar/components/annotation.scss#L7

to be `.thread-list__card .is-focused .annotation-quote__quote`

That would resolved the issue.

However, I have two comments:

* There is a comment above the this rule that indicates that the style should be moved to another component. I can try to do that.

* In addition to this fix, I suggest to change the colour of the highlighted text if the the user is hovering in the card. That way the visual representation is symmetrical (either by hovering on the highlighted text or the card)

Please, let me know if you want me to tackle both of these comments.

**Comment by esanzgar** [comment]
I will add a new issue about point number #2: 

> In addition to this fix, I suggest to change the colour of the highlighted text if the the user is hovering in the card. That way the visual representation is symmetrical (either by hovering on the highlighted text or the card)
