### ISSUE TITLE
Scrolling in PDF is interrupted by scroll to selected annotation

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/client#253]
_Originally reported as https://github.com/hypothesis/h/issues/3537 by @dwhly._

### Steps to reproduce
1. With the extension, browse here: http://www.hewlett.org/wp-content/uploads/2016/11/Open_Educational_Resources_December_2015.pdf#annotations:nZkR7DlyEeaH6sfmQWfRVA
2. Scroll down about twenty pages, or to approximately page 6 in the main document (after the exec summary).
### Expected behaviour

The document should continue to scroll
### Actual behaviour

It snaps back to the selected annotation
### Browser/system information

Chrome extension

cc @jeremydean

**Comment by robertknight** [comment]
The annotation in question is this one: https://hypothes.is/a/nZkR7DlyEeaH6sfmQWfRVA.

I'm no longer able to reproduce this.
