### ISSUE TITLE
Annotation body reverts to old version temporarily when saving changes

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#2538]
### Steps to reproduce

1. Create a new annotation with the body text "old version" and save it
2. Click the "Edit" button, change the body text to "new version" and click the button to save changes

### Expected behaviour

After step 2, the annotation body should briefly display the text "new version" along with the message "Saving..." where the annotation action buttons normally appear. Once the changes are saved, the annotation body should read "new version" and the annotation action buttons should re-appear.

### Actual behaviour

After step 2, the annotation body briefly reverts to "old version" while the changes are being saved, and then switches to "new version" once the save is committed.

The issue is easier to see on QA / prod at busy times compared to localhost because saving takes longer. If the user was on a slow connection or the service was slow for some reason, this issue could cause the user to briefly think that their changes had been lost.

**Comment by esanzgar** [comment]
Resolved by https://github.com/hypothesis/client/pull/2562
