### ISSUE TITLE
remembered tags are doubled

### ISSUE THREAD

**Issue by judell** [hypothesis/client#2547]
When the tag list in localStorage is like this:

["RRIDCUR:Validated","va","RRID:Addgene_12259","RRID:CVCL_2426","RRIDCUR:Unrecognized","PMID:32894207","PMID:32905778","PMID:32915137","PMID:32935086","RRID:AB_621848","RRIDCUR:Missing"]

The remembered tag list in the client is like this:

![image](https://user-images.githubusercontent.com/46509/93620908-9db8e080-f98f-11ea-8ee4-512bc31a51c8.png)

**Comment by lyzadanger** [comment]
I've opened a PR with a fix—good catch, this is a bug with string casing.

On my local/fix branch now:

![image](https://user-images.githubusercontent.com/439947/93671142-7edd4b80-fa6e-11ea-8a9a-f875e7f29b95.png)
