### ISSUE TITLE
Inappropriate UI scaling on hi-DPI mobile devices

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/client#255]
_Originally reported as https://github.com/hypothesis/h/issues/2211 by @dwhly._

### Steps to reproduce
1. Open any webpage through Via using a hi-DPI device such as a Nexus 6P.

alternatively, and perhaps more easily

1. Open any webpage in Chrome on the desktop, and activate Hypothesis.
2. Open developer tools and activate the device toolbar: ![screen shot 2017-02-22 at 11 11 42](https://cloud.githubusercontent.com/assets/3602/23206920/b8c97a6e-f8ef-11e6-9310-2c007841b935.png)
3. Select a hi-DPI device such as a Nexus 6P: ![screen shot 2017-02-22 at 11 12 51 1](https://cloud.githubusercontent.com/assets/3602/23206966/e4fb43ba-f8ef-11e6-9080-7bfe1511c0c2.png)

### Expected behaviour
Hypothesis sidebar controls should present reasonable visual size and reasonable tap targets.

### Actual behaviour
Controls are teeny-tiny!

### Browser/system information
Chrome on Nexus 6/Android.

#### Nexus 6 (2015-05)
![screenshot_2015-05-03-06-53-59](https://cloud.githubusercontent.com/assets/1413074/7445332/a31d0dac-f162-11e4-81b7-8884e67a1406.png)

#### Nexus 5 (2016-07)
![screenshot_20160722-164015](https://cloud.githubusercontent.com/assets/112063/17060658/56484c2a-502b-11e6-834d-d0d426e39376.png)

#### Simulated Nexus 6p (2017-02)
![screen shot 2017-02-22 at 11 12 31](https://cloud.githubusercontent.com/assets/3602/23207003/ffe0d604-f8ef-11e6-9ae3-04bf4e92acf4.png)

**Comment by klemay** [comment]
This was reported by a user today (from the annotation inquiry form on our website).

**Comment by robertknight** [comment]
I'm not sure whether the original issue was down to us or Chrome, but nevertheless it was resolved at some point:

<img width="776" alt="Sidebar controls Nexus 6 emulation" src="https://github.com/hypothesis/client/assets/2458/680d523e-a974-4470-94ee-05817e9914cb">
