### ISSUE TITLE
Tag autocomplete function adds an extra tag sometimes

### ISSUE THREAD

**Issue by OllieJones** [hypothesis/client#2550]
### Steps to reproduce
1. Use an account that has already used some tags; we want them to appear in the autocomplete menu.
1. Start to annotate some text in some web page.
2. Type annotation text
3. Click in or tab to the Add New Tags field.
4. Type a letter or two, enough to show the autocomplete dropdown menu. For example, for the tag `journal ` type `jo`.
5, Click on the completed tag in the autocomplete dropdown menu.
6. Click on the POST button.
 

### Expected behaviour
Should get an annotation record with only the tag chosen from autocomplete.  In my example, it should be `journal`.

### Actual behaviour
Actually get two tags. In my example they are `journal` and `jo`. The second, unwanted, tag comes from the letters I typed into the Add New Tags text box to activate the autocomplete.
 
### Browser/system information
* Google Chrome Version 85.0.4183.102 
* Windows 10 18363.1082.

**Comment by lyzadanger** [comment]
@OllieJones Thank you for reporting this!
