### ISSUE TITLE
Adder doesn't always appear above page content

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/client#256]
_Originally reported as https://github.com/hypothesis/h/issues/2869 by @judell._

### Steps to reproduce
1. Go to https://codepen.io/nickstenning/pen/KWPNaK?editors=1100
2. Try to make an annotation on the page text (Hypothesis is already embedded).

### Expected behaviour
The adder should appear above the content.

### Actual behaviour
The adder is hidden, because the page content has too high a z-index.

**Comment by nickstenning** [comment]
@robertknight on the original issue:

> Note for future reference. Rather than hardcoding zIndex to a fixed value, we could potentially just make sure we select one that is higher than the max index within the frame being annotated.
> 
> ``` js
> elementZIndex = zindex => Number(zindex) || 0;
> maxZIndex = () => [].slice.apply(document.querySelectorAll('*'))
> .reduce((max, el) => Math.max(max, elementZIndex(getComputedStyle(el).zIndex)), 0);
> ```

**Comment by nickstenning** [comment]
@nickstenning on the original issue:

> Like this, you mean? https://github.com/openannotation/annotator/blob/258fd8822de6fca73b4f7ab4717d14556367d1ab/src/util.coffee#L154 :wink: 
>
> I suspect that's not used because we have our own custom adder, but it's worth looking at.
>
> The only thing I'd caution is that if there's a way to do this that doesn't involve a loop over every element in the document, that would be good. On large documents iterating over `document.querySelectorAll('*')` is going to take a non-negligible amount of time.

**Comment by nickstenning** [comment]
@robertknight on the original issue: 
> It takes about 800-1000ms for this on the famously large [HTML5 single-page spec](http://www.w3.org/html/wg/drafts/html/master/single-page.html):
> 
> ``` js
> (d = Date.now(), [].slice.apply(document.querySelectorAll('*')).map(el =>
> getComputedStyle(el).zIndex), Date.now() - d)
> ```
> 
> And on what I would consider a more typical large article such as [this eLife paper](http://elifesciences.org/content/4/e08924), about 200ms.
> 
> So yes, that is expensive enough to create noticeable lag on large articles.
> 
> Given that we know where the adder is going to appear, we could search a much smaller list of elements though.
>

**Comment by nickstenning** [comment]
@nickstenning on the original issue:

> > Given that we know where the adder is going to appear, we could search a much smaller list of elements though.
> 
> Good idea. Sampling `document.elementFromPoint(x, y)` in a few places around where we want to pop up the adder and then checking those elements would probably work! (It's non-standard but IIRC it works in every major browser).
>

**Comment by nickstenning** [comment]
@sean-roberts on the original issue:

> This was something I was going to bring up after researching the client more - glad to see this ticket is here. Seems to me we can get _very_ far with setting the z-index value to the highest limit that has no known problems in older browsers (2147483647) and call it a day. If we have to get smarter than that, we can reopen this or create a new ticket saying it's not good enough.

**Comment by nickstenning** [comment]
@robertknight on the original issue: 

> > Seems to me we can get very far with setting the z-index value to the highest limit that has
> > no known problems in older browsers (2147483647) and call it a day. 
> 
> That's a lot simpler than the other options - worth a try 👍 
> Found this as a reference: http://www.puidokas.com/max-z-index/

**Comment by nickstenning** [comment]
Note that the "arms race" approach to fixing this -- just picking `ZINDEX_MAX` and using that -- may not be the right solution here in light of #242.

**Comment by esanzgar** [comment]
Closed by [this PR](https://github.com/hypothesis/client/pull/2585)
