### ISSUE TITLE
Incorrect display of dropdown menu in IE 10/11

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/client#257]
_Originally reported as https://github.com/hypothesis/h/issues/2659 by @robertknight._

Tested under IE 10 on Win 7 and IE 11 on Win 10:

![ie11-vert-menu-alignment](https://cloud.githubusercontent.com/assets/2458/10669033/ce4f36de-78d6-11e5-8064-97c503957d62.png)

![ie11-vert-menu-alignment-2](https://cloud.githubusercontent.com/assets/2458/10669107/11e4bc5c-78d7-11e5-9fb2-27eda486f675.png)

**Comment by robertknight** [comment]
IE 11 now accounts for only 1% of our overall usage and IE < 11 virtually zero. We're most likely not going to fix this.
