### ISSUE TITLE
When viewport shrinks, transition from side-by-side to overlap more gracefully

### ISSUE THREAD

**Issue by klemay** [hypothesis/client#2682]
This is a suggested improvement to the PDF side-by-side experience.

**Current behavior**
As you shrink the browser window, when the viewport becomes too narrow to support both the sidebar and the PDF, the PDF starts to shrink-- until a certain point, after which the sidebar snaps to completely overlap the PDF, and the underlying PDF expands again to fill that additional space. Keep narrowing still and then eventually the PDF begins to shrink again.  So--the PDF shrinks in two steps, in kind of “sawtooth” fashion. 

I'm not able to embed the GIF @dwhly created to show what this looks like, as it exceeds the file limit of 10MB. [Here's a link to the GIF in Slack](https://hypothes-is.slack.com/archives/C07NXBDNW/p1602277113066700). 

**Desired Behavior**
As the viewport narrows, sidebar goes from being side-by-side to partially overlapping and then completely overlapping without *ever* shrinking the PDF, *until* the PDF itself must shrink because the browser is simply too narrow.

**Comment by robertknight** [comment]
I'm tempted to close this merely for the sin of reporting an issue with a 103 MB GIF.

In all seriousness though, there is a misunderstanding in the issue over what is happening. There is a constraint here that we have a compromise between keeping the sidebar and PDF visible at the same time, which is convenient when annotating, vs ensuring that the PDF text is large enough to be readable. When side-by-side mode is activated automatically _the content has already been shrunk_, unless you have a wide monitor (eg. something much larger than my 13" MacBook). For this reason, it is inevitable that the PDF will "snap" to being wider once the viewport becomes small enough that we decide we can't support showing the PDF and sidebar at the same time.
