### ISSUE TITLE
Sidebar buttons are misaligned on mobile devices

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#2683]
Something changed recently that caused the sidebar controls to be misaligned on mobile devices (perhaps where `@media (pointer: coarse)` is true?):

<img width="400" alt="Misaligned buttons" src="https://user-images.githubusercontent.com/2458/97472144-68fe5880-1941-11eb-8f1a-6200317267ec.jpeg">

In the above image, the toggle button at the top of the sidebar should be aligned with the navigation bar at the top of the sidebar.

Tested on an iPhone running iOS 14.1.

**Comment by lyzadanger** [comment]
@esanzgar I believe this is fixed. Can you close if so?
