### ISSUE TITLE
Following bouncer links to orphaned annotations is broken

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#2686]
![Screenshot from 2020-10-28 15-40-24](https://user-images.githubusercontent.com/22498/97556291-2c7a3d80-19d1-11eb-82b3-95ee21ad4b6d.png)

Example: https://hyp.is/8VgUcHvgTvuTR1eQizPISg/www.thelegalproject.nl/

1. Click on a bouncer link to an orphaned annotation
2. Expected result: The client should open and show the annotation somehow  
   Actual result: The client says "Showing 1 annotation" and "Show all (0)" but doesn't show the annotation. If you click <kbd>Show all</kbd> the annotation can be found under the _Orphans_ tab

**Comment by lyzadanger** [comment]
Confirmed that this specific example is resolved by the fix: 

![image](https://user-images.githubusercontent.com/439947/101170287-3fa1ae00-360c-11eb-9217-e2efeff5ba73.png)
