### ISSUE TITLE
Implement responsive layout for Notebook view

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#2730]
The Notebook will have access to more screen real estate than the sidebar, and may well end up with two or even three columns when space allows. Wireframe out and SASS up a responsive, mobile-first layout that will work comfortably on our targeted browsers and devices.

**Comment by esanzgar** [comment]
I have tested the responsive design of the notebook in 2 different contexts: (1) inside the `<hypothesis-notebook>` and (2) standalone. These are some notes:

## Inside `<hypothesis-notebook`

- when `@media screen and (min-width: 15em)` the close button overlaps with the annotation cards when scrolling down:
![image](https://user-images.githubusercontent.com/8555781/108515566-8165fa80-72c5-11eb-8f4e-188bad00e163.png)

- when `@media (pointer: coarse)` it is possible to scroll the host page, as described [here](https://github.com/hypothesis/client/pull/3024#pullrequestreview-592240569).

- when `@media only screen and (min-width: 769px)` the group selector changes positions and shifts the annotation cards to the left: 
![image](https://user-images.githubusercontent.com/8555781/108519012-862cad80-72c9-11eb-869f-e8674d78b89e.png)


## Standalone

- when `@media (min-width: 450px)` the group selector shifts positions. Notice that the `min-width` media query is different from the section above:
![image](https://user-images.githubusercontent.com/8555781/108520276-c80a2380-72ca-11eb-85c4-21550707d404.png)

- when `@media (min-width: 450px)` and clicking on `reply` or `edit` the markup editor overflows the width of the viewport: 
![image](https://user-images.githubusercontent.com/8555781/108521215-c9881b80-72cb-11eb-8bb3-3ae99b595339.png)

**Comment by lyzadanger** [comment]
@esanzgar Note that the user-filter wonkiness is already tracked: https://github.com/hypothesis/client/issues/2922

**Comment by esanzgar** [comment]
@lyzadanger has asked me to take a look at what kind of content overflows on narrow viewports:

1. `MarkdownEditor` and `.annotation__form-actions`:
![image](https://user-images.githubusercontent.com/8555781/108845838-32c6a200-75de-11eb-90b5-edc2c165a2ef.png)

**Comment by lyzadanger** [comment]
@esanzgar Thanks for identifying these. I think the first two overflow examples above (markdown editor and non-breaking word) are ones we should go ahead and track down as part of this work. The third example—nested replies—is very real, but complex enough that I think we need to put it aside for this particular objective.

**Comment by lyzadanger** [comment]
This issue was somewhat poorly framed by me initially: responsive design is an ongoing task that will continue to need iteration, especially as we move into developing more features. However, I believe the spirit of the original issue has been satisfied, and am going to close this issue.
