### ISSUE TITLE
Rename onLogin to onLoginRequest

### ISSUE THREAD

**Issue by sean-roberts** [hypothesis/client#274]
@nickstenning brought up the point that `onLogin` doesn't accurately reflect what is actually happening and suggested we go with `onLoginRequest`. This ticket will update the client code, docs, and client demo site to use this new api naming.

cc: @robertknight @seanh @sheetaluk

**Comment by robertknight** [comment]
Fine with me. This reminds me that we need to implement integration with the 'Sign up' button as well and that should follow the same naming convention.

**Comment by nickstenning** [comment]
Isn't that just a link?

**Comment by robertknight** [comment]
Maybe - we haven't talked about it in any detail yet. My initial assumption is that we would give publishers similar flexibility to the login callback.

**Comment by seanh** [comment]
:+1:
