### ISSUE TITLE
Upper bucket is hidden underneath button on mobile

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/client#2747]
### Steps to reproduce
1. On medium-size screens, add an annotation to the top of the page

### Expected behaviour
A bucket bar should appear near the `bucket-bar` near the `annotator-toolbar`

### Actual behaviour
Buttons from the `annotator-bar` hides the bucket count.

### Browser/system information
Chrome and Safari

### Additional details
Transitioning from very small-size screen to a medium-size screen hides the bucket underneath the button:

![Nov-20-2020 10-39-25](https://user-images.githubusercontent.com/8555781/99785930-25e96c80-2b1e-11eb-88fa-ddf4d4215a36.gif)

On middle-size screens, removing one button in the `annotator-toolbar` reveals the hidden bucket:

![Nov-20-2020 10-41-54](https://user-images.githubusercontent.com/8555781/99785923-22ee7c00-2b1e-11eb-91e1-ae1cbe928242.gif)

**Comment by robertknight** [comment]
I can't reproduce any more. It looks like at the time the screenshot was taken, something was causing the toolbar buttons in the sidebar to be larger than normal, maybe on touch devices.

I do note that `src/annotator/sidebar.tsx` does still have a hardcoded padding value in it via a `pt-[110px]` Tailwind class.
