### ISSUE TITLE
Icons not visible on some websites

### ISSUE THREAD

**Issue by motiko** [hypothesis/client#2768]
To reproduce open the extension in [stackoverflow.com](stackoverflow.com) you will see empty blue buttons on the side.
<img width="406" alt="image" src="https://user-images.githubusercontent.com/875618/88369227-da050180-cd8f-11ea-835a-0dd5b5cb0ebd.png">
Same in incognito page with other extensions disabled
<img width="365" alt="image" src="https://user-images.githubusercontent.com/875618/88369680-d4f48200-cd90-11ea-9e91-2ec2bbe5b426.png">

**Comment by esanzgar** [comment]
I can confirm this issue.
This is likely is an interaction between the host CSS and the client's CSS. 
This could be solved by using shadow DOM.
