### ISSUE TITLE
Share panel generates invalid hyp.is / bouncer links for local PDF files

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#2786]
### Steps to reproduce
1. Open a local PDF file in Chrome
2. Activate the Hypothesis browser extension
3. Click on the "Share" icon in the top navigation bar

### Expected behaviour

The link shown in the panel should only reference HTTP URIs which bouncer can actually send the user to, or URIs in some other scheme which bouncer could resolve to an HTTP URI.

If no HTTP URL is available then the dialog should either show some suitable explanation or fall back to generating an activity page link to the group's activity page.

### Actual behaviour

A hyp.is link is generated which tries to direct the user to a URI which is the PDF fingerprint. For example: https://hyp.is/go?url=urn%3Ax-pdf%3A102c7f4b4df6b006687f35b60cf013ab&group=abcdef

<img width="483" alt="Share link for local PDF file" src="https://user-images.githubusercontent.com/2458/101149796-54377380-3617-11eb-997a-a9592b3b77ba.png">

**Comment by lyzadanger** [comment]
I want to capture that this same UX problem exists with the share-a-single-annotation component: 

![image](https://user-images.githubusercontent.com/439947/102515587-edc14500-405b-11eb-9965-e20386a3f126.png)

That link is useless if it's for a local document.

**Comment by lyzadanger** [comment]
Design discussion Slack thread (requires Hypothesis team access): https://hypothes-is.slack.com/archives/C07NXBDNW/p1608223971151900
