### ISSUE TITLE
Ensure that Notebook functions within the LMS context

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#2801]
Make sure the Notebook works tolerably well in LMS contexts. This may or may not require some work in the LMS app as well.

Leaving this purposefully vague at this point, but it can be fleshed out if we need to, or by the implementer.

**Comment by robertknight** [comment]
The current status is that there is a way for H staff to test the notebook app in the LMS:

1. You have to enable the feature flag for the specific LMS user that you want to test with. Doing this requires getting the auto-generated username from the client's Help panel and ensuring that the `notebook_launch` feature flag is active for them in https://hypothes.is/admin/features. The easiest way to do this is to add the user to the "LMS Test Accounts" feature cohort
2. After launching an assignment, you need to use the "Open notebook" command from the client's user menu within 5 minutes. This time limit comes from the duration that the grant token provisioned by the LMS is valid for.

Obviously we need to resolve issue (2) before we can expose the Notebook to a wider group of users.

**Comment by robertknight** [comment]
The notebook is now working in the LMS context. The only new work that was required was [refreshing the grant token](https://github.com/hypothesis/lms/commit/5b88f055e80e4b511f7abd99c3ddd4d9f735550c) if it had expired.
