### ISSUE TITLE
On small screens the client makes some websites horizontally scrollable

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/client#2811]
### Steps to reproduce
1. On a small window (mobile devices included), , go to https://via.hypothes.is/https://example.com
2. The `annotator-bar` appears on the right margin and then shortly it disappears
3. The client makes the page to not fit in the screen and and is now scrollable horizontally 
4. The `annotation-bar` can be found by scrolling to the right side of the screen 

![Dec-10-2020 14-13-20](https://user-images.githubusercontent.com/8555781/101777580-f614ff80-3af2-11eb-98a2-bf683b3f4dc2.gif)

### Expected behaviour
example.com has a responsive layout and it fits any screen size without scrolling

### Actual behaviour
Addition of the client to example.com makes the document scrollable.

### Browser/system information
I have tested this behaviour on Android/Chrome, iOS/Chrome, iOS/Safari and Mac/Chrome (making the window small or by activating the chrome devtools/device toolbar)

**Comment by robertknight** [comment]
> I have tested this behaviour on Android/Chrome, iOS/Chrome, iOS/Safari and Mac/Chrome (making the window small or by activating the chrome devtools/device toolbar)

I was not able to reproduce this in Chrome/Safari using a real iOS device (my iPhone X). I was able to reproduce using the responsive design mode in Chrome devtools when configured to emulate an iPhone X however. I put my Android device on charge to see if I can reproduce there.

**Comment by robertknight** [comment]
I was able to reproduce this on my Moto G4 Android device running Chrome 86.
