### ISSUE TITLE
annotateit.org scripts referenced from client

### ISSUE THREAD

**Issue by sean-roberts** [hypothesis/client#284]
Browsing around with IE11 I see that we get a browser error thrown for "HTTPS security is compromised by http://assets.annotateit.org/vendor/xpath.min.js" The problem really is that it is http on a https served page. But to reduce our surface area, I think we need to pull in these resources under cdn.hypothes.is 

In a search, I found these three as cross-domain resources from annotateit.org

http://assets.annotateit.org/vendor/xpath.min.js
http://assets.annotateit.org/vendor/json2.min.js
http://assets.annotateit.org/vendor/ierange.min.js

**Comment by robertknight** [comment]
The references to annotateit.org were apparently part of the vendored copy of Annotator.js, and were removed from the source tree when that vendored script was removed in a5a8fdc09dff91192d0140b00820c15d44c9296c
