### ISSUE TITLE
allow copy all highlight note 

### ISSUE THREAD

**Issue by Jackiexiao** [hypothesis/client#2862]
I would like `copy all` highlight note feature in hypothesis, it would be useful while note taking and copy to other app

**Comment by esanzgar** [comment]
Thanks @Jackiexiao, it is an interesting suggestion.

I don't know if any some sort of export functionality is in the pipeline.

**Comment by lyzadanger** [comment]
@katelyn should have some context about the export feature!

**Comment by judell** [comment]
Meanwhile, this will help: https://jonudell.info/h/facet/

**Comment by lyzadanger** [comment]
@klemay Might I request some product input here?

**Comment by klemay** [comment]
Yes, as part of bringing additional function to our LMS app, we have plans to add an export feature. @Jackiexiao, I am going to close this issue in favor of an existing one that we have open for annotation export: https://github.com/hypothesis/product-backlog/issues/566
