### ISSUE TITLE
Notebook opening on the wrong group (always Public) in the Extension

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#2866]
This issue may belong in the `browser-extension` repo—I haven't debugged it at all yet.

Right now, if you open the Notebook _from the extension_, it will always open the Public group. This isn't useful because the Public group has too many annotations to show in the Notebook's current implementation. The Notebook doesn't seem to be picking up and/or applying the group currently focused in the sidebar.

The currently-focused group _does_ get correctly applied when opening the Notebook from an embedded client.

**Comment by robertknight** [comment]
In my testing I found that this was a side effect of https://github.com/hypothesis/client/pull/2886 and that fixing that issue also resolved this one.
