### ISSUE TITLE
Improve focus ring styling and/or consistency 

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#2870]
The focus ring has some issues and they extend beyond the client repo.

See slack thread
https://hypothes-is.slack.com/archives/C07NXBDNW/p1608060744150100

Doc to outline issue and some proposals
https://docs.google.com/document/d/1iO4uIxp7ECXZnZjnsXQqyxikQKxdtTuZrsbeRNcFba0/edit

I think as a group we are leaning toward #2.

We need to decide what to do (if anything) and then how to do it. It should also be extended across repositories likey using the new frontend shared package (TBD)

**Comment by esanzgar** [comment]
This was my proposal:
https://docs.google.com/document/d/1h-2Xg1pjkmV64k65LMCnH6T00bbORU4TBq-d1SCO7yI
