### ISSUE TITLE
Markdown editor component performance woes when replying to annotation with many replies

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#2897]
When replying to an annotation that has a lot of other replies, the markdown editor component feels balky (in Chrome 87, MacOS).  In this video, I start typing immediately once focusing the markdown editor input, but it takes many seconds for the text to show up:

![markdown-editor-performance](https://user-images.githubusercontent.com/439947/104936627-c6bba300-597a-11eb-8346-99fe7d6903f4.gif)

I haven't dug into this, but a few observations:

* The performance degradation appears to be a function of number of replies in a single thread, not number of top-level annotations.
* While 155 replies to a thread (as in this example) is a lot, I don't think it's out of the realm of possibilities these days.
* This performance lag also manifests in the Notebook view under the same circumstances (lots of replies).

**Comment by robertknight** [comment]
Hi Lyza - Do you have a script to replicate the annotation data used in your test? The Preact devtools extension has a profiler which may be useful here for debugging. One issue I know about is that thread virtualization only applies to top-level threads. If a single thread has hundreds of replies then the client will render all of them, even if they are off-screen.

**Comment by lyzadanger** [comment]
@robertknight I built a POST request in Postman and then used its "Batch" feature to execute that POST 200 times.

I believe I manually created the reply first, then grabbed the request payload generated by the client and put it into the Postman request body. Then I added an Auth header.

Is this enough guidance to get you started? I can be more detailed if you need.

**Comment by robertknight** [comment]
Fixed by https://github.com/hypothesis/client/pull/2898. There is still a related issue that toggling the visibility of a large list of hundreds replies via the "Show/Hide replies" button on the bottom of an annotation card is laggy, but this is much less annoying for a user than the laggy editing experience that Lyza reported here.
