### ISSUE TITLE
Simplify logic, DOM and class names on sidebar.js

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/client#2908]
After the 2021-02-05, do the following improvements on `sidebar.js`:

* remove the feature flag `disableShadowSidebar`
* review and simplify the logic
* review the DOM organisation and class names

**Comment by lyzadanger** [comment]
Hi, @esanzgar 

Can you help me understand better a few things here?

* What is special about February 5?
* "Review and simplify the logic" seems a little vague. Are you saying that you're after a general refactor of `sidebar.js`?

Is the driving force behind this the shadow DOM changes, which will allow us to be less convoluted with our DOM and CSS?

**Comment by esanzgar** [comment]
@robertknight suggested to remove the `disableShadowSidebar` flag two weeks after the merge (Jan 22nd), if we don't hear any complains from users.

I am not after an extensive general refactor of `sidebar.js` but a small revision.

In addition to this, the `BucketBar` has a `container` option that is not longer used and can be removed. Again this is not a general refactor of the plugin system, but it will mean that BucketBar will no longer be able to be loaded as the other plugins.
