### ISSUE TITLE
Remove `presets` option in karma.config.js

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#2929]
Due to an issue with frontend-shared/ (or tools that reference those files), tests don't correctly compile jsx modules in that folder when run from the client.

`gulp test`

The quick fix is to force `@babel/preset-react` a second time in the `karam.config.js`,

```
            presets: [
              '@babel/preset-env',
              [
                '@babel/preset-react',
                {
                  pragma: 'createElement',
                },
              ],
            ],
```
            
This should be unnecessary because it's redundant in .bablelrc at the root level. For some reason the config is being wiped out as soon as files are imported from frontend-shared.  This should be fixed so we don't duplicate babel config or if frontend-shared is migrated into its own repo, this needs to be removed.

**Comment by robertknight** [comment]
This was done in e3467f5d3c0f28d888fa55f5cf4428c3551c2491.
