### ISSUE TITLE
Optimize publishing step for frontend-shared package

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#2936]
Currently checkout@v2 only gets the minimal git history, but in order to pass/fail the publish step for the shared package, we need to see if any diff has occurred in that folder. In order to do that we need more git history.

`inside frontend-shared.yml` we do this  by running a step

```
- name: Fetch origin
      run: git fetch origin master:master
```

But this could be slightly improved by only fetching a number of days back or setting a depth. Note that doing these may prevent tags from fetching and that may be problematic for our diff command inside `actions/frontend-shared-version/index.js` which needs to reference the last publish tag

`const diffResult = await exec(`git diff --stat v${version}..master frontend-shared/`)`
where version may be `1.645.0` for example

Ideally, we need to get the minimal amount of git history to be able to diff against the last published version.

**Comment by robertknight** [comment]
The frontend-shared package was moved to a separate repository (https://github.com/hypothesis/frontend-shared) and the release process has been redone as part of that.
