### ISSUE TITLE
Don't run `yarn link` twice

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#2960]
Currently when linking the frontend-shared package, 

`gulp link-frontend-shared`
```
[11:23:34] Using gulpfile ~/Documents/client/gulpfile.js
[11:23:34] Starting 'link-frontend-shared'...
yarn link v1.22.10
warning There's already a package called "@hypothesis/frontend-shared" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.
✨  Done in 0.05s.
yarn link v1.22.10
success Using linked package for "@hypothesis/frontend-shared".
✨  Done in 0.06s.
[11:23:34] Finished 'link-frontend-shared' after 474 ms
```

We get a warning that it was already linked. We can't just suppress this warning because sometimes it may be valid when you have previously linked a second copy of frontend-shared (for example, if you checked out the client repo twice and maintain two local copies)

We need to do some checking to see if the linked frontend-shared package indeed points to the ./frontend-shared folder from the repo that `gulp link-frontend-shared` was run from. The linked shared package will typically reside in `frontend-shared -> ../../../../.config/yarn/link/@hypothesis/frontend-shared` (or similar) and from that folder, we should see a symlink back to the ./frontend-shared subdir of the client repo we are running the `gulp link-frontend-shared` command from.

e.g.
```
$ pwd
/Users/kyle/Documents/client
$ cd ../../../../.config/yarn/link/@hypothesis/frontend-shared
ls -l
`lrwxr-xr-x  1 kyle  staff  44 Jan 28 15:05 frontend-shared -> ../../../../Documents/client/frontend-shared`
```

in this case `Users/kyle/Documents/client` matches, so we know its linked up correctly. There may be an easier way, but this is one approach.

**Comment by robertknight** [comment]
This issue no longer applies following the extraction of this package into a separate repository (https://github.com/hypothesis/frontend-shared).
