### ISSUE TITLE
SPIKE: use alternative URLs when searching for annotations

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/client#2975]
When searching for annotations the client includes a number of equivalent URLs based on certain elements on the page.

For example, the search includes the DOI (`https://hypothes.is/api/search?_separate_replies=false&group=__world__&limit=200&offset=0&order=asc&sort=created&uri=doi%3A10.1097%2FJOM.0000000000000063&uri=https%3A%2F%2Fpubmed.ncbi.nlm.nih.gov%2F24806729%2F`) if the document contain this
 `<meta name="citation_doi" content="10.1097/JOM.0000000000000063">`.

Does the client includes the alternative URL if the document contains: `<link rel="alternative" href="[URL]" >`? Would this be useful?

This is related with: https://github.com/hypothesis/product-backlog/issues/1175

**Comment by robertknight** [comment]
> Does the client includes the alternative URL if the document contains: <link rel="alternative" href="[URL]" >? Would this be useful?

`rel="alternate"` (note _alternate_, not _alternative_) can be used for many different purposes and often the same "alternate" URL is re-used across many pages on the same site. The most common use I'm aware of is when many pages on a site use the same `<link rel="alternate">` link to refer to an RSS or other feed. See [the Hypothesis blog for example](https://web.hypothes.is/blog/5-ways-to-use-the-new-hypothesis-canvas-groups-integration/). For this reason we definitely can't just use `<link rel="alternate">` as search URLs when the client calls `/api/search`.
