### ISSUE TITLE
SPIKE: assess the possibility of not injecting `annotator.css` to the host page

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/client#2979]
Now that we have shadow-DOMed the sidebar, we could experiment with the possibility of not injecting `annotator.css` to the host page.

Pros:

- Host page's look and feel won't be disrupted by hypothesis's CSS
- Less backdoors to change certain aspects of the application. For example, https://github.com/hypothesis/client/issues/1853 (https://elifesciences.org/for-the-press/81d42f7d/elife-enhances-open-annotation-with-hypothesis-to-promote-scientific-discussion-online).

Cons:

- Annotation highlight must be shadow DOMed.

**Comment by robertknight** [comment]
Currently we have the following elements in the host page:

- Sidebar container (`<hypothesis-sidebar>`)
- Adder toolbar (`<hypothesis-adder>`)
- Notebook container (`<hypothesis-notebook>`)
- Highlights (`<hypothesis-highlight>`)

Following https://github.com/hypothesis/client/pull/2997, all of these except highlights will be in shadow DOM in the vast majority of browsers. What we could do is split the annotator.css bundle into a tiny bundle that contains just the highlight styles and no global CSS, which is loaded in the host page, and the rest of the annotator CSS which is only loaded inside shadow roots, assuming that the browser supports shadow DOM.
