### ISSUE TITLE
SPIKE: don't rely on changing `margin-left` to open/close sidebar

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/client#2980]
Currently, the client relies on changing the CSS `margin-left` to open/close the sidebar. If window is resized `margin-left` also needs to be modified (at certain window widths).

A more intuitive approach of open/closing the sidebar would be changing the visibility of the iframe. Here is an example (together with a CSS-grid layout):  https://codepen.io/esanzgar/pen/qBaeGzb

However, it doesn't expands the sidebar as shown here:

https://user-images.githubusercontent.com/8555781/107369631-50761080-6ae2-11eb-82ed-575f9cbd7d76.mov

Would it be possible to simplify the layout of the sidebar and still allows for the expansion of the sidebar?

**Comment by robertknight** [comment]
This report doesn't identify a specific user-facing problem that needs to be solved, so I'm closing it for now. If we encounter a user-facing issue that we want to address, then we'll describe it in those terms and find a suitable solution.
