### ISSUE TITLE
sidebar empty/transparent when annotating google patents

### ISSUE THREAD

**Issue by judell** [hypothesis/client#300]
### Steps to reproduce
1. Annotate any Google patent

### Expected behaviour
Normal annotation behavior

### Actual behaviour
http://jonudell.net/h/google-patent-transparent-sidebar.mp4

### Browser/system information

![image](https://cloud.githubusercontent.com/assets/46509/24109963/722baaa4-0d4f-11e7-859b-079510abbbbd.png)

**Comment by judell** [comment]
Returned to the page, did not repro.

**Comment by judell** [comment]
Back and forth on this, it wouldn't repro, then it would, then it wouldn't...

**Comment by lyzadanger** [comment]
@judell Can you provide a URL to "any google patent" so we can see if this one is still reproducable?

**Comment by robertknight** [comment]
I couldn't reproduce on https://patents.google.com/patent/US20120176140?oq=battery (as one random example).
