### ISSUE TITLE
Trouble logging in, annotating Independent article

### ISSUE THREAD

**Issue by cmbirk** [hypothesis/client#304]
### Steps to reproduce
1.  Navigate to http://www.independent.co.uk/voices/angela-merkel-donald-trump-democracy-freedom-of-press-a7556986.html
2.  Activate Chrome Extension (1.4.0.0 Official Build)
3.  Open Hypothes.is sidebar
4.  Click `Log In`

### Expected behaviour
I should be presented with a login form

### Actual behaviour
The sidebar closes

### Browser/system information
Chrome: Version 56.0.2924.87 (64-bit)
OS: MacOS 10.12.3

### Additional details
I am not seeing this issue on other sites, so I assume it has something to do with this particular site.  The same issue happens on other Independent articles.

On the particular article presented in `1.`, I am also not able to annotate the GraphIQ graphic, which is likely a separate issue.  I am able to see the annotation popup when selecting text, so the issue is with that graphic only.

**Comment by seanh** [comment]
@cmbirk Weird. I tried and I am able to go to that Independent article, activate the Chrome extension, log in, and annotate, no problems

When you say the sidebar closes, are you able to just open it again by clicking on the arrow button?

![peek 2017-03-23 11-05](https://cloud.githubusercontent.com/assets/22498/24244912/baf8c1de-0fb8-11e7-8af1-fdac807d33f8.gif)

Or is the sidebar actually gone such that you can't re-open it?

If you open up the Chrome development console (_Menu_ -> _More tools_ -> _Developer tools_) do you see any error messages there?

Not being able to annotate the GraphIQ graphic is indeed a separate issue, and I can confirm that I can't annotate it either, would you mind opening another issue for that?

Thanks

**Comment by chdorner** [comment]
I'm able to reproduce this, but only in Chrome:
![bug](https://cloud.githubusercontent.com/assets/112063/24954049/fa98d0d4-1f7d-11e7-8910-3eb6eb56d756.gif)

```
Version: 1.11.0
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
URL: http://www.independent.co.uk/voices/angela-merkel-donald-trump-democracy-freedom-of-press-a7556986.html
Username: chdorner
Date: 12 Apr 2017 12:49:00 +0200
```

**Comment by klemay** [comment]
No longer able to reproduce - closing
