### ISSUE TITLE
Bucket bar does not update when PDF is scrolled

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#3047]
### Steps to reproduce

1. Go to https://via.hypothes.is/https://latimerslj.weebly.com/uploads/1/3/3/7/133773423/sweat_znhurston.pdf and select the Public group. This should have ~150 annotations.
2. Wait for all the annotations to load and anchor
3. Scroll down the page at a moderate pace

### Expected behaviour

The buckets should scroll smoothly as the corresponding highlights change their position relative to the viewport.

### Actual behaviour

The buckets do not update when scrolling

### Browser/system information

Tested in Safari 14.

### Additional details

Slack thread: https://hypothes-is.slack.com/archives/C1M8NH76X/p1614004139008000

**Comment by esanzgar** [comment]
I confirm that the issue was introduced by PR #2904
