### ISSUE TITLE
Reorganize Annotation-related source SCSS

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#3126]
We recently organized Annotation-related components into a component sub-directory. Annotation SCSS has not been updated, however, and is still spread across many component SCSS modules. Reorganize SCSS for these modules in a way that makes sense with the new component-organization pattern.

**Comment by lyzadanger** [comment]
This has a slight dependency on #3000 (it's been on my mind to get to this...)

**Comment by robertknight** [comment]
Looks to me like we're done with this @lyzadanger? In `src/styles/annotator` we entry points for the annotator, highlights and PDF overrides bundles, plus a components directory.
