### ISSUE TITLE
[Notebook QA] Annotation card doesn't identify document for filtered replies 

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/client#3250]
In Notebook, the annotation cards show the name of the document where the annotation was made. However, when filtering by user, if the annotation is a reply the document name is not shown and the annotation appears without context. User must click the "Show x more in conversation" button to have the source document name appear.

<img width="647" alt="Screen Shot 2021-04-01 at 1 39 22 PM" src="https://user-images.githubusercontent.com/71603629/113337382-b4a09e00-92f5-11eb-8180-89508a506345.png">

**Comment by esanzgar** [comment]
I could include the document information in two different positions:

1. At the top level annotation

![image](https://user-images.githubusercontent.com/8555781/118139697-ea15cc80-b407-11eb-9909-effbf5dc41e0.png)

2. At the first non hidden annotation

![image](https://user-images.githubusercontent.com/8555781/118140179-6a3c3200-b408-11eb-96bc-d8008ede2624.png)

Implementation wise option 1 is easier and I also think it is more clear.

**Comment by lyzadanger** [comment]
@esanzgar Option 1, please!

**Comment by esanzgar** [comment]
Closed by #3423
