### ISSUE TITLE
Config values from h-vialib won't merge into the client's final config

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#3300]
When using LMS,  the `requestConfigFromFrame` tells the client sidebar to fetch the config from LMS via RPC. The request sends back values from `<script type="application/json" class="js-config">` and  merges that into the final config object. Settings from the iframe url itself are ignored such as `openSidebar` and `showHighlights`.  These settings happen to be defaulted to the same values that the client uses when they are missing so there are no perceivable differences. However, if someone was to change the defaults in h-vialib, then they certainly would not work because the client ignores those values.

The `group` key is also another such value that comes from the iframe url but it has a special case for it to pass through the merged config. The fix here should be to generalize the config so all these values, including `group`, `openSidebar` and `showHighlights` etc, pass a whitelist test and get merged into the final config. We also need to resolve which values take president in case any are duplicated in the via url and then again in the js-config RPC result.

**Comment by robertknight** [comment]
> When using LMS, the requestConfigFromFrame tells the client sidebar to fetch the config from LMS via RPC. The request sends back values from <script type="application/json" class="js-config"> and merges that into the final config object. Settings from the iframe url itself are ignored such as openSidebar and showHighlights. 

The configuration fetched by the client via `window.postMessage`-based communication with the LMS frontend is configuration _for the sidebar application only_. This configuration doesn't override the `openSidebar` and `showHighlights` settings used in the annotator part of the code. These have to come from the page / web app into which the client is loaded.
