### ISSUE TITLE
Propose plan to improve the communication between frames

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/client#3403]
1. The shadow DOMing of the `sideframe` has caused the [ePub demo to stop working](https://github.com/hypothesis/product-backlog/issues/1201). 
2. The `notebook` and `sideframe` are not able to discover each other.
3. Iframes are hyper-connected which is the cause (entirely or partially) of several issues:
  * https://github.com/hypothesis/client/issues/631
  * https://github.com/hypothesis/client/issues/540
  * https://github.com/hypothesis/client/issues/688
  * https://github.com/hypothesis/client/issues/539
  * https://github.com/hypothesis/client/issues/249

Because of all the above, we should propose a plan to tackle the communication issues in the client.

@robertknight has suggested `MessageChannel` API as a mechanism to enable sending private messages between frames.

**Comment by esanzgar** [comment]
This is related to: https://github.com/hypothesis/lms/issues/433

**Comment by robertknight** [comment]
Hi @esanzgar - Thanks for the thoughtful write-up. I left some notes here: https://hyp.is/go?url=https%3A%2F%2Fgithub.com%2Fhypothesis%2Fclient%2Fissues%2F3403&group=wqvn7Lar

In summary:

- I think we can simplify the guest <-> host communication requirements slightly by assuming that a guest will always know which of its ancestors is the host.
- Furthermore I think we can support only scenarios where the guest is a direct child of the host initially, though it may have a different origin
- The host frame should always be able to get a reference to both windows that need to communicate with each other: either directly or via the `event.source` property of a `MessageEvent` from the window to the host, so I think we can let it have the responsibility of creating the `MessageChannel`
- As you noted, a relay introduces latency in message delivery, though I don't know how much. More importantly though it means that any messages sent between the two parties will be observable by the host. With the current messages we send that's not really a problem as guest/host frames are always considered untrusted. It could be a problem for notebook <-> sidebar communication though

**Comment by esanzgar** [comment]
Based on your comments I created this prototype:
https://github.com/hypothesis/client/pull/3494

Thank you very much!

**Comment by esanzgar** [comment]
On the prototype above in #3494, we have used `Potential option 1` and it feels it is the right solution.

The current shortcomings with the inter-frame communication were described in detail. Several solutions were also proposed.

I will close this ticket.
