### ISSUE TITLE
`Window.getComputedStyle` returning `null` is not handled

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#341]
There are a large number of error reports coming from Firefox due to a call to `window.getComputedStyle` returning `null` which is not being handled. See https://sentry.io/hypothesis/client/issues/244947672/ and https://sentry.io/hypothesis/client/issues/244958521/

When this happens, no threads get rendered in the client. I have experienced this locally with my dev server but not with the production instance of Hypothesis.

**Comment by robertknight** [comment]
https://sentry.io/hypothesis/client/issues/244947672/

**Comment by robertknight** [comment]
https://sentry.io/hypothesis/client/issues/244958521/

**Comment by robertknight** [comment]
Possibly related: https://bugzilla.mozilla.org/show_bug.cgi?id=548397

**Comment by ajpeddakotla** [comment]
@robertknight seeing as @sheetaluk is on support this week, perhaps Sheetal can take a look at this?

**Comment by robertknight** [comment]
Yes - I've pushed a proposed fix at https://github.com/hypothesis/client/pull/342 which needs review.
