### ISSUE TITLE
Add layer of abstraction for determining counts of threads, annotations

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#3449]
The current logic for determining how many threads and/or annotations are visible or match the current filtering criteria assumes the presence of the entire annotation set in the store.

Extract logic and/or add a layer of abstraction to components (e.g. `NotebookResultCount`), helpers, etc. that determine counts.

**Comment by robertknight** [comment]
https://github.com/hypothesis/client/issues/3451#issuecomment-1731457508
