### ISSUE TITLE
Add a config context for "boot"

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#3474]
The current annotator/config/index module has contexts for various apps. It may be appropriate to pull out this file from the /annotator folder and put it in a more general location and add a "boot" context as well. Currently boot gets its config in its own ad-hoc way, but there is no reason we can't use the config/index.js module for this instead. It will also help to explicitly declare the config keys for the boot context adject to the other app contexts.

'boot' needs

- apiUrl
- 'assetRoot
- 'manifest         
- 'notebookAppUrl
- sidebarAppUrl

Relates to 
https://github.com/hypothesis/client/issues/3236

**Comment by LMS007** [comment]
One thing we need to consider with the boot code is that it needs to be extremely lightweight and small so its speedy to load. Importing other modules should only be done if they are critical, otherwise it may be worth maintaining the ad-hoc approach and closing out this ticket.

**Comment by robertknight** [comment]
> One thing we need to consider with the boot code is that it needs to be extremely lightweight and small so its speedy to load. Importing other modules should only be done if they are critical, otherwise it may be worth maintaining the ad-hoc approach and closing out this ticket.

For this reason I'm not sure we want to try and reuse the same config parsing code in the boot module. I'm going to close this for now and we can revisit when we have a stronger idea of why we'd want to do it.
