### ISSUE TITLE
Guidance for local files should include "reloading tab".

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#348]
### Steps to reproduce
Just checking the box for allowing local file access in Chrome isn't enough. You also need to reload the tab where that local file is if it's already been loaded prior to allowing access.  Our instructions should say that-- probably in bold.  It's bitten me, and it also just bit a user... 

Tweets:
https://twitter.com/GoogleGuacamole/status/850801375541899266

### Expected behaviour
Users should follow our directions and get results.

### Actual behaviour
Since we don't describe a crucial step, users hit a dead-end.

### Browser/system information
Chrome / extension

**Comment by sean-roberts** [comment]
was thinking about adding:

**Step Three:** After you have allowed file URL access, reload the pages you are trying to annotate.

work for you?

**Comment by sean-roberts** [comment]
@dwhly ^

**Comment by dwhly** [comment]
Pefect.
