### ISSUE TITLE
Use `ConfirmModal` for all current `window.confirm` situations

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#3515]
Currently, the client will use the `window.confirm` when available in the browser in cases where it needs a boolean confirmation from the user, falling back to the `ConfirmModal` (our own implementation of a boolean Modal, with our styling) if the browser will not provide `window.confirm`.

Now that `ConfirmModal` is established, go ahead and use it in preference to the browser's native controls across the application here by removing the code path for `window.confirm` from the `prompts` module.

**Comment by robertknight** [comment]
Implemented by https://github.com/hypothesis/client/pull/3646.
