### ISSUE TITLE
Evaluate replacing `Panel` in `SidebarPanel` with (shared) `Dialog`

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#3518]
The `SidebarPanel` component currently uses a `Panel` component (which, by the time you read this, is likely the `Panel` from the `frontend-shared` package).

It might be desirable to use `Dialog` instead. Reasoning:

* The ability to set an initial focus element in `Dialog` — this could allay some a11y issues with these panels
* Only one `SidebarPanel` is displayed at a time; they are really conceptually "dialogs"

Don't do this if it's more trouble than it's worth. It will likely require some adaptation of `SidebarPanel` to pass through an initial focus ref.

**Comment by robertknight** [comment]
Closing this as something we'll revisit when we have a stronger motivation for it.

**Comment by acelaya** [comment]
This is actually done already 😅. I guess it was refactored as part of some other task and we forgot to close this.
