### ISSUE TITLE
The client and extension are not working locally

### ISSUE THREAD

**Issue by lutaev** [hypothesis/client#3641]
Hi there. Thank you for your work.

I'm not sure it is a bug, but I suppose it can be helpful for other developers to understand how to develop h-client. I'm trying to run the client + browser extension, so, please correct me if I do it wrong.

### Steps to reproduce
1. Install [browser extension](https://github.com/hypothesis/browser-extension), then run in extension repo: `make build`.
I got problems on this step, so I did everything as it was described in docs and got a lot of errors after loading into Chrome, for example: 
`Unchecked runtime.lastError: Cannot access contents of url "chrome-error://chromewebdata/". Extension manifest must request permission to access this host.`. 
Also, some fetch errors:

![Screenshot 2021-08-02 at 19 26 19](https://user-images.githubusercontent.com/6015401/127893589-a11b4902-3a9c-484d-a3a7-4cfa75b6bb7e.png)

2. Clone the hypothesis client and install dependencies.
3. In extension repo run: `yarn link`. Then in the client repo run `yarn link hypothesis`
3. Then run the client with command `make dev`. By default (as I understand), it uses 4000 port.
4. Add client to your page. I did it with script:
```html
<script src="http://localhost:4000"></script>
``` 

### Expected behaviour
The client should appears on the right-hand side

### Actual behaviour
Nothing happens, I see in Chrome dev tools console:
```
Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost:4000/ with MIME type text/html.
```

### Browser/system information
MacOS Catalina 10.15.7
Chrome 91.0.4472.114

I'm sure I missed something.  Any help is appreciated.

Thanks.

**Comment by robertknight** [comment]
Are you running a local version of the "h" server? The references to `localhost:5000` are attempts to connect to this.

> Unchecked runtime.lastError: Cannot access contents of url "chrome-error://chromewebdata/". Extension manifest must request permission to access this host

I've not seen this before. This is not a URL that our code generates itself so it might be something that Chrome has generated in response to some earlier error. You will need to do some investigation to find where the `chrome-error://chromewebdata/` URL is coming from.

> Then run the client with command make dev. By default (as I understand), it uses 4000 port.

The client's development server runs on port 3000 and the client's files are served from port 3001. If you are using the browser extension however, the client is loaded from the extension itself.
