### ISSUE TITLE
How to deploy a production instance of client?

### ISSUE THREAD

**Issue by fishfree** [hypothesis/client#3689]
I sucessfully build a production instance with Nginx reverse proxy of Hypothsis H. Now I want to deploy client and then via / lms. But no detailed documentation to follow. Please help me. Many thanks!

**Comment by robertknight** [comment]
Hello,

Please don't file issues about this across all of our repositories. We don't have a complete, up-to-date tutorial for deploying Hypothesis to a production environment. This is currently something that anyone wanting to deploy their own instance will need to figure out for themselves. The closest thing that exists is our [deployment](https://github.com/hypothesis/deployment) repository which contains the scripts that we use to deploy applications as Docker containers in AWS Elastic Beanstalk.

The Hypothesis client consists almost entirely of static resources, except for a tiny HTML file with some configuration in it(see https://hypothes.is/app.html). All the static resources are served from an S3 bucket (exposed at cdn.hypothes.is) and we also publish it as an npm package ('hypothesis').

**Comment by fishfree** [comment]
@robertknight Thank you for your quick reply! I checked the [deployment](https://github.com/hypothesis/deployment) repository, still cannot figure out how to deploy.
I'd like to know which configurations in which files I need to modify according to my production enviroment (i.e. domain name, reverse proxy, etc), then build the containers locally.  
In terms of Client,  I cannot figure out why response of https://cdn.hypothes.is/hypothesis are pure Javascript as below:
![image](https://user-images.githubusercontent.com/1741341/130006635-cb8c518b-0cc5-4d51-b36c-b1fb751e870a.png)
How to deploy https://cdn.hypothes.is/hypothesis after running make build under my domain https://***.com/hypothesis? I'm not familiar with Node.js application deployment.

**Comment by fishfree** [comment]
@robertknight I can understand your situation. Or could you provide some more detailed deployment doc or somewhat out-of-box docker-compose.yml for all services of hypothes.is? Thank you very much!
