### ISSUE TITLE
Local PDF support doesn't work when using Vimium-C's PDF extension

### ISSUE THREAD

**Issue by NightMachinary** [hypothesis/client#3690]
When using [vimium-c](https://chrome.google.com/webstore/detail/pdf-viewer-for-vimium-c/nacjakoppgmdcpemlfnfegmlhipddanj?hl=en) , I  get this error from hypothesis:

![image](https://user-images.githubusercontent.com/36224762/129776596-850abfae-e7c8-4ca5-87fc-3c254d49bef8.png)

Other vimium-c links:
- https://github.com/gdh1995/vimium-c
- https://github.com/gdh1995/vimium-c-helpers (the PDF viewer resides here, and is a fork of Mozilla's)

**Comment by robertknight** [comment]
What is the page URL when you tried to activate Hypothesis? I would have expected to see this error:

<img width="674" alt="Chrome custom PDF error" src="https://user-images.githubusercontent.com/2458/129854350-0fa1f3dc-2468-427b-8637-bcc5ddcb52ad.png">

From what I recall, Chrome extensions are not allowed to inject scripts into pages served by the browser (eg. `chrome://settings`) or other extensions. If I've remembered that correctly, then the answer is that this is something we simply can't support - sorry!

**Comment by NightMachinary** [comment]
![image](https://user-images.githubusercontent.com/36224762/129885325-bd822d38-9bab-487e-9fe1-a82a207b53cd.png)

```
file:///Users/evar/Base/_Books/uni9/analysis/Mathematical-Analysis_2021-Aug-17.pdf
```

Though vimium does 'stuff' with the address bar, so I wouldn't take it at face value.

**Comment by robertknight** [comment]
> Though vimium does 'stuff' with the address bar, so I wouldn't take it at face value.

That's interesting. I didn't think it was possible to override that. That might be a useful thing for us to do in our browser extension if it is possible.
