### ISSUE TITLE
How to deploy the "make build" files? Why response of https://cdn.hypothes.is/hypothesis are pure Javascript?

### ISSUE THREAD

**Issue by fishfree** [hypothesis/client#3697]
I'm not familiar with Node.js technology stack. I cannot figure out why response of https://cdn.hypothes.is/hypothesis are pure Javascript as below:
![image](https://user-images.githubusercontent.com/1741341/130336761-c0ed6bf6-7c40-435a-a18f-90ce68e52186.png)

How to deploy "make build" files of this project to make the effect of https://cdn.hypothes.is/hypothesis?

**Comment by robertknight** [comment]
https://cdn.hypothes.is/hypothesis is the `build/boot.js` script that initiates loading of the client. It is also the same script as returned by https://hypothes.is/embed.js, which is what publishers add to their pages to embed the Hypothesis client. The contents of the `build/` directory are deployed to an Amazon S3 bucket by scripts/deploy-to-s3.js. https://cdn.hypothes.is is a DNS alias for this S3 bucket.
