### ISSUE TITLE
Cannot highlight text in books on archive.org

### ISSUE THREAD

**Issue by JJger148** [hypothesis/client#3747]
### Expected behaviour
The text in archive.org should be highlighted and the highlighted text in hypothes.is should link back to the boos in archive.org

### Actual behaviour
text in archive.org is not highlighted only the sentences are copied, but they do not link back. 

### Browser/system information
Mac M1
Brave Browser

### Additional details
maybe it is an issue from openlibrary? 
https://openlibrary.org/dev/docs/bookreader#contributors

**Comment by robertknight** [comment]
>  It does update the URL as you navigate through the book, but Hypothesis doesn't currently react by changing the set of loaded annotations.

This issue has now been resolved, so that leaves supporting annotation of SVGs.

**Comment by leedenison** [comment]
Closing this as SVG annotations are being tracked here:

https://github.com/hypothesis/product-backlog/issues/1502
