### ISSUE TITLE
Use `Icon` component and shared icons

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#3876]
This may be a task to work at over a few PRs, but we should start converting the `client` to use shared icons from the `frontend-shared` package, and converting uses of `SvgIcon` to `Icon`.

**Comment by robertknight** [comment]
The `SvgIcon` component no longer exists in the client, although there are still some references to it in comments which need to be updated.

**Comment by lyzadanger** [comment]
> The SvgIcon component no longer exists in the client, although there are still some references to it in comments which need to be updated.

Yep, I just did that same grep. OK, tell you what. I'm going to open a tiny PR to remove the references in comments.
