### ISSUE TITLE
Client fails to load on nepremicnine.net (and other sites that directly load Google Swiffy runtime)

### ISSUE THREAD

**Issue by chdorner** [hypothesis/client#398]
### Steps to reproduce
1. Go to https://www.nepremicnine.net/ in Chrome or Firefox (possibly other browsers as well)
2. Activate the browser extension or the bookmarklet

### Expected behaviour
The client should load and allow the user to annotate.

### Actual behaviour
The client fails to load with a Javascript error message. In Firefox it complains about: `TypeError: this.__swiffy_name is undefined` in the `script.js` that is provided by the page. In Chrome it complains about: `Uncaught TypeError: Cannot read property 'localName' of undefined` also in the `script.js` that is provided by the page.

### Browser/system information

Firefox:

```
Version: 1.19.0
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0
Date: 23 May 2017 12:35:15 +0200
```

Chrome:

```
Version: 1.17.0
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Date: 23 May 2017 12:36:11 +0200
```

**Comment by robertknight** [comment]
The page has a buggy implementation of `Function.toString` which is normally an alias for `Function.prototype.toString`. Somewhere along the line when our [core-js](https://github.com/zloirock/core-js) polyfills load, which happens right at the start of the client's load, they end up invoking this buggy implementation and crashing out.

The buggy implementation of `Function.toString` has references to the [Swiffy](https://en.wikipedia.org/wiki/Google_Swiffy) runtime and you can reproduce the problem using the Swiffy demos:

1. Click on one of the demo links at https://developers.google.com/swiffy/showcase/
2. The demos run inside an iframe. Get the iframe's URL and open it in a new tab
3. Attempt to activate Hypothesis client

This will now fail with a similar error.

**Comment by ajpeddakotla** [comment]
Wondering if this is an H issue that needs to be fixed on our end @robertknight?

**Comment by ColCh** [comment]
Any news here? Seems that Swiffy breaks Function.prototype.toString
