### ISSUE TITLE
chrome 60 failed to load

### ISSUE THREAD

**Issue by wwj718** [hypothesis/client#399]
![image](https://cloud.githubusercontent.com/assets/3153878/26388347/56545172-4086-11e7-8672-8161b12b9a88.png)

**Comment by robertknight** [comment]
Thank-you for the report, can you please provide information about:

1. The browser + version you are using (you can check in Chrome by going to chrome://version)
2. The URL you are trying to annotate
3. The version of the client you are using. You can find this out by looking at Hypothesis' entry in chrome://extensions
4. Details of any error messages which are visible in the console (View -> Developer -> Developer Tools in the menu, then go to the Console tab. Errors are highlighted in red).

**Comment by nickstenning** [comment]
@robertknight as it says in the title, this is Chrome 60, and the image is of the GitHub homepage.

I can reproduce on our own website, e.g. at https://web.hypothes.is/blog/qdr-ati/, which is embedding the latest client.

Doesn't seem to affect the Chrome extension for me.

I think this is worth prioritising as at the current cadence, Chrome 60 will be out for all users in a month or so.

**Comment by robertknight** [comment]
Thanks @nickstenning - I can reproduce too with Chrome 60 (60.0.3100.0) on https://web.hypothes.is/blog/qdr-ati/.

**Comment by sean-roberts** [comment]
Thanks for reporting. The Chrome team reproduced the issue and identified it as a regression. Will update when issue has been addressed. Chromium issue:

https://bugs.chromium.org/p/chromium/issues/detail?id=726839&q=iframe&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by wwj718** [comment]
👍

**Comment by sean-roberts** [comment]
Fixed in latest canary 👍

**Comment by wwj718** [comment]
👍
