### ISSUE TITLE
Guests in file:// or other opaque origins cannot connect to sidebar

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#4011]
When a guest frame is loaded from a file:// URL or some other [opaque origin](https://html.spec.whatwg.org/multipage/origin.html#concept-origin) and sends a request to the host frame for a guest <-> sidebar connection, `PortProvider#listen` will receive a `MessageEvent` whose `origin` is the _string_ "null". This string is not a legal argument to `window.postMessage`, so an error occurs when PortProvider attempts to send the port back to the guest using `source.postMessage(data, event.origin)`.

Related Slack thread: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1638812510038200

One possible solution would be to special case handling of opaque origins using `source.postMessage(data, event.origin === null ? '*' : event.origin)`. Another might be to always allow any origin for certain types of source frame (eg. guests).

**Comment by mattdricker** [comment]
This is the original user report: https://app.hubspot.com/contacts/6291320/ticket/690271618/

Example local HTML files attached to that ticket.
