### ISSUE TITLE
Provide an option to keep some filters when using `store.clearSelection`

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#4040]
This is a small follow-up task for https://github.com/hypothesis/client/pull/4039

The `store.clearSelection` method is fairly far-ranging in its clearing, and a use case has popped up in which we want to "clear all filters except this one pertaining to user focus."

Rob suggested making the `clearSelection` method take accept a list of filters that should not be cleared, optionally. Good idea. Should do.

**Comment by robertknight** [comment]
This issue is superseded by https://github.com/hypothesis/client/issues/6006, which is a more general issue about how combining the various filter modes should work.
