### ISSUE TITLE
Overlapping annotations on PDFs cause text to be unreadable

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#408]
### Steps to reproduce
1. Open this link: https://hyp.is/1HFqPDR4EeeDM2deDdF8Rw/www.heartland.org/_template-assets/documents/Books/Why%20Scientists%20Disagree%20Second%20Edition%20with%20covers.pdf

### Expected behaviour
The selected text on the PDF should be clear and visible on the page.

### Actual behaviour
There are so many overlapping highlights that the text is nearly completely obscured.

### Browser/system information
Chrome / extension

### Additional details
Seems like the way we use layers to communicate highlights results in diminished visibility of the text with each layer for PDFs.  May need to fundamentally change approach, or use lighter gradients for the 2nd, 3rd and 4th overlaps.  Perhaps after 3-4 overlaps we shouldn't darken further.

**Comment by robertknight** [comment]
https://github.com/hypothesis/client/issues/1995 explains the underlying issue and why it happens with PDFs but not web pages. In short, highlights in PDFs are drawn _on top of_ the text whereas in web pages they are drawn _underneath_ the text.

**Comment by robertknight** [comment]
The situation has been significantly improved with https://github.com/hypothesis/client/pull/1996, although there is still some loss of readability as the highlights are still drawn _on top_ of the text in PDFs.
