### ISSUE TITLE
Wrong autocomplete tag selection

### ISSUE THREAD

**Issue by lupa18** [hypothesis/client#409]
### Steps to reproduce
1. Create a quote
2. begin writing a tag below 
3. when autocomplete displays a work, click on it

### Expected behaviour
The whole word must be selected (tag)

### Actual behaviour
Only the portion of the word you written is selected, so you create a new (invalid) tag

### Browser/system information
Firefox 53.0.2 (64-bits)
Linux Mint 18.2 (Ubuntu 16.04)

**Comment by lyzadanger** [comment]
This looks to have been fixed over time and cannot be reproduced with the current tag editor. Thanks!
