### ISSUE TITLE
SVG documents cannot be annotated

### ISSUE THREAD

**Issue by almereyda** [hypothesis/client#4174]
### Steps to reproduce
1. Open https://www.solipsys.co.uk/Chartodon/107731033028536736.svg
2. Try to load the Hypothesis client
  - Either through the bookmarklet
  - Or through https://github.com/diegodlh/unofficial-hypothesis-extension
3. Get error

### Expected behaviour

Hypothes.is appears and I am able to annotate the SVG, very much like we would a PDF.

### Actual behaviour

It is not possible to annotate the SVG. An error appears:

![Bildschirmfoto von 2022-02-03 02-36-06](https://user-images.githubusercontent.com/1645308/152266827-0b5153e3-4067-4762-a889-849b3b045042.png)

![Bildschirmfoto von 2022-02-03 02-36-27](https://user-images.githubusercontent.com/1645308/152266837-ec38d651-05f0-4eef-a42e-ff26b4bc4a0b.png)

This is due to the SVG document not being an HTML document.

### Browser/system information
Firefox 96, Ubuntu 21.10

**Comment by robertknight** [comment]
To make this work I think we'd have to do something similar to what we do with PDFs, where we have an HTML viewer app in the extension that fetches and presents the non-HTML content. The Hypothesis client can then be loaded in the HTML viewer.

An additional problem to solve is that we don't currently support drawing highlights on SVG text.

**Comment by almereyda** [comment]
Thank you for the details. Yes, this is what I was thinking, but didn't intend to prescribe.

You were thinking about #201 and #3747, to make the relation explicit, am I correct?

**Comment by robertknight** [comment]
Yes, with the twist that the entire document is SVG, rather than an SVG embedded in an HTML document.

**Comment by nairiboo** [comment]
Closing in favour of https://github.com/hypothesis/product-backlog/issues/1502
