### ISSUE TITLE
Annotator control UI is affected by base-REM changes in host page

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#4248]
We've run into a few cases in which user font-zooming (which resets the base REM size) or host page REM base sizing detrimentally affects the UI of the controls in the annotator (those controls rendered inside of shadow DOMs in the host page). 

In the most pertinent case of VitalSource EPUB support, zooming the font size in the VitalSource viewer is impacting the layout and appearance of the toolbar buttons next to the sidebar:

![image](https://user-images.githubusercontent.com/439947/155719734-5c60cc42-9511-4998-8dd4-bb6fa67920bf.png)

We need to decide whether we want to:

* Allow these controls to scale with user scaling (grow and shrink) with the host page's base font size. In this case, we need to make _all_ of the applied CSS relative. Right now we have a mix of relative spacing/sizing with absolute (pixel) font sizes. The spacing is scaling but the fonts are not, and there may be some remaining pixel-based positioning that breaks down.
* Enforce an absolute size for these controls no matter what user scaling preference is. In this case, we need to make _all_ of the applied CSS absolute.

My heart prefers the first option because it is truer to the web's intention and feels more accessible. However, there may be general preference for the second. I'm going to need some input.

See also a related case in PDFjs from a few weeks ago: https://github.com/hypothesis/client/pull/4208

**Comment by chrisshaw** [comment]
Strongly in favor of the first option for the accessibility reason @lyzadanger describes. This is an often explicit recommendation by accessibility advocates.

This particular problem doesn't look urgent, but if we find a collection of places where user preference breaks our design then it may be high time to change our design to accommodate it.
