### ISSUE TITLE
Support Feature Flags in annotation layer

### ISSUE THREAD

**Issue by sean-roberts** [hypothesis/client#434]
Currently, feature flags (all tied to a user account) are only available within the angular context of the sidebar. They are loaded from the api but are only in memory within the iframe of the sidebar. The plan here is to use some flavor of postMessage or crossframe to bubble up the feature flags when they become available. Then, store them in memory on the annotation layer. Any time the message triggers, we override the current feature flag state.

When this is complete, this will allow us to feature flag annotation layer settings such as using one variant of a highlighter or another.

**Comment by robertknight** [comment]
This was implemented in https://github.com/hypothesis/client/pull/440
