### ISSUE TITLE
Show highlights now defaults off

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#456]
### Steps to reproduce
1. With extension, open sidebar
2. Turn on show highlights
3. Browse to another page

### Expected behaviour
1. Show highlights should be on by default
2. <del>Show highlights button should be sticky across pages</del> (We don't think it was every sticky - seanh)

### Actual behaviour
1. Show highlights off by default
2. Not sticky

### Browser/system information

Version:
1.22.0
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36

**Comment by seanh** [comment]
This should be fixed now, release is on its way
