### ISSUE TITLE
Annotations anchoring incorrectly.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#480]
### Steps to reproduce
1. Go here: https://hyp.is/IOAv5lb_SxqS1QwwT9NyCw/web.hypothes.is/publishing/
2. Go here: https://hyp.is/AVP_f0pCH9ZO4OKSlpsd/web.hypothes.is/publishing/
3. Go here: https://hyp.is/Vkg__XH0TG6GgRcDP4u7cQ/web.hypothes.is/publishing/

### Expected behaviour
These should orphan

### Actual behaviour
They don't

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

### Additional details
If you have other information which might be helpful, please include it. If a
screenshot will help to illustrate the issue you are reporting, please include
one.

**Comment by judell** [comment]
Observation on https://hypothes.is/api/annotations/IOAv5lb_SxqS1QwwT9NyCw:

```
               {
                    "exact": "just below",
                    "prefix": "\\"></script> Ideally, place that",
                    "type": "TextQuoteSelector",
                    "suffix": "</body>, but it should work any"
                },
```

How is markup finding its way into the prefix and suffix? I think that should never happen.

**Comment by judell** [comment]
And perhaps it has not happened for a long time. Here is the timestamp on that annotation:

```
    "updated": "2015-07-21T15:26:22.069765+00:00",
```

It was created almost 2 years ago.

**Comment by dwhly** [comment]
It's possible this is fixed?  Not closing till we're sure, but de-prioritizing.

**Comment by ajpeddakotla** [comment]
Closing as a similar ticket exists: https://github.com/hypothesis/client/issues/258
