### ISSUE TITLE
How to print annotations?

### ISSUE THREAD

**Issue by dusandevic** [hypothesis/client#4826]
Hello, 

What would be the optimal approach to implement a feature to print the annotations?

My idea is to present annotations as a footnotes but I see some challenges here, e.g. how to properly render the replies (hierarchy). 

It's also required to use existing data to detect places in DOM and put the footnote-references. 

I'm just looking for a high level overview of how you would approach this requirement. Maybe I'm missing something obvious. 

My goal for now is to do this for web pages, I can imagine the PDF part would be much more challenging. 

Thanks upfront and keep the great work!

**Comment by robertknight** [comment]
> What would be the optimal approach to implement a feature to print the annotations?

This is an open and un-explored question, on both the technical and design fronts. Among the technical challenges:

- The annotations in the sidebar are virtualized, which means that only annotations in/near the viewport are actually rendered in the DOM, so you can't print that view directly. It would be necessary to implement some new print-friendly view of the data.
- The text of annotations and replies is not actually present in the DOM where the highlights are displayed. It is kept separate in the sidebar to isolate the comments from third-party JavaScript on the page. So this makes combining content and annotations more complicated, depending on whether those security properties are preserved.
- Ignoring the issue in the previous point, you'd need to figure out a way of intermingling the content and comments in a way that works for most pages. Presenting the content as footnotes as one design option, but then you'd need to figure out how to do this on a technical level.

**Comment by dusandevic** [comment]
Thanks @robertknight, really appreciate your feedback!
