### ISSUE TITLE
view switcher missing for logged-in user in https://github.com/hypothesis/pdf.js-hypothes.is

### ISSUE THREAD

**Issue by judell** [hypothesis/client#485]
# Steps to reproduce:

1. Follow the README setup for https://github.com/hypothesis/pdf.js-hypothes.is

2. Load http://localhost:8000

# Problem behavior

When logged in, the view switcher vanishes and the console says:

```
console.js:26 Error connecting to H push notification service
...
Received a broken close frame containing a reserved status code.
```

![image](https://user-images.githubusercontent.com/46509/27891613-9e68bea4-61af-11e7-89cf-1b5963412a92.png)

Also reported to https://github.com/hypothesis/pdf.js-hypothes.is/issues/13 but I'm guessing the recent epub/frame-related changes are involved, so reporting it here as well. 

I initially noticed this in the Canvas app, which uses the https://github.com/hypothesis/pdf.js-hypothes.is machinery, but reproduced it for this report using the https://github.com/hypothesis/pdf.js-hypothes.is as repo directly.

The severity for the Canvas app is not fatal, it is still possible to annotate and view annotations, but page notes are only findable by searching for them.

**Comment by ajpeddakotla** [comment]
@judell is this still an issue w/ the new implementation of the Canvas app? Does that app use the viewer?

**Comment by klemay** [comment]
I'm able to see the view switcher when I open a PDF in our new LMS app. @judell is it accurate to say this is no longer an issue for Canvas / other LMSes?

**Comment by robertknight** [comment]
On the basis of klemay's last comment, I'm going to close this for now. Please reopen if you can reproduce.
