### ISSUE TITLE
Internationalisation (I18n)

### ISSUE THREAD

**Issue by almereyda** [hypothesis/client#4859]
As a long time Hypothesis user since many years, I am astonished how the annotation layer for the web, which is presumably global, does not have internationalisation (i18n) measures in place.

As a user from another language space than the Anglican one, I need to set or autodetect the locale, in order to allow for collaboration with non-english speakers. (Yes, they exist!)

Are there any plans from the team and the [many many partners](https://web.hypothes.is/partners/) to open up the community and tool for non-english speaking people on earth?

This issue was opened, since I didn't find a precursor upon searching the issues and discussions here.

**Comment by robertknight** [comment]
There are a number of existing issues related to this, the last of which I would treat as the main one: https://github.com/hypothesis/client/issues/4656, https://github.com/hypothesis/h/issues/4575, https://github.com/hypothesis/product-backlog/issues/324.

**Comment by almereyda** [comment]
Thanks @robertknight! I was searching only in this repository here for internationalisation in British English, why I might not have found them. I will subscribe to those right away.

The term internationalisation is also a little broader than translation alone, as it might affect RTL and CJK languages as well.

Should we keep this issue open as a tracking discussion for the broad subject, or would we rather want to fall back to translation only, and see where issues with that arise in international contexts?
