### ISSUE TITLE
Annotator vertical toolbar icons are missing / moved on some sites

### ISSUE THREAD

**Issue by anavarre** [hypothesis/client#491]
_(Update 2020-06-10: The issue no longer happens on bustle.com, but it does happen on other sites. See recent comments for updates - @robertknight)_ 

### Steps to reproduce
1. Visit https://www.bustle.com/articles/165434-9-ways-to-give-constructive-criticism-that-are-actually-helpful
2. Click the hypothes.is Chrome icon to trigger the sidebar

### Expected behaviour

Sidebar icons should show up.

### Actual behaviour

Sidebar icons don't show up. See below:

![bustle-missing-icons](https://user-images.githubusercontent.com/293478/27983875-0956a5f4-63c8-11e7-92fa-71b35074ec7a.gif)

### Browser/system information

Ubuntu Xenial with Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by robertknight** [comment]
Thank-you for the report @anavarre . It looks like this is caused by CSS on the page affecting the `<button>` elements in the sidebar. Specifically a `button { min-width: XXXpx }` rule.

We could fix in modern browsers this the same way we fixed issues with page styling interfering with the Annotate/Highlight toolbar using Shadow DOM.

**Comment by robertknight** [comment]
We changed the implementation of the toolbar recently for accessibility reasons and the use of actual `<button>` elements is causing this or similar issues to happen on more sites. One site this is happening on is Slashdot: https://science.slashdot.org/story/19/10/16/0037252/californias-new-law-bans-schools-from-starting-before-8am. Tested with version 1.443.0.

<img width="444" alt="Screenshot 2020-06-09 16 30 46" src="https://user-images.githubusercontent.com/2458/84167887-b2233e00-aa6e-11ea-825c-24cfa21fc134.png">

**Comment by esanzgar** [comment]
I confirm this will not longer be an issue once we deploy #2904.

I have been able to test it successfully with https://science.slashdot.org/story/19/10/16/0037252/californias-new-law-bans-schools-from-starting-before-8am.

For this site, https://www.bustle.com/articles/165434-9-ways-to-give-constructive-criticism-that-are-actually-helpful, the CSS intrusion doesn't seem to be an issue any longer
