### ISSUE TITLE
Overlay Highlighter Tail

### ISSUE THREAD

**Issue by sean-roberts** [hypothesis/client#510]
Here are some thoughts that should get addressed with the overlay highlighter:

- Layering. With overlay highlighting, the highlights are on a different layer than the rest of the content. Where as when we wrapped the actual text nodes with the highlighter dom we inherited the same z-index layer as the content. We don't get that benefit anymore. So in order to not run into issues where the highlights are on a lower level than the content (making them hidden) or where the highlights overlay all content layers (making things like modals and floating elements on the page have highlights over them - breaking UX).
- Accessibility. With the previous text wrapping highlighter model, the highlights were in context with the content and tabbing to them and making them keyboard accessible would have been far more straightforward. In the overlay world (in the first iteration) all of the dom that is embedded is appended to the body as the last set of elements. This means they are no where close to context. A significant benefit for using overlay highlighting to begin with was supporting a CFI environment (like epubs) would not break. So, I propose that when the highlighter can have the accessibility work prioritized, it should be reworked to append the dom common ancestor of the range element. By appending it as the last child of said element, you do not break CFI because there would be no expectation that the CFI selector would search that far down the tree. This would at least bring the highlights closer to context where you can actually do some useful keyboard navigation

**Comment by robertknight** [comment]
I'm going to close this as we decided not to proceed with the overlay highlighter for the moment. https://github.com/hypothesis/product-backlog/issues/1136#issuecomment-702577397 has more context.
