### ISSUE TITLE
Add Canvas usage tracking metric

### ISSUE THREAD

**Issue by dawariley** [hypothesis/client#511]
### Expected behaviour

- To be able to track Canvas usage. 
- This will allow us slice/filter the data by Canvas usage and help us be more efficient at tracking educational use. @ajpeddakotla @segdeha 
- Let's add Canvas to our list of events we track in Google Analytics.

### Actual behaviour
No way at present to monitor how many students are launching a Canvas instance of the client.

At the moment tracking:
- Chrome
- Extension
- via
- Bookmarklet

### Additional details
var validTypes - to include Canvas.

Perhaps @jeremydean has a way of already tracking this, but would be a useful addition to Google analytics. Apologies if I've missed something!

**Comment by seanh** [comment]
Thanks, I've moved this over to the Canvas repo just to keep all Canvas issues in one place. It's great to have this tracked: https://github.com/hypothesis/lti/issues/15
