### ISSUE TITLE
Transparent sidebar after following a direct link in Chrome v60-61

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#516]
Heather, Sean H and myself have all been able to reproduce an issue where the client loads but the sidebar application is transparent.

[Internal Slack discussion](https://hypothes-is.slack.com/archives/C03QZM0K4/p1501774682420282)

Upstream bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=753314

Reduced test case: https://github.com/hypothesis/chrome-invisible-iframe-bug

### Steps to reproduce
1. In a Chrome browser with the Hypothesis extension installed, go to https://www.nytimes.com/2017/08/02/us/politics/trump-conservative-republicans.html
2. Click on the link in the sidebar that points to https://hyp.is/PhJttnhhEee3ohv_EsiIPA/www.nytimes.com/2017/08/02/us/politics/trump-immigration.html
3.Wait for the new tab to load and the sidebar to open

### Expected behaviour
The sidebar application is visible.

### Actual behaviour

The sidebar iframe is there in the DOM, but transparent:

![screenshot 2017-08-03 17 45 12](https://user-images.githubusercontent.com/2458/28933167-100953a4-7874-11e7-8775-493bd687ef66.png)

### Browser/system information
Chrome 61.0.3163.25 (me), Chrome 60.0.3112.78 (seanh), Chrome Canary 62.0.3175.0 (me)

### Additional details

The sidebar content re-appears if I do any of the following:

1. Toggle the visibility of the iframe by applying and then removing `display: none`
2. Switch to another tab and back again

**Comment by robertknight** [comment]
CC @heatherstaines @seanh

**Comment by robertknight** [comment]
After some further experimentation it appears that the problem can be reproduced when the current tab was opened via a link inside a sidebar iframe belonging to the extension.

1. Using the Chrome extension, create an annotation with the text content `https://example.org` and save it
2. Click the link in the annotation body to open a new tab
3. Activate the extension in the new tab

I've tried variations of (1) where the link goes to a hyp.is URL, a via.hypothes.is URL and an arbitrary other URL. All reproduce the problem. Creating the same links in the host HTML page, also using `target="_blank"` does not appear to reproduce the problem. The problem does not appear to occur when using the embed.

**Comment by robertknight** [comment]
Issue reported upstream at https://bugs.chromium.org/p/chromium/issues/detail?id=753314

**Comment by seanh** [comment]
Thanks for following up on this @robertknight

**Comment by robertknight** [comment]
Something occurred to me about why it matters that the link _is opened from the sidebar_. This is because of the `window.opener` DOM property which provides synchronous access to the window which opened the current link.

The need to provide this synchronous access has some far-reaching consequences for multi-process browsers such as Chrome. See https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/

Adding the `rel=noopener` attribute to the link in the iframe in the [test case extension](https://github.com/hypothesis/chrome-invisible-iframe-bug) resolves the problem.
