### ISSUE TITLE
Unable to annotate pages with non-Unicode encoded URLs

### ISSUE THREAD

**Issue by Chenastron** [hypothesis/client#5202]
I've encountered some web pages that cannot be annotated using Hypothesis, such as https://seesaawiki.jp/w/livedoor3432/d/%b2%c6%a4%b3%a4%bd%a5%c0%a5%a4%a5%a8%a5%c3%a5%c8%a1%aa. The "Search annotation" icon keeps loading and I cannot annotate. I cannot figure out the reason, please help me. 

My operating system is Win11 22H2, Edge version is 109.0.1518.69. Are similar web pages like "https://seesaawiki.jp/w/livedoor3432/d/%a5%c6%a5%b9%a5%c8%a4%c7%a4%b9" that contain non-English or non-Unicode encoded characters in the URL causing the problem?

**Comment by robertknight** [comment]
See also https://github.com/hypothesis/client/issues/531.

**Comment by acelaya** [comment]
This should now be working. Thanks @tom-pj!
