### ISSUE TITLE
Notebook is showing only ~250 of 2000+ annotations in a group

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#5219]
I have a private group with ~2100 annotations. When I select that group in the client and open the notebook, I only see 249. Looking at the search requests that the client makes I see:

1. It requests a first page of 50 annotations from the search API, and gets back a page of 50
2. It requests a second page of 200 annotations, and gets back a page of 199

The client has logic that stops fetching results once it gets back a page whose length is smaller than the number it requested: https://github.com/hypothesis/client/blob/c9cc6e39741af3bc79b59777b6db93d9ff202c29/src/sidebar/search-client.js#L165

There are two things that need to be looked into:

1. Why h is returning a page of 199 results instead of 200
2. Depending on the outcome of (1), whether we need to change the logic in the client that decides whether to continue fetching pages or not and the advice we provide in API documentation

It would be much more straightforward for API consumers if h could guarantee that, when a page of N annotations is requested, it will return N annotations, as long as there are enough in the group.

**Comment by robertknight** [comment]
Script I made for debugging this: https://gist.github.com/robertknight/bb0d5f12b3c907d0829576a41310a31c. It pages through annotations in a specified group and reports when the page size is less than what was expected.

**Comment by robertknight** [comment]
In my private reading group I have one missing annotation/reply out of 2155. I paged through the last 100K annotations in the Public group and found 6. With `_separate_replies=true`, I get 2121 annotations back from an expected total of 2122.

**Comment by robertknight** [comment]
The annotation that is present in Elasticsearch but missing in h has ID "M1kYrjmiEe2S7YcCSc2PkQ", found by comparing API results against results in Kibana. This was a test annotation created on https://hypothes.is/docs/help, so it probably only lived for a short period of time before being deleted.

**Comment by robertknight** [comment]
There are two problems to be resolved here:

1. We should try and identify how stale entries can appear in Elasticsearch, that don't have a corresponding entry in Postgres, and have a mechanism for removing them. We have a mechanism for ensure that annotation updates are reliably propagated from h => Elasticsearch, even if faults happen in various places. We could extend that to handle deletions as well (I'm assuming it doesn't already)
2. We need to fix the situation in the client where the issue in h can lead to the client not fetching all annotations in a group

The Hypothesis search API currently lacks an explicit mechanism indicating whether there are more pages to come in the results or not. Instead consumers have to use some policy such as comparing the total number they have fetched to the `"total"` field or checking when the returned page of annotations is less than what was requested (what the client currently does) or empty (another possible policy).

**Comment by kael** [comment]
> The client has logic that stops fetching results once it gets back a page whose length is smaller than the number it requested:

One way to get all annotations is to fetch the next batch of annotations after the last one until the `rows` is empty. I've seen several examples of this pattern for infinite scroll with `react-query`, not based on the match of the `total` and the `count` but by relying on the length of the next items list. It looks like a generic safe manner to prevent or circumvent potential discrepancies.
