### ISSUE TITLE
Tooltip doesn't point to what it's supposed to point to

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#526]
### Steps to reproduce
1. Shrink sidebar
2. Hover over flag icon for moderation

### Expected behaviour
Tooltip caret should point to flag

### Actual behaviour
Tooltip points too far to right

![screen-shot-2017-08-10-at-7 44 30-am](https://user-images.githubusercontent.com/1413074/29173666-ee9f82f4-7d98-11e7-8622-93ea3040c75b.png)

**Comment by fatbusinessman** [comment]
From an initial investigation, it appears that the caret ends up misaligned if (and only if) the text wraps onto multiple lines. Curiously, this doesn’t appear to be only when the sidebar is less than a certain threshold. I’m not entirely how that algorithm works.

**Comment by lyzadanger** [comment]
One of the advantages of using the browser's built-in "tool-tip" functionality (i.e. `aria-label` and `title` attributes, etc.) is that we don't run into stuff like this! Not an issue now that we're not doing our own custom tooltips here.
