### ISSUE TITLE
Client breaks if page overrides `window.navigation` global

### ISSUE THREAD

**Issue by boehs** [hypothesis/client#5324]
https://github.com/hypothesis/client/blob/a6a89b6b9c6784142c242eb46b87595f980c3454/src/annotator/util/navigation-observer.js#L81

I tried to launch hypothesis on https://www.poetryoutloud.org but could not highlight. I'll save you the boring details of how I figured all this out, but it is because this site reassigns `navigation` using `var` [here](https://www.poetryoutloud.org/wp-content/themes/pugpig-poetryoutloud-theme/scripts/header.js), and as a result, the `if (navigation)` check passes, but the `addEventListener` method no longer exists, causing an error and the entire highlighter to bork. I know that basically every window object could be reassigned so these checks are generally silly, but:

1. `navigation` *makes sense* as a variable name in the context poetry out loud was using it
2. Navigation is a new API, which means legacy websites haven't accounted for it
3. The fix is trivial

Just add additional checks for if the needed properties also exist on `window.navigation`

**Comment by robertknight** [comment]
Thanks for debugging this. Adding some stricter checks for whether `window.navigation` exists and is the object we expect seems reasonable.
