### ISSUE TITLE
Unselected text being highlighted

### ISSUE THREAD

**Issue by HuiguangChu** [hypothesis/client#5391]
When try to do annotation, if we selecting the end of the text has blank area.
The Random text below will be selected as well. 
Should be considerde as a bug?

https://user-images.githubusercontent.com/3482267/231758685-2b530101-27f8-471c-8ac9-10dbf9e1c301.mov

**Comment by HuiguangChu** [comment]
> 

I see. Thanks for the quick reply.

**Comment by robertknight** [comment]
We might end up improving this as part of resolving https://github.com/hypothesis/client/issues/5023. The issue here is indeed inherited from PDF.js, but for users it doesn't make a difference whose code the problem comes from. It would be nice to improve somehow.
