### ISSUE TITLE
fix-position-fixed issue on Ipad

### ISSUE THREAD

**Issue by ticlaudeberube** [hypothesis/client#548]
Add 2 or more annotations
Tap Edit Annotation
Type on keyboard >SideBar is hidden, only cursor is visible.

Close keyboard
Tap body >  Sidebar is visible.

This looks to be a know issue called fix-position-fixed.  But, it is not possible to catch Hypothesis frame DOM events from parent page in order to apply the fix .

https://dansajin.com/2012/12/07/fix-position-fixed/

**Comment by robertknight** [comment]
What version of iOS are you testing with? I don't have an iPad to hand for testing at the moment, but that post was written in 2012 in the era of iOS 5 and 6. It is quite likely that it no longer applies. Also, as far as I am aware, we are not using fixed positioning for the sidebar at all.

**Comment by ticlaudeberube** [comment]
IOS10
It's a kown issue with IOS.  But we cannot fix it as were not able to catch the frame events. Basically taping a textarea brings up the keyboard and the sidebar is clipped. So, we don't see what we are typing anymore.

The fix needs to be done from the sidebar frame.

Thanks for folowing up.
