### ISSUE TITLE
Look into possibility of being able to attach bucket bar to transcript container in video player

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#5488]
In the in-development video player app, all the annotatable content is in the transcript container. The bucket bar however is in its usual location on the right side of the screen:

<img width="651" alt="Video app bucket bar" src="https://github.com/hypothesis/client/assets/2458/abe703a5-b54a-431d-b617-868723181670">

I find that these buckets end up being hard to see / easy to miss as they are visually detached from the container that scrolls. A possibility that we want to explore instead is attaching the bucket bar to the transcript container. This might be connected to preventing annotation of content outside of the transcript.

- [x] Resolve issue with merging of on-screen and off-screen buckets (https://github.com/hypothesis/client/issues/5525)
- [x] Enable bucket bar to render into a custom container (https://github.com/hypothesis/client/pull/5524)
- [x] Update bucket bar bucket positions if container is resized (https://github.com/hypothesis/client/issues/5550)
- [x] Ensure top/bottom bucket scrolling works when using a custom bucket container (https://github.com/hypothesis/client/pull/5524#discussion_r1226864192, https://github.com/hypothesis/client/pull/5552)

**Comment by robertknight** [comment]
Some technical issues we'd need to work through:

- How does the host page specify a container to attach the bucket bar to?
- The bucket bar currently lives inside the `<hypothesis-sidebar>` shadow DOM, which isolates it from the page's styles. We'd probably need to extract it into its own custom element with its own shadow DOM.

**Comment by lyzadanger** [comment]
@robertknight Looks like maybe this one is good to close? Yay!

**Comment by robertknight** [comment]
Yes, this is good to close.
