### ISSUE TITLE
Links target _blank do not allow to navigate back into app

### ISSUE THREAD

**Issue by ticlaudeberube** [hypothesis/client#553]
Some links such as .annotation-header__user do not allow to navigate back to app.

In order to have them work in Cordova we would need to use window.open in order to force it to open in a browser window.

Would it be possible to allow these links to be overridden/customized by passing an event via the configuration object?   window.hypothesisConfig.customBehaviour

**Comment by robertknight** [comment]
We are currently working on allowing publishers to customize which URL the username link opens by providing a `usernameUrl` parameter in the client configuration, which will probably be a URL template that contains the username somewhere. Will this meet your needs?

**Comment by ticlaudeberube** [comment]
In Cordova, any links pointing to H are breaking flow by jumping the app into a dead end without any capabilities to come back. The way to fix them would be to force the app to open a new browser window or to show the H content in a another single page app route.   We don't have the capapbilities to override these links so far.  

A quit fix would be to use window.open on these links for mobile apps.  Another way would be to allow override methods to be passing in by the app configuration.

**Comment by lyzadanger** [comment]
@robertknight Is this one still applicable/valid?

**Comment by lyzadanger** [comment]
Thanks for the update @ticlaudeberube !
