### ISSUE TITLE
Support re-arranging tags via drag-and-drop

### ISSUE THREAD

**Issue by kael** [hypothesis/client#5542]
Sometimes it is required to edit annotations tags by adding a tag at a specific place between other existing tags.

In that case of tags edition, tags that should be placed after the newly added one have to memorized, deleted from the list, and added then after the newly added one.

It'd be nice to have the ability to drag and drop tags when the annotation is in _edit/write_ mode. It would allow to simply add a tag to an annotation and then to drag and drop it between the already existing ones.

Cheers.

**Comment by robertknight** [comment]
> Sometimes it is required to edit annotations tags by adding a tag at a specific place between other existing tags.

I don't think we make any promises that Hypothesis, as a system, treats tags as an ordered list rather than a set. We do happen to preserve the order currently across the UI and backend storage, but I couldn't guarantee that will be preserved everywhere in future.
