### ISSUE TITLE
When annotation is replied to by another user, reply initially shows as mine.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#557]
### Steps to reproduce
1.  Make an annotation
2. Have another user reply to it in a different client/tab/computer.
3. Update the original client to show the new reply.

### Expected behaviour
Reply should show as by the replying user.

### Actual behaviour
Reply shows as by you-- the testing user-- until the page is reloaded, at which point the correct user shows.  This appears to only be when the "display name" flag is active.  (i.e. my name shows on annotation cards as my displayname, not my username).

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

![screen shot 2017-10-18 at 11 54 15 am](https://user-images.githubusercontent.com/1413074/31749516-52b61b00-b42f-11e7-961d-a2420aec380e.png)

![screen shot 2017-10-18 at 11 52 52 am](https://user-images.githubusercontent.com/1413074/31749512-50408a7c-b42f-11e7-858a-f663c7ab2813.png)

**Comment by robertknight** [comment]
I believe this is related to https://github.com/hypothesis/h/issues/5486 and should be fixed when that issue is fixed.

**Comment by robertknight** [comment]
The issue mentioned in the previous comment has been resolved, so this should now be fixed as well.
