### ISSUE TITLE
UX roundy corners

### ISSUE THREAD

**Issue by leedenison** [hypothesis/client#5602]
[Roundy corners in UX product issue](https://github.com/hypothesis/product-backlog/issues/1490)

- [x] Update to frontend-shared once [the PR](https://github.com/hypothesis/frontend-shared/pull/1289) there is merged and published (can use yalc in the meantime to get something ready)
- [x] Make use of the h FF, and dynamically set CSS vars accordingly
- [x] Update locally defined components to use rounded corners as well.
  - [x] Normalize menu items
- [x] Replace `rounded-[size_in_px]` with just `rounded` in components using that.

**Comment by jaredpdesigns** [comment]
Hi @leedenison I have the code for this change ready, but I don't seem to have access to contribute to the [Frontend Shared](https://github.com/hypothesis/frontend-shared) repo. I was planning to create a PR based on the changes to make it easier for everyone to review.

**Comment by acelaya** [comment]
Hey @jaredpdesigns. Can oyu check again? You should now have the same permissions as in this repository.

**Comment by robertknight** [comment]
Current PR: https://github.com/hypothesis/frontend-shared/pull/1289

**Comment by dwhly** [comment]
Lets ship this when we do as a FF, just so we can review and fine tune if necessary.
