### ISSUE TITLE
Build and download export data when user clicks "Export"

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#5619]
![Image](https://user-images.githubusercontent.com/439947/252430660-b4ccd72a-f70b-40e2-85d0-b3449b3aa949.png)

When a user clicks the _Export_ button in the proposed interface, we should construct and download export data as described in the [design document](https://docs.google.com/document/d/12q6y5uu0bojEK-vuXYZrcTrhDfg4BPumnIYUCO9GGaE/edit).

The export data should contain all annotations loaded into the store, including annotations, page notes, orphans and highlights for all users. Client-only properties should be removed from annotations.

A few notes and a spike related to this:

*  [SPIKE: branch on `client` demonstrating simple file download of loaded annotations](https://github.com/hypothesis/client/tree/spike-data-download) 
*  [Using files from web applications - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#using_object_urls) 
*  [URL: createObjectURL() static method - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static) 

This work also includes handling any error states that might arise here.

Depends on #5618 and #5640

**Comment by acelaya** [comment]
We could potentially split this task into two, one building the logic to export "active" annotations into a file, and another one to bind that logic with the corresponding UI.

That would allow work to start on the first part without depending on https://github.com/hypothesis/client/issues/5618

**Comment by lyzadanger** [comment]
Yes, the logic for transforming the annotations in the store to the rightly-shaped objects could be parallelized for sure.

**Comment by acelaya** [comment]
I have created https://github.com/hypothesis/client/issues/5640 to tackle the non-UI part

**Comment by acelaya** [comment]
Implementation is complete and we have basic error handling.
