### ISSUE TITLE
User page blank on Mac 

### ISSUE THREAD

**Issue by judell** [hypothesis/client#564]
User logs in to H site (not sidebar), sees this:

Screenshot:

![image](https://user-images.githubusercontent.com/46509/32186826-6e286c32-bd60-11e7-93c1-e2c26ac49ce6.png)

JS console reports:

![image](https://user-images.githubusercontent.com/46509/32186833-7709a762-bd60-11e7-8266-afdf7d5e74ac.png)

**Comment by klemay** [comment]
@judell we're closing out some old issues, and this one appears to not be relevant anymore. Is it safe for me to close this one, given I can't repro this now?

**Comment by judell** [comment]
Sure, thanks for checking.
