### ISSUE TITLE
Implement logic to build and download export data

### ISSUE THREAD

**Issue by acelaya** [hypothesis/client#5640]
> This issue is part of https://github.com/hypothesis/client/issues/5619. Check details there

> The export data should contain all annotations loaded into the store, including annotations, page notes, orphans and highlights for all users. Client-only properties should be removed from annotations.
>
> A few notes and a spike related to this:
>
> *  [SPIKE: branch on `client` demonstrating simple file download of loaded annotations](https://github.com/hypothesis/client/tree/spike-data-download) 
> *  [Using files from web applications - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#using_object_urls) 
> *  [URL: createObjectURL() static method - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static) 

- [x] Basic report exporting logic: https://github.com/hypothesis/client/pull/5642
- [x] Annotations sanitization, removing client-specific attributes
  - https://github.com/hypothesis/client/pull/5658
  - https://github.com/hypothesis/client/pull/5644 
- [x] https://github.com/hypothesis/client/issues/5661: 
  - https://github.com/hypothesis/client/pull/5663
  - https://github.com/hypothesis/client/pull/5665
  - https://github.com/hypothesis/client/pull/5669

**Comment by acelaya** [comment]
Main logic is now implemented. We will adjust where needed once integration with the UI is done.

**Comment by acelaya** [comment]
Reopening this one to use as a way to track smaller pieces of work

**Comment by lyzadanger** [comment]
Satisfied and done!
