### ISSUE TITLE
Clicking "Delete" button on an annotation should not scroll to it

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#566]
### Steps to reproduce
1. Annotate part of a document
2. Scroll to a different part of the page
3. Click the "Delete" button on the annotation created in step (1)

### Expected behaviour
A prompt should appear to delete the annotation. The scroll position in the page should remain unchanged.

### Actual behaviour
The document scrolls back to the position of the annotation being deleted, losing the user's current place in the document.

### Additional details
I often use annotations with a "bookmark" tag to track how far I've got in reading long essays / papers or other documents. When removing an old bookmark, it is annoying that this results in the document being scrolled back to the position of that bookmark.

**Comment by coler-j** [comment]
@robertknight did you find a way to control the delete behaviour?

**Comment by robertknight** [comment]
I am no longer able to reproduce this issue.
