### ISSUE TITLE
Generate suggested filename and validate user-inputted filenames for export

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#5670]
We are allowing users to determine the filename (not extension) of export files. We should also provide a reasonable initial suggested filename for exports.

That means we need to:

* Validate user-inputted filenames to make sure they're not insane. I don't know how far we want to go down this rabbit hole. In poking at this for about 10 minutes today, I ended up with a working regex like so: `/^[^\n:\\\/\*\?"<>|\x{0000}]{1,255}$/` reflecting the restrictions on filenames common across major OSes (mostly Windows having the most restrictions), based on https://stackoverflow.com/questions/4814040/allowed-characters-in-filename ... might be barking up the wrong tree entirely here: https://github.com/hypothesis/client/pull/5723
* Provide a good initial filename suggestion, maybe cobbled together from date and group name, e.g. `2023-07-26-Hypothesis-My Group Name`. I'll leave it up to the implementor: https://github.com/hypothesis/client/pull/5673

**Comment by acelaya** [comment]
@lyzadanger I have started a first iteration of the filename validation using a variation of the `/^[^\n:\\\/\*\?"<>|\x{0000}]{1,255}$/` RegExp.

I have removed the `\x{0000}` part, because it was making the `0` character to become invalid, and by testing the regexp in some testing sites, the explanation said it was taking that as literal characters.

What was exactly the purpose of the `\x{0000}` part?

**Comment by robertknight** [comment]
For auto-generated filenames we can adopt a conservative approach which avoids common characters that are disallowed in at least one of the major OSes (eg. `/`, `:`). I would not try to implement all the restrictions that might exist (eg. Windows disallows specific keywords as filenames, like "con"). When the user enters a filename, I suggest we should allow them to enter _anything they want_. The browser will take care of converting this to a usable filename when the file is downloaded.

**Comment by acelaya** [comment]
> For auto-generated filenames we can adopt a conservative approach which avoids common characters that are disallowed in at least one of the major OSes (eg. `/`, `:`).

The variation I'm working with at the moment is `/^[^\n:\\/*?"'<>]{1,255}$/`, which bans characters `\n`, `:`, `\`, `/`, `*`, `?`, `"`, `'`, `<` and `>`, and allows filenames between 1 and 255 characters.

We can, of course, be less strict.

**Comment by acelaya** [comment]
Finally not applying validation via a regexp. Instead, we will split this in two:

* Validate length via `required` and `maxLength` attributes on the input, as this is more accessibility-friendly: https://github.com/hypothesis/client/pull/5723
* Do not forbid any special characters, an let the browser "escape" them. We can potentially display a warning if any is used though, but this is not critical.
