### ISSUE TITLE
"Second Discovery server" issue with https://via.hypothes.is/https://www.wired.com/story/how-a-tiny-error-shut-off-the-internet-for-parts-of-the-us/

### ISSUE THREAD

**Issue by judell** [hypothesis/client#568]
The client flashes and reloads multiple times, when the URL in the title of this issue is proxied through via to Chrome or Firefox.

I actually noticed it when sharing this to Twitter: https://hyp.is/kXa8ksNqEeersAd_9WPOYw/www.wired.com/story/how-a-tiny-error-shut-off-the-internet-for-parts-of-the-us/

**Comment by judell** [comment]
Happens here too: https://via.hypothes.is/https://www.theguardian.com/environment/2016/aug/16/louisiana-flooding-natural-disaster-weather-climate-change#annotations:0Ej7cmPrEea4wn9yAf5xZg

**Comment by dwhly** [comment]
Yes, I can confirm.

What do you mean by "Second Discovery server"?

**Comment by judell** [comment]
You'll see it in the JS console. It happens when multiple instances of H fight about the RPC (crossframe) channel. Feels like what was happening before we restricted injection into iframes by requiring the enable-annotation attribute, but I can't confirm that.

**Comment by robertknight** [comment]
Also reproduced by seanh here: https://via.hypothes.is/https://www.theguardian.com/politics/blog/live/2017/nov/16/john-mcdonnell-sets-out-labours-five-key-demands-for-the-budget-politics-live

Analysis on Slack starting at https://hypothes-is.slack.com/archives/C1M8NH76X/p1510842201000410

**Comment by seanh** [comment]
@robertknight I'm wondering if this is really a client issue or a via issue? Should it be moved to the via repo?
