### ISSUE TITLE
Incorrect state of highlight visibility toggle button when highlights are initially turned off

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#569]
Report from a user about the highlight visibility toggle button having an incorrect state when the client is configured to hide highlights.

The original report was in the context of this project: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/hypothesis-forum/aPX7SYgdutY

> BTW, I noticed a bug in your embedded code" when I use 

```html
<script type="application/json" class="js-hypothesis-config">
{
"showHighlights": false
}
</script>
```

> to turn off highlights initially, the highlights are (correctly) turned off, but the "eye" icon to the left of the top of the (open) annotation panel (incorrectly) lacks a slash through it, which it should have to indicate that highlights are not being shown.

**Comment by lyzadanger** [comment]
This has been fixed at some point in the interim! Currently, if one sets `showHighlights: false` in config, this is the initial state of the toolbar:

![image](https://user-images.githubusercontent.com/439947/97318116-e773d100-1841-11eb-896f-7d93c61a9aaa.png)

(and highlights are, as desired, not displayed). Clicking on the highlight button "turns the highlights on" and correctly changes icon state:

![image](https://user-images.githubusercontent.com/439947/97318191-fc506480-1841-11eb-856c-23aa29809c40.png)
