### ISSUE TITLE
Allow users to upload an export file in Import tab

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#5692]
When import feature flag is enabled, a user should be able to access an _Import_ tab in the `client`'s Shared dialog. They should be able to select and upload a Hypothesis annotation export (JSON) file for import, and select which user's annotations they wish to import. The application should let the user know if there are problems with their uploaded file.

This task is complete when we are ready to implement what happens when the user clicks "Import" after going through these steps (Actually importing the annotations/creating them is a separate task).

**Comment by acelaya** [comment]
Completed by https://github.com/hypothesis/client/pull/5710
