### ISSUE TITLE
Write logic to upload and parse JSON annotations (exported annotations)

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#5693]
The `ExportAnnotations` component should be able to upload and parse an exported-annotation file (via an `input[type="file"]` element) to prepare for import.

It should be able to:

* Perform basic validation to ensure that the uploaded file has at least one recognizable, importable (i.e. non-duplicate) top-level annotation in it
* Build a data structure that contains information about users that have valid annotations in the file, with a count of annotations for that user, as well as a count of any duplicate annotations for that user (will be used to populate a select).

This implies the ability to duplicate-check via `id`s in the import file.

Connecting this up to "real" UI is a separate task.

We can flesh this ticket out a bit if it's helpful.

Part of https://github.com/hypothesis/client/issues/5692

**Comment by acelaya** [comment]
Completed by https://github.com/hypothesis/client/pull/5710
