### ISSUE TITLE
Implement Import tab UI and connect to upload logic

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#5694]
Implement prototyped UI for Import tab in the client and connect to file-parsing logic. Allow file upload, validation, and user-to-import-for selection.

Part of https://github.com/hypothesis/client/issues/5692

Depends on https://github.com/hypothesis/frontend-shared/issues/1180
Depends on https://github.com/hypothesis/client/issues/5693

**Comment by acelaya** [comment]
Completed by https://github.com/hypothesis/client/pull/5710
