### ISSUE TITLE
Perform annotation imports (happy path)

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#5695]
Once a user has uploaded a (valid) exported-annotations JSON file, and selected which user's annotations should be imported, and clicked "Import", perform the actual import by creating new annotations on the service.

This task covers only the simplest happy path. There should be no retry on any error encountered when creating an imported error, and only the simplest reporting/counting of imported annotations vs. annotations that failed to import.

This ticket can be fleshed out (or subtasks tracked) per implementor preference.

Some loose implementation things the team discussed:

* Once the user clicks "import", it might be helpful to construct client annotation objects representing the annotations to be imported and put them in an import queue (i.e. in the application store)
* We will probably batch requests, but size of batch TBD
* On successful annotation-create, the response of the create service should be used to add the newly-added annotation to the application store
* Imported annotations should set `extras.original_id` for subsequent duplication checking
* Include something in the request to the create endpoint that can be used to log/indicate that this is an import action

Depends on https://github.com/hypothesis/client/issues/5692

**Comment by robertknight** [comment]
https://github.com/hypothesis/client/pull/5710 implements this, but with differences compared to the original description:

> We will probably batch requests, but size of batch TBD

Request batching is not yet implemented.

> Imported annotations should set extras.original_id for subsequent duplication checking

Duplicate checking is currently done based on content (text, tags, quote selector) rather than ID.

> Include something in the request to the create endpoint that can be used to log/indicate that this is an import action

This is not currently implemented.

**Comment by acelaya** [comment]
Created draft issues for the pending points:

- Batching: https://github.com/orgs/hypothesis/projects/122/views/1?pane=issue&itemId=36125363
- Include something in the request to the create endpoint that can be used to log/indicate that this is an import action: https://github.com/orgs/hypothesis/projects/122/views/1?pane=issue&itemId=36515597

Closing this as completed to follow-up work there.
