### ISSUE TITLE
Public/Open Groups Frontend Work - New UI, Page-affiliated Groups

### ISSUE THREAD

**Issue by gobengo** [hypothesis/client#570]
Followup to adding new public and open groups on the backend [here](https://github.com/hypothesis/h/issues/4676).
This issue is to update the client to allow publisher's to configure promoted groups to appear alongside the groups that the user is a member of.

These unmerged PRs implement the work I intended by this ticket.
* [ ] client has settings.pageGroups so publishers can highlight their groups - https://github.com/hypothesis/client/pull/609
* [ ] a few more changes in h to help the client out https://github.com/gobengo/h/pull/1

**Comment by lyzadanger** [comment]
@klemay This looks out-of-date. Can we close?
