### ISSUE TITLE
For export, export filename should derive from document filename or title.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#5709]
Right now the current implementation creates an export filename from the DATE-NAMESPACE-GROUP (I think), but the current document needs to be a part of that.  In other words, we need a suggested filename which is more like DATE-GROUP-FILE/TITLE.  In other words either the filename (PDF) or title (HTML or PDF).  We should probably also truncate titles or filenames after a certain number of characters (20?).

**Comment by robertknight** [comment]
In the LMS context I think, but will have to verify, that the client doesn't currently know the filename in the case where the document is a PDF coming from Google Drive, Canvas Files etc. In those cases the PDF downloads the file from a temporary signed URL. The title embedded in the PDF should still be available though, _if_ there is one. We had planned to set up a mechanism that would allow the LMS app to communicate the original filename to the client, but I want to raise the fact that this might more complex than it seems at first.

**Comment by acelaya** [comment]
I did a quick check of what's the document title we are currently setting for the guest frame, and this is what I can see.

* Website:
    * LMS: Proper title
    * Public: Proper title
* Regular PDF
    * LMS: "PDF.js viewer"
    * Public: Proper title
* Google Drive PDF:
    * LMS: "PDF.js viewer"
* Canvas file:
    * LMS: "PDF.js viewer"
* YouTube:
    * LMS: Proper video title
    * Public: Proper video title
* MS One Drive PDF:
    * LMS: TBD
* JSTOR:
    * LMS: "PDF.js viewer"
    * Public: "jstor" (I have to verify, but I think this is the right title)

This matches what Rob said, so we probably would need to find a way to expose this title to the client in many of the LMS use cases.

**Comment by robertknight** [comment]
> I did a quick check of what's the document title we are currently setting for the guest frame, and this is what I can see.

Are you looking at the HTML document's `<title>` tag? That's not always the same as the document title that the client associates with annotations, which comes from the guest's active integration. If we're going to use a document title, that is the one that we should use.

**Comment by acelaya** [comment]
> Are you looking at the HTML document's <title> tag? That's not always the same as the document title that the client associates with annotations, which comes from the guest's active integration. If we're going to use a document title, that is the one that we should use.

I checked `document.title`, which, unless I'm missing something, should have the same value as the `<title />` tag.

**Comment by robertknight** [comment]
This was implemented in https://github.com/hypothesis/client/pull/5781. The suggested document title is the same as the one that shows up on activity pages as the document's title. We will find some cases where that title is sub-optimal. I suggest filing separate issues for such cases.
