### ISSUE TITLE
Import annotations improvements

### ISSUE THREAD

**Issue by acelaya** [hypothesis/client#5737]
The overall logic and happy path for import annotations is already implemented. This is a list of improvements and nice-to-have items for the import annotations experience:

- [x] https://github.com/hypothesis/client/issues/5741
- [x] https://github.com/hypothesis/client/issues/5740
- [x] https://github.com/hypothesis/client/issues/5739
- [x] https://github.com/hypothesis/client/issues/5738

**Comment by robertknight** [comment]
All the client-side items in this task that were essential are now done. I have removed https://github.com/hypothesis/client/issues/5791 as it is not essential and is tracked separately. There was also a link for a task to create a backend dashboard. That's outside the scope of this project though.
