### ISSUE TITLE
Show user progress of annotations import

### ISSUE THREAD

**Issue by acelaya** [hypothesis/client#5740]
UI for this needs to be defined first.

Possible sources of inspiration (more for implementation/API than actual design):

* https://mui.com/material-ui/react-progress/#linear-with-label
* https://chakra-ui.com/docs/components/progress/usage
* https://primer.style/design/components/progress-bar

**Comment by robertknight** [comment]
We do have an indicator that an import is in progress. A spinner is shown at the bottom of the import form when an import is in progress. We don't show the overall progress percentage as eg. a progress bar though.

**Comment by jaredpdesigns** [comment]
Some ideas:

**Current:**
<img width="408" alt="import-with-progress-1" src="https://github.com/hypothesis/client/assets/6108048/9c38c980-7dd7-4e2f-9f84-4fcbbdbdaeb6">

**In-progress:**
- Both inputs are `disabled` but kept in place
- Progress is shown visually on the import button with a circular progress indicator
- Overall progress is displayed a text next to the button

<img width="408" alt="import-with-progress-2" src="https://github.com/hypothesis/client/assets/6108048/b75a4f3f-0297-44f5-a8e7-50fd942a5cc5">

**Complete:**
- Using [Callout](https://patterns.hypothes.is/feedback-callout) to indicate success
- Import button acts as a reset to import more

<img width="408" alt="import-with-progress-3" src="https://github.com/hypothesis/client/assets/6108048/1b1342ad-e642-4cdd-b7d2-b7b9dbb77908">
