### ISSUE TITLE
Handle errors, edge cases and retries for imported annotations

### ISSUE THREAD

**Issue by acelaya** [hypothesis/client#5741]
Includes:

- [ ] Responding to different types of failures: network, low 400s, 429, 5xx and retry strategies
- [ ] When and how to "give up" after encountering x number of errors
- [x] Defining what level of information to give user about failed-to-import annotations
- [x] Ensuring de-duplication/idempotence

Question:

- [x] What happens if the user reloads the page in the middle of an import?

**Comment by robertknight** [comment]
> What happens if the user reloads the page in the middle of an import?

Whatever has already been imported by the time the reload happens will exist after the reload. The remainder can be imported be repeating the import, which will skip any duplicates.

**Comment by robertknight** [comment]
> Responding to different types of failures: network, low 400s, 429, 5xx and retry strategies

A 4xx error could indicate:

- Auth error. Retry will not help.  Remaining annotations will probably fail as well.
- Data validation error. Retry will not help. Remaining annotations may successfully import.
- 429 rate limit error: Retry may work after a short delay.
- 5xx error: Backend timeout or fault. Retry may work

A possible approach would be something like:

- For 429 and 5xx errors, wait for a brief delay (say 1s) and then retry. Abort after N failures, for some small N.
- For 400 errors, skip current annotation and continue with remainder. Abort after N failures.
- For other 4xx errors, abort immediately

> When and how to "give up" after encountering x number of errors

We have display toast messages after the import to summarize what happened. I suggest we report errors using the same mechanism.

> Defining what level of information to give user about failed-to-import annotations

I suggest we keep the user visible message short, since it needs to fit in a toast. We can log more details in the console for debugging. Also for support we can ask the user to send us the file they are trying to import.

> Ensuring de-duplication/idempotence

De-duplication at import time is already implemented. It currently matches based on the _content_ of annotations. We can change this later when we have a clear reason.

**Comment by robertknight** [comment]
With regards to retries, implementing that involves some decisions about what requests to retry, how much backoff (if any) to use, how many times to retry etc. I don't have a great idea about optimal values for that. I'm considering that we launch with with none in place but instead some telemetry (eg. via Sentry) to learn what is worth having. The other way of learning more is simply by trying large bulk imports in production and observing what transitory failures happen.

**Comment by acelaya** [comment]
> See https://github.com/hypothesis/h/blob/232446d776fdb906d2fb253cf0a409c6813a08d6/conf/nginx.conf#L122

If I'm getting [nginx docs](http://nginx.org/en/docs/http/ngx_http_limit_req_module.html) right, we are configuring a max amount of 1 request per second, with `burst=8`, meaning as long as we don't perform more than 8 requests in the same second, we "only" get them delayed, but not blocked.

After the ninth request in the same second coming from the same user, we would start returning 429 status responses.

Since we import at batches of 5, I think users should not be seeing these too frequently (unless they create other annotations in parallel, or share their public IP with other people which is importing annotations).

On the other hand, the 1 request per second limit is probably affecting the import in batches, so this is probably related with what's mentioned here https://github.com/hypothesis/client/pull/5751#issuecomment-1691566341

**Comment by acelaya** [comment]
This comment helped me understand nginx docs and how the `rate_limit` directive works https://serverfault.com/a/642823

**Comment by robertknight** [comment]
Adding automatic retries complicates the code and it isn't clear at the moment that it will provide enough value to justify that. It would be easier to make that decision if we actually had some data on failure rates as a baseline - eg. 1% of import requests fail with 429 errors or something.

We have increased the rate limit for the API and also added logic to send error reports to Sentry when imports fail.

I am going to punt on further work here for the moment. I did create a quick sketch of a retry implementation though:

<details>

```diff
diff --git a/src/sidebar/services/import-annotations.ts b/src/sidebar/services/import-annotations.ts
index 45b9f6f33..c66f4de5e 100644
--- a/src/sidebar/services/import-annotations.ts
+++ b/src/sidebar/services/import-annotations.ts
@@ -7,6 +7,7 @@ import {
 } from '../helpers/permissions';
 import type { SidebarStore } from '../store';
 import type { Frame } from '../store/modules/frames';
+import { FetchError } from '../util/fetch';
 import { captureException } from '../util/sentry';
 import type { AnnotationsService } from './annotations';
 import type { ToastMessengerService } from './toast-messenger';
@@ -214,35 +215,58 @@ export class ImportAnnotationsService {
       }
     };
 
+    // Return true is an error that might be fixed by retrying the request.
+    const canRetry = (err: Error) => {
+      const status =
+        err instanceof FetchError ? err.response?.status : undefined;
+      return (
+        typeof status === 'number' &&
+        (status === 429 || (status >= 500 && status < 600))
+      );
+    };
+
     // Save annotations to the server, allowing a maximum of
     // `MAX_CONCURRENT_IMPORTS` in-flight requests at a time.
     const results: ImportResult[] = [];
     const queue = anns.map((ann, index) => ({ ann, index }));
     const active: Array<Promise<void>> = [];
-    while (queue.length > 0) {
-      const task = queue.shift()!;
-      const done = importAnn(task.ann)
-        .then(result => {
-          this._store.completeImport(1);
-          results[task.index] = result;
-        })
-        .then(() => {
-          const idx = active.indexOf(done);
-          // nb. `idx` should always be >= 0 here.
-          if (idx !== -1) {
-            active.splice(idx, 1);
-          }
-        });
-      active.push(done);
-
-      // When we reach max concurrency, wait for at least one import to complete.
-      if (active.length >= MAX_CONCURRENT_IMPORTS) {
-        await Promise.race(active);
+    const maxRetries = 3;
+    let retries = 0;
+
+    while (queue.length > 0 || active.length > 0) {
+      // Fill up the `active` list of in-flight requests from the queue.
+      while (active.length <= MAX_CONCURRENT_IMPORTS && queue.length > 0) {
+        const task = queue.shift()!;
+        const done = importAnn(task.ann)
+          .then(result => {
+            // Attempt to mitigate some temporary issues by retrying the request.
+            if (
+              result.type === 'error' &&
+              retries < maxRetries &&
+              canRetry(result.error)
+            ) {
+              ++retries;
+              queue.push(task);
+              return;
+            }
+
+            this._store.completeImport(1);
+            results[task.index] = result;
+          })
+          .then(() => {
+            const idx = active.indexOf(done);
+            // nb. `idx` should always be >= 0 here.
+            if (idx !== -1) {
+              active.splice(idx, 1);
+            }
+          });
+        active.push(done);
       }
-    }
 
-    // Wait for all remaining imports to complete.
-    await Promise.all(active);
+      // Wait for at least one import to complete. The task will remove itself
+      // from the active list before it completes.
+      await Promise.race(active);
+    }
 
     const { messageType, message } = importStatus(results);
     if (messageType === 'success') {
```

</details>
