### ISSUE TITLE
Decide how to handle URI mismatch when importing

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#5743]
The import feature currently preserves the URI of the original annotation on import, rather than using the URL of the document you are currently viewing. If the user imports annotations that were exported from a different URL than the one they are currently looking at, and if the original / current document URLs are not considered "equivalent" by h, then the newly imported annotations will disappear after reloading the page.

We should decide how we want to handle this for the initial version, with particular attention paid to document URLs that will be encountered in the LMS app (eg. files in Canvas / D2L file storage, Google Drive files...)

We should also consider whether we do anything to warn against a scenario in which annotations are made on one document and then imported on an unrelated document. The problem here is that determining whether the original and new URLs are the "same" is difficult in the fully general case. We could apply some heuristics to show a warning if it is sufficiently likely that the user is making a mistake.

**Comment by acelaya** [comment]
We have decided to resolve this in a few steps:

1. Happy path: Always overwrite the URI for every imported annotation, with target document one (https://github.com/hypothesis/client/pull/5755)
2. Try to include the "original document" (Title? Name?) on the export file, so that we can display that information before importing, helping users catch possible mistakes while importing from the wrong document.

**Comment by robertknight** [comment]
https://github.com/hypothesis/client/pull/5755 solved the problem of a URI mismatch by using the target URI of the original document. However it continues to use the document metadata that was in the import file. I suggest we should use the document metadata of the current document as well, or not include document metadata at all. This will prevent mixing the document metadata of the old / new URL in the event they are different.

**Comment by robertknight** [comment]
> We have decided to resolve this in a few steps:

From these two points, we have solved (1) by always using the URI and metadata from the current document. I suggest we use separate issues for (2) because it has a bunch of complexity for different document sources. Also it is a "nice to have" extension whereas the main point of this issue was making sure the annotations were created in such a way that they don't disappear when the page is reloaded.
