### ISSUE TITLE
Ensure PDF fingerprint is included on imported annotations

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#5771]
For annotations made on PDFs, the PDF fingerprint is very important in practice, as a way to link annotations created on the same PDF but hosted at different URLs. When importing annotations, we should ensure that the PDF fingerprint of the currently loaded document is included in the metadata submitted in the `POST /api/annotations` request.

The metadata should be the same as when creating a new annotation on the current document manually. When creating an annotation directly, the metadata [here](https://github.com/hypothesis/client/blob/160c8fe59866f00f9eea81b0cd55a4be984fac7e/src/annotator/guest.ts#L782) and comes from `Guest.getDocumentInfo`.

**Comment by acelaya** [comment]
Closed by https://github.com/hypothesis/client/pull/5768
