### ISSUE TITLE
Add additional formats to annotation export

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#5784]
Adding additional format types for export will dramatically increase the utlity of this feature.  Proposed:  Add CSV, TXT and HTML formats in addition to JSON.  This will require UX to specify these additional format types, such as:

![Image](https://github.com/hypothesis/client/assets/1413074/b429037e-3562-4257-8565-c13db46ca652)

Also, the exact structure that each file format has will need to be defined.  Here is a google doc with some provisional descriptions for each.

https://docs.google.com/document/d/1Xn6AazKkpUy85VUaj9v_utasexk8lIqP_1zveILq1So/edit

---

- [x] [Create FF](https://github.com/hypothesis/h/pull/8323)
- [x] [Add format selection dropdown](https://github.com/hypothesis/client/pull/5955)
- [x] [Implement logic to export plain text file](https://github.com/hypothesis/client/pull/5960)
- [x] [Implement logic to export CSV file](https://github.com/hypothesis/client/pull/6057)
- [x] [Implement logic to export HTML file](https://github.com/hypothesis/client/pull/6073)
- [x] [Implement copy-to-clipboard](https://github.com/hypothesis/client/pull/6085)

**Comment by robertknight** [comment]
Less technical users probably won't know what the use of the different formats are. It could be helpful to spell that out in the dropdown. Something along the lines of:

JSON - For import into another Hypothesis group or document
CSV - For import into Excel, Google Sheets etc.
TXT - Plain text
HTML - Rich text

**Comment by acelaya** [comment]
I have created a project board for a more detailed progress tracking https://github.com/orgs/hypothesis/projects/131/views/1

**Comment by acelaya** [comment]
I'm going to close this as completed, as the bulk of the work is done, and the main user journey is finished.

The feature is currently disabled behind a feature flag, but we will soon enable it for public users.

There's a few pending improvements that can be tracked separately. Main ones are tagged as [project: export formats](https://github.com/hypothesis/client/issues?q=is%3Aissue+is%3Aopen+label%3A%22project%3A+export+formats%22), and a few more can be found in the [project board](https://github.com/orgs/hypothesis/projects/131/views/1).
