### ISSUE TITLE
Double-clicking to select a word in a PDF then annotating it annotates the wrong word

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#58]
Here I double click on the word "annotating". The highlight is the wrong size (it's the size of the word "bug"). When I then click to make an annotation, the annotation then gets "bug" not "annotating" as its target text.

![untitled screencast - edited 30](https://cloud.githubusercontent.com/assets/22498/17252317/2a023832-55a4-11e6-860c-dc79a20f4da4.gif)

(This looks like it might be an issue with selecting text in PDF.js)

**Comment by dwhly** [comment]
When I pinged yury on the pdfjs team on this issue about six months ago (misalignment of selection highlights vs the underlying words), he suggested that upgrading our version of PDFjs might fix this.

**Comment by ajpeddakotla** [comment]
PDFjs was updated last year, and this bug is no longer reproducible.
