### ISSUE TITLE
Slight wording changes including "copy" in addition to "export"

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#5800]

**Comment by robertknight** [comment]
Can you please add a couple of sentences of description here to clarify what this is about, or a link to the Slack thread / docs etc. if they exist.

**Comment by robertknight** [comment]
Is this covered by the "Learn more about copying and exporting" text shown in https://github.com/hypothesis/client/issues/5783#issuecomment-1710509495 / https://github.com/hypothesis/client/pull/5817 or did you intend something else?

**Comment by dwhly** [comment]
This is already covered.  Sorry for the delay!
