### ISSUE TITLE
Bookmarklet automatic login

### ISSUE THREAD

**Issue by agentcooper** [hypothesis/client#5801]
Hi,

I am using Hypothesis bookmarklet. Because each time I open it from a different domain, I need to click "Log in" button to authenticate. The auth window opens and closes right away as I'm logged in on https://hypothes.is.

I would like the auth window to appear as soon as I open the bookmarklet. I see that `openLoginForm` option was at some point available in the [client config](https://h.readthedocs.io/projects/client/en/latest/publishers/config.html), but was later removed. Is there a specific reason for this and would you be open to a PR that adds it again?

**Comment by robertknight** [comment]
>  Is there a specific reason for this and would you be open to a PR that adds it again?

Yes. The login form used to be part of the sidebar but was moved to a popup window for security reasons. Modern browsers do not allow web applications to open popup windows automatically except in response to a "user gesture". This is why you have to clock on the login button.

A general problem that the Hypothesis bookmarklet faces is that, to a browser, it looks a lot like an ad (third party iframe embedded in someone else's site), and is subject to the same security restrictions designed to prevent ads from tracking you around the web.

It might be possible to do something with the [Storage Access API](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API), but I think there would probably need to be some kind of initial interaction with the sidebar before it could fetch annotations on a site you hadn't previously visited.

**Comment by robertknight** [comment]
I should add that browser extensions can provide a better experience because they have additional places they can store login tokens, which are not subject to the same constraints as the bookmarklet. We don't currently take advantage of this in the browser extension though, and just use `window.localStorage` everywhere. `window.localStorage` is in general handled the same way as cookies, and is subject to the same treatment as third-party cookies.

**Comment by agentcooper** [comment]
I see, I didn't think about the restriction around windows that open automatically, that makes sense. Thanks.

My primary browser is Safari, so there is no Hypothesis extension for it, but I also like that the bookmarklet activates only when I click on it and does nothing otherwise.

**Comment by agentcooper** [comment]
@robertknight I was thinking more about this and got a following idea.

Let's say there is a new option in `window.hypothesisConfig` that allows to set the API key (from https://hypothes.is/account/developer). Then this can be a part of a custom bookmarklet, so it will include something like `window.hypothesisConfig = { apiKey: "..." };`. Then auth code can use this token instead of opening a separate window to login.

What do you think?

**Comment by robertknight** [comment]
The `window.hypothesisConfig` function is accessible to any 3rd-party JavaScript which happens to be running on the web page, and can be used to access any data in your Hypothesis account. I'm afraid this isn't viable from a security perspective.

**Comment by robertknight** [comment]
I'm closing this issue for the moment as we are constrained by the web platform in the context of the bookmarklet (per [this comment](https://github.com/hypothesis/client/issues/5801#issuecomment-1708225010)). In the browser extension we have more freedom and we can do better.
