### ISSUE TITLE
Enable Hypothesis LMS app to override client feature flags

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#5803]
Feature flags used by the client are currently stored in h. The flags returned as part of the profile data are produced by looking at the user's role (regular, admin etc.) and the feature cohorts they belong to.

In the context of the Hypothesis LMS integration, we have found it much more useful to turn features on or off at the level of an installation of our LMS integration, as a property of an "application instance" in the LMS app. We want to enable turning certain client features on/off at this level.

The way I envision doing this is that the LMS app will have a setting for an application instance which is translated into a dictionary of feature flag overrides in the configuration it passes to the Hypothesis client. These overrides will take precedence over feature flags received from the user's profile in h. We might want to restrict this capability to override flags so that it can't be used by arbitrary web pages. The reason being that it could lead to sites becoming reliant on feature flags that we later decide to remove.

**Comment by robertknight** [comment]
Just a note on some agreement about precedence from a call this afternoon.

The plan in the LMS app is that we will use this to switch feature flags on in some LMS instances while they are _off_ for the h user, but we won't support disabling feature flags via this feature once they are turned _on_ for the h user, eg. by turning the feature on for everyone in h.

The rationale is that once we flip the switch to "on for everyone in H", it means that it really is on for everyone, and there isn't a possibility that it has been disabled somewhere, so we don't have to continue to consider that possibility when testing etc.

**Comment by acelaya** [comment]
I just want to make a comment on the above. This approach makes sense considering we have decided to enable this feature for LMS users first, and for the "public" users later, but in most of the cases we would want to do it the other way around (I assume), enabling new features for public users first.

Just to have this in mind in case we want to re-use this for future features.

Of course, we can take a completely different approach and start enabling them always for LMS users first, as if they were premium early access features for paying customers.

**Comment by acelaya** [comment]
> We can still enable for public users first with this approach. There is a checkbox for feature flags in h which allows a feature to be turned on for first party (ie. public) users only. This is separate from the "everyone" checkbox which means first + third-party users.

Right, I always forget about the "first party" option. Then I think we are covered 👍🏼

**Comment by robertknight** [comment]
This is now deployed.
