### ISSUE TITLE
Ensure that existing kb articles for keyboard shortcuts document everything we've implemented.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#5825]
This one:

https://web.hypothes.is/help/keyboard-shortcuts-for-hypothesis

And this one: 

https://web.hypothes.is/help/creating-annotations-using-only-your-keyboard/

**Comment by robertknight** [comment]
Related to this, several large web apps have a convenient shortcut guide which you can trigger with <kbd>Shift+?</kbd>. I think it would be great to have such a facility in our own apps as a standard feature:

<img width="1333" alt="YouTube shortcut guide" src="https://github.com/hypothesis/client/assets/2458/acd3095c-d70a-49e0-a7ee-e67d8e092d07">

**Comment by acelaya** [comment]
The only shortcut I have found which is not explicitly documented is <kbd>Escape</kbd> to close the adder when it's open.

**Comment by dwhly** [comment]
> The only shortcut I have found which is not explicitly documented is Escape to close the adder when it's open.

The adder or the sidebar?

**Comment by acelaya** [comment]
> The adder or the sidebar?

The adder.

**Comment by mkdir-washington-edu** [comment]
Added the Escape option to the shortcuts article, and added a note in the annotations article pointing to the shortcuts article so users can find the additional shortcuts.
