### ISSUE TITLE
Extra full stop in onboarding card

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#586]
The first sentence ends in a full stop but the other two don't. IIRC the design did not have a full stop. @sheetaluk 
![screenshot from 2017-11-17 17-37-21](https://user-images.githubusercontent.com/22498/32960799-2db0a2d4-cbbe-11e7-8413-f2e3223c1624.png)

**Comment by sheetaluk** [comment]
The design has a full stop after the first bullet point:

https://user-images.githubusercontent.com/5212631/31545299-a288f80e-b016-11e7-819e-6325f83b681e.png
