### ISSUE TITLE
"New note" button text should be bold

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#588]
The text inside this button:

![screenshot from 2017-11-17 17-42-19](https://user-images.githubusercontent.com/22498/32960980-c37a4b4e-cbbe-11e7-96b2-da8ea7f170db.png)

is bold in [the design](https://user-images.githubusercontent.com/5212631/31545299-a288f80e-b016-11e7-819e-6325f83b681e.png)

**Comment by lyzadanger** [comment]
This button has been converted to a "standard" client app button, and that involves bold text, so this one's no longer applicable.
