### ISSUE TITLE
"New note" buttons are different sizes

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#589]
The two **New note** buttons are different sizes (looks like both different font size and different padding):

![screenshot from 2017-11-17 17-43-44](https://user-images.githubusercontent.com/22498/32961047-f7f20c90-cbbe-11e7-99c8-30170af8d8a4.png)

**Comment by robertknight** [comment]
IMO the buttons being different sizes isn't a problem - it has clearly been adjusted in the tutorial dialog to fit in with the surrounding text. However the padding is obviously wrong in Firefox:

<img width="447" alt="screenshot 2017-11-30 10 51 43" src="https://user-images.githubusercontent.com/2458/33427848-b1b9b1a6-d5be-11e7-8024-ff42b263d62f.png">

In Safari & Chrome it looks OK, although the padding above the text still doesn't quite match:

<img width="477" alt="screenshot 2017-11-30 11 08 14" src="https://user-images.githubusercontent.com/2458/33427884-cdf0a50a-d5be-11e7-8925-2dc806a2dca2.png">

**Comment by seanh** [comment]
Sorry, I think I was unclear in my issue description - it's not my personal opinion that the buttons should be the same size because they should be the same size, what I meant was that the font weight and padding on the new note button is different than in the design.

I'm pretty sure the designs had the bold font and extra padding on the real new note button, the same as on the fake new note button in the tutorial card.

Also, this design (bold font and extra padding) would match other buttons in the client, for example here's the post button:

![screenshot from 2017-11-30 13-02-56](https://user-images.githubusercontent.com/22498/33432227-1661f48c-d5cf-11e7-8f45-4e88a0a4b7df.png)

so my guess is that the new note button should be the same.

@dawariley Can you clarify the design? Here's how the new note button currently looks on production, it's the same in either Firefox or Chrome:

![screenshot from 2017-11-30 13-02-36](https://user-images.githubusercontent.com/22498/33432246-2fb10702-d5cf-11e7-8a0f-287688b82e62.png)

**Comment by lyzadanger** [comment]
The padding and layout of this button was made consistent with other application buttons during the Angular => preact migration. Yay!
