### ISSUE TITLE
Double-clicking to select a word in a PDF and then annotating annotates nothing

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#59]
Here I double-click on the word "annotating". The highlight is far too small for some reason. Then when I annotate, it creates an annotation with no target text.

![untitled screencast - edited 31](https://cloud.githubusercontent.com/assets/22498/17252699/8c5da420-55a5-11e6-84be-bd475c32da98.gif)

(This looks like it might be a bug with selecting text in PDF.js.)

**Comment by ajpeddakotla** [comment]
Updated PDFjs last year - no longer reproducible.
