### ISSUE TITLE
Annotate icon is smaller than in design

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#590]
The blue annotate icon isn't the same size as the one in [the design](https://user-images.githubusercontent.com/5212631/31545299-a288f80e-b016-11e7-819e-6325f83b681e.png):

![screenshot from 2017-11-17 17-45-43](https://user-images.githubusercontent.com/22498/32961123-3c3ce492-cbbf-11e7-89c9-02aa820c9362.png)

**Comment by lyzadanger** [comment]
I believe this is a screen shot from the tutorial panel, perhaps? In any case, there's no match for the string "Start annotating" in our current codebase, so I believe this design nit is out of date.
