### ISSUE TITLE
Re-Scoping VitalSource Annotations

### ISSUE THREAD

**Issue by acelaya** [hypothesis/client#5915]
PRD: https://docs.google.com/document/d/1nK9T5IzpHh_n64YVCUZVHHqWw-SxBDuCuYDM5FtTFvQ/edit

Designs: https://www.figma.com/file/QxZ1x1Cv8hDzd5iK0ulISs/Hypothesis---VitalSource-Page-Range-Selection?type=design&mode=design

**Comment by robertknight** [comment]
Closed by https://github.com/hypothesis/lms/pull/6111.
