### ISSUE TITLE
Annotations on pdfs generated from google docs are shifted to the right

### ISSUE THREAD

**Issue by nick-benoit14** [hypothesis/client#596]
### Steps to reproduce
1. Create a google drive document
2. Allow file to be sharable to anyone with the link
3. Make note of your document id 
4. Go to 
https://via.hypothes.is/https://docs.google.com/document/d/<your_document_id>/export?format=pdf
5. Make an annotation somewhere in the middle of the file (not on the first line), note that it is shifted to the right by some amount. 

### Expected behaviour
Highlights and annotations should remain consistent with what the user initially highlighted.  

### Actual behaviour
Highlights and annotations are shifted to the right when the user clicks the 'Highlight' or 'Annotate' button.

### Browser/system information
Chrome Version 62.0.3202.94 (Official Build) (64-bit)
Mac OSX High Sierra 10.13.1

### Additional details
The amount the highlight is shifted to the right appear to be influenced by its position in the file. I.e if you annotate the first word, it is not shifted at all; if you highlight a word in the last line of the file, it is shifted to the right a large amount. 

I saw this same result when I tested via the following ways: 
  * The export url listed above
  * Exporting a doc as a pdf, then uploading to drive as a pdf and accessing `https://drive.google.com/uc?id=<your_file_id>&authuser=0&export=download`
  * Exporting doc as pdf and hosting at public url to test with via

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/product-backlog/issues/740, where PDF issues have been compiled.
