### ISSUE TITLE
"New note" button positioning is wrong if page has no notes

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#599]
The "New note" button positioning is wrong if the page has no notes and so the "blank state" content is being shown:

<img width="490" alt="screenshot 2017-11-21 13 53 18" src="https://user-images.githubusercontent.com/2458/33076047-6f2658c8-cec3-11e7-952c-061c10a83588.png">

Client configuration:

```js
window.hypothesisConfig = function () {
    return {
      disableToolbarCloseBtn:false,
      disableToolbarMinimizeBtn: true,
      disableToolbarHighlightsBtn: true,
      disableToolbarNewNoteBtn: true,
      disableBucketBar: true,
      enableSidebarDropShadow: true,
      enableExperimentalNewNoteButton: true,
      enableCleanOnboardingTheme: true,
      theme: 'clean',
      usernameUrl: 'http://www.elife.org/user/',
      branding: {
        // Match the body's background color.
        appBackgroundColor: 'white',

        // Match the header's background and foreground colors.
        accentColor: '#0288d1',
        ctaBackgroundColor: '#0288d1',
        ctaTextColor: 'white',

        // Match the body text of the article.
        annotationFontFamily: 'serif',
        selectionFontFamily: 'serif',
      },
      showHighlights: 'whenSidebarOpen',
    };
  };
```

**Comment by robertknight** [comment]
On further testing, this appears to be a Safari-specific issue. In Safari 11.0.1 I reproduced while reviewing #611 as follows:

1. Visit a page using the new-look "New Note" button, using a user who has not dismissed the sidebar tutorial
2. Switch to the "Page Notes" tab
3. Switch back to the "Annotations" tab
4. Switch back to the "Page Notes" tab

End result:

<img width="469" alt="screenshot 2017-11-30 10 47 40" src="https://user-images.githubusercontent.com/2458/33427605-befefbce-d5bd-11e7-88c0-d99dba7fa91e.png">

The button's position appears as expected in Chrome 64 (dev) and Firefox 59 (Nightly).

**Comment by seanh** [comment]
@robertknight Did this get fixed? I'm not currently seeing it on production eLife

**Comment by ajpeddakotla** [comment]
This issue has been fixed.
