### ISSUE TITLE
Double-clicking to select a word in a PDF does not trigger adder

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#60]
Here I double-click on the word "annotating". The highlight is far too small for some reason. The adder popup does not appear.

![untitled screencast 29](https://cloud.githubusercontent.com/assets/22498/17252807/f19c61aa-55a5-11e6-8ac6-ef6761a730c7.gif)

**Comment by ajpeddakotla** [comment]
Updated PDFjs last year - no longer reproducible.
