### ISSUE TITLE
Make real time updates easier to see

### ISSUE THREAD

**Issue by nairiboo** [hypothesis/client#6007]
Real time updates of annotations, no need to select "download new annotations" button.

**Comment by robertknight** [comment]
> Some users have complained that the button at the top of the sidebar is not obvious enough

A possible solution would be to show a badge with a count of updates. This would make the existence of updates more obvious without the downside of interrupting the user while they are reading the sidebar.

**Comment by robertknight** [comment]
This was solved in https://github.com/hypothesis/client/issues/6255.
