### ISSUE TITLE
Annotating last words on page on PDF orphans the editor.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#608]
### Steps to reproduce
1. Go to https://steem.io/SteemWhitePaper.pdf
2. Launch chrome extension
3. Select the last words on any page, make sure at least one space in between words is included.  For instance, annotate "August 2017" on page 1.
4. Click to launch editor.

### Expected behaviour
Editor should open and stay opened in annotations tab.

### Actual behaviour
Editor opens briefly and then shifts to orphans tab.

### Browser/system information
Chrome extension.

### Additional details
This may be particular to PDFs where our current PDFjs cannot adequately distinguish the spaces between letters.  On PDFs which PDFjs gets the spacing right, this problem doesn't happen.

**Comment by dwhly** [comment]
Fixing this may require addressing https://github.com/hypothesis/product-backlog/issues/366

**Comment by judell** [comment]
Unchanged in FF 65 / PDFjs 2

**Comment by robertknight** [comment]
I am no longer able to reproduce the issue. I would guess this was fixed with the overhaul of quote-based annotation anchoring last year.
