### ISSUE TITLE
Accessibility issues from Jan 2024 review

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#6151]
This issue covers resolving accessibility issues identified in the [January 2024 review by OCAD](https://docs.google.com/document/d/1YdYr5jIsKEm4CkOQF9un3LUc-A8xLtwFP5kWbNpqYOM/edit#heading=h.gjdgxs) that affect the client.

- [x] #6158
- [x] #6163
- [x] #6166
- [x] #6179
- [ ] #6185
- [x] #6188
- [ ] #6193
- [ ] #6194

**Comment by acelaya** [comment]
The main tasks have been completed, and there are individual issues for the pending tasks, so I'm going to go ahead and close htis.
