### ISSUE TITLE
Tags on publisher group annotations link to broken activity pages

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#616]
Publisher group annotaitons don't work on activity pages (lots of problems). These tags on the annotation cards in the sidebar shouldn't link to activity pages for publisher group annotations:

![screenshot from 2017-11-30 12-50-16](https://user-images.githubusercontent.com/22498/33431699-40abbdc4-d5cd-11e7-8f8c-c2e0b66585cd.png)

**Comment by dwhly** [comment]
> for publisher group annotations

Or perhaps "for 3rd party namespaces".  Publisher groups that are in the H namespace presumably wouldn't be a problem.

**Comment by seanh** [comment]
We don't have any publisher groups that are in the h namespace. I would like to dispel any notion that such things exist!

**Comment by robertknight** [comment]
> We don't have any publisher groups that are in the h namespace. 

I think we should stop calling what we've given eLife "publisher groups" 😛, because that is going to get really confusing soon!

What you mean here is "groups associated with third-party accounts", which admittedly is not as succinct.

**Comment by seanh** [comment]
I _think_ what Dan (and others outside of the product team) mean by _publisher group_ is simply a group that is nominated, by a publisher's website, as sort of a "pinned group" whenever the client is launched on that website. What this means currently is that eLife's publisher group is the _only_ group that's available in the client on eLife's site, but in the future when other groups (e.g. first-party groups) are also available on the eLife site their publisher group will just be the one that's pinned to the top of the groups menu / highlighted / featured / promoted in some way as the "publisher's official group".

So this concept of a publisher group is distinct from the concept of a third-party group.

But of course right now we only have one kind of publisher group - the third-party publisher group with third-party account integration that we created for eLife.

What I'd like to dispel is any notion that publisher groups beyond this limited case is a feature that currently exists in Hypothesis. I'm sure that all sorts of things will come up, when we try to implement a publisher group that is a first-party group, or that allows people to join the group without having to be logged in to an account on the publisher's site, etc.

These are all features we can have, but will require thought and work.
