### ISSUE TITLE
Annotate/Highlight dialogue box detached from selected text

### ISSUE THREAD

**Issue by dhimmel** [hypothesis/client#619]
We're interested in using the hypothesis javascript client for our Manubot HTML pages (https://github.com/greenelab/manubot-rootstock/issues/90). We want to apply Hypothesis to pages like https://greenelab.github.io/manubot-rootstock/.

However, when we add Hypothesis like https://via.hypothes.is/https://greenelab.github.io/manubot-rootstock/, there's an issue with the dialogue box placement:

![hypothesis](https://user-images.githubusercontent.com/1117703/33519575-6bfdf19e-d777-11e7-9827-9c544a375c66.png)

The annotation options appear far away from the actual point of highlighting. Not sure whether this is an issue with [our CSS](https://github.com/greenelab/manubot-rootstock/blob/fffae41daf5ec4a7d607ab051de45f4ecd05ce4c/webpage/github-pandoc.css) or a Hypothesis client issue. Hat tip to @RaoOfPhysics for bringing this issue to our attention.

**Comment by dsiddy** [comment]
@dhimmel, thanks for the heads-up. When I set `margin-left: 0` on your website's `html` element, the Hypothesis adder appears in the correct position, so I'm guessing there's something similar to #487 at work here. (The relevant file, for troubleshooting's sake, is [src/annotator/adder.js](https://github.com/hypothesis/client/blob/master/src/annotator/adder.js).)

**Comment by dhimmel** [comment]
Thanks @dsiddy. I'm interested in the potential fix you've discovered.

Our CSS currently [includes](https://github.com/greenelab/manubot-rootstock/blob/fffae41daf5ec4a7d607ab051de45f4ecd05ce4c/webpage/github-pandoc.css#L82-L88).

```css
/***Page margins when printing***/
@page { 
    margin-top: 19mm;
    margin-bottom: 16mm;
    margin-left: 0mm;
    margin-right: 0mm;
}
```

However, the `@page` presumably only affects the printed document. Do you have a suggestion for how we would change our CSS for Hypothesis to work?

**Comment by dsiddy** [comment]
Sorry for the belated reply, @dhimmel. I just accepted your invitation and submitted a pull request (greenelab/manubot-rootstock#95) that should resolve the issue.

**Comment by dhimmel** [comment]
Closed in https://github.com/greenelab/manubot-rootstock/commit/d2097311f451464f245b287adf799796267c32f5. Thanks @dsiddy for the fix!
