### ISSUE TITLE
EPUB (Readium) issue with fuzzy matching for anchors

### ISSUE THREAD

**Issue by jccr** [hypothesis/client#631]
Please read the details here: https://github.com/readium/readium-js-viewer/issues/679

### Steps to reproduce
1. Navigate to a Readium demo with Hypothesis, quick link for this here: https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&goto=epubcfi(/6/20!/4/2%5Bbuilding_a_better_epub%5D/2/1:0)
2. Open the H sidebar and ensure you are logged in to hypothes.is
3. Switch to a private group or be prepared to make a private annotation
3. In the EPUB viewport with the content, highlight the chapter header text "Building a Better EPUB".
4. Open Readium's table of contents view (hot key: t).
5. Note that there's an annotation highlight there that matches the chapter header made in the previous step.

### Expected behaviour
The annotation should only exist in the intended document, which in this case is in the EPUB content, not at the hosting document with the ToC view.

### Actual behaviour
There's a "duplicate" highlight that appears in a different, unintended location.

### Browser/system information
Chrome 62, macOS 10.13.1

### Additional details
I believe this is happening due to an aspect of the multi-frame support in the H client. The client is working to match annotations that come through at a document scope and maybe the top-level frame is at a scope that it gets all the sub-document's annotations too. Fuzzy, eager or fall-back anchoring is probably being triggered at the top level frame and it's causing this issue.

**Comment by robertknight** [comment]
There is definitely a conceptual problem at the moment that if multiple frames are connected to the sidebar then the client will fetch annotations for all frames and try to broadcast every annotation to every frame (see `src/sidebar/frame-sync.js`). One definite result of this is that annotations can non-deterministically fail to anchor or mis-anchor. @judell encountered this recently in the [context of OSF](https://docs.google.com/document/d/1lMKiSehHt_WEj3K87V6Do-ue5t5x6mVL_Z7Lib2IlMk).

One obvious solution here would be to tag each annotation with the frame it "belongs" to and then only try to anchor in the appropriate frames.

**Comment by ajpeddakotla** [comment]
Scope: Medium complexity.

**Comment by robertknight** [comment]
This looks like another instance of the problem in https://github.com/hypothesis/client/issues/688.

**Comment by robertknight** [comment]
> There is definitely a conceptual problem at the moment that if multiple frames are connected to the sidebar then the client will fetch annotations for all frames and try to broadcast every annotation to every frame (see src/sidebar/frame-sync.js).

This has now been partially addressed. An annotation is now only ever sent to one specific frame, and the frame is chosen deterministically. There is still an issue that annotations will only be sent to sub-frames if the annotation's URL exactly matches the sub-frame's URL. See https://github.com/hypothesis/client/blob/25b22fc6c4b1b1de795ecf69256bc2956d2e9951/src/sidebar/services/frame-sync.js#L52.
