### ISSUE TITLE
Scroll position of the main page not being maintained after adding an annotation

### ISSUE THREAD

**Issue by saurabhnanda** [hypothesis/client#637]
### Steps to reproduce
1. Visit http://www.vacationlabs.com/haskell/prelude.html
2. Add an annotation anywhere and "Post to public"

### Expected behaviour
Scroll position should be maintained.

### Actual behaviour
Webpage scrolls to either the very top, or some other random position. Basically the scroll position is not maintained.

### Browser/system information
https://whatismybrowser.com/w/NKH36S8

**Comment by robertknight** [comment]
Neither http://www.vacationlabs.com/haskell/prelude.html nor 
https://whatismybrowser.com/w/NKH36S8 are accessible any more. I wasn't able to reproduce the issue on a different page either. Please re-open with details of your browser if you are able to reproduce using the current version of Hypothesis.
