### ISSUE TITLE
Window target not set for HTML links in annotation markdown

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#64]
### Steps to reproduce
1. Create an annotation with the following markdown content: `Hello <a href="http://www.google.com">Google</a>`
2. Click the link in the Chrome extension
### Expected behaviour

The link should open in a top-level tab, preferably a new tab rather than the current one so it doesn't lose the user's position in the sidebar
### Actual behaviour

The content of the sidebar disappears and the console displays an error message either about failing to load mixed content (if the link is HTTP and the current URL is HTTPS) or same-origin restrictions for iframes (if the link's protocol is HTTPS)
### Browser/system information

Tested in Chrome v52

**Comment by nickstenning** [comment]
I don't think this replicates as you've described it. For me creating a plain link such as `<a href="http://www.google.com">Google</a>` works fine.

But the minute you add something weird to the anchor tag, it breaks:

```
<a href="http://www.google.com">Google</a> works
<a  href="http://www.google.com">Google</a> breaks (two spaces)
<a onclick="" href="http://www.google.com">Google</a> breaks
```

**Comment by robertknight** [comment]
All three of the test cases in the previous example work as expected in the current version of the code.
