### ISSUE TITLE
Adder has changed to two buttons much smaller

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#641]
### Steps to reproduce
1. Launch H, select text

### Expected behaviour
Normal adder should show

### Actual behaviour
Strange adder appears.  Only apparently in Chrome, FF still normal.

### Browser/system information
Chrome extension, 1.60

![screen shot 2017-12-19 at 10 28 01 am](https://user-images.githubusercontent.com/1413074/34172794-0fd4a19a-e4a8-11e7-8189-c947d0e38dff.png)

**Comment by robertknight** [comment]
https://github.com/hypothesis/client/blob/02a436773f73607ee8c8080f47af900ae1c7149d/src/annotator/adder.js#L93 needs updating following the CSS bundle renaming. Whether it happens will depend on the browser’s Shadow DOM support.

**Comment by robertknight** [comment]
Fixed by https://github.com/hypothesis/client/pull/642
