### ISSUE TITLE
Log in link on unavailable annotation message does nothing

### ISSUE THREAD

**Issue by fatbusinessman** [hypothesis/client#643]
### Steps to reproduce
1. In a logged-out client, go to an extension that’s not publicly viewable
2. Click the “log in” link in the “This annotation is not available” prompt

![annotation unavailability message](https://user-images.githubusercontent.com/32775/34576615-64c253ca-f176-11e7-9f6d-af0e2767c8ad.png)

### Expected behaviour

The client should log in automatically, or bring up a popup window to let me log in.

### Actual behaviour

As far as I can tell, nothing happens. I don’t see any JavaScript errors, or any notifications of blocked popups.

### Browser/system information

Chrome, macOS, browser extension 1.61.0.

### Additional details

Clicking the “Log in” link at the top of the sidebar still works as expected; it’s only the link inside the unavailability message that doesn’t work. From a look into the code, it seems to call `vm.login()` rather than the `vm.onLogin()` that the “Log in” link at the top calls.

**Comment by dwhly** [comment]
We might consider removing the link from the alert message, since it will require synchronizing on an ongoing basis, and the login feature is up top.

**Comment by robertknight** [comment]
Fixed in 1a33558515a3a010e2f4ba8e2b09d62bb3cef6b9.
