### ISSUE TITLE
Show actual date vs just month of group creation

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#644]
Right now we show:  January, 2018.
Instead, lets show:  January 3, 2018.

![screen shot 2018-01-05 at 1 59 47 pm](https://user-images.githubusercontent.com/1413074/34630513-4184f790-f221-11e7-8882-6c22e4281bdc.png)

**Comment by dawariley** [comment]
Related issue: Activity pages revamp work currently being undertaken with respect to the introduction of new group types. https://github.com/hypothesis/product-backlog/issues/422

**Comment by hmstepanek** [comment]
I spoke with @segdeha about this in my 1:1 today. I've briefly looked at this enough to know that while you could make a simple version that does this in a hacky way, what we prob want here is to make a location service (we don't have anything like this right now). So this is a little larger than we originally thought and should be prioritized with @ajpeddakotla.

**Comment by ajpeddakotla** [comment]
@hmstepanek we should just add the date in a the US format `July 4, 2018`, and create a seperate card to build a location service later so that we can display in multiple date formats dependent on where the user is located.

**Comment by dawariley** [comment]
Yes absolutely. When we spoke I mentioned the date locale but never saw this as a deal breaker. US date format is totally fine for v1.

**Comment by ajpeddakotla** [comment]
Closing this as it is completed.
