### ISSUE TITLE
Possible bug in annotator/highlighter/dom-wrap-highlighter

### ISSUE THREAD

**Issue by jc275** [hypothesis/client#647]
https://github.com/hypothesis/client/blob/1dc20a2ce4773f3cfbdc467232e56135408691b9/src/annotator/highlighter/dom-wrap-highlighter/index.coffee#L22

Should this end with `i.nodeValue` instead of `@nodeValue` ?

**Comment by lyzadanger** [comment]
This code no longer exists as this part of the codebase has been migrated to JavaScript and refactored.
