### ISSUE TITLE
js error when activating client on wikipedia

### ISSUE THREAD

**Issue by judell** [hypothesis/client#649]
Visit a Wikipedia page, say https://en.wikipedia.org/wiki/Tubbs_Fire, activate the extension (or use via), check the console:

![image](https://user-images.githubusercontent.com/46509/35021638-9a27c760-fae6-11e7-9ce0-dee30ebb3d62.png)

In the debugger, we see that it's where wikipedia's JS code handles our message, with `data: "__cross_frame_dhcp_offer"`

![image](https://user-images.githubusercontent.com/46509/35021706-ee53c794-fae6-11e7-9a38-d41aa6ab3adc.png)

Is this the fault of the Wikipedia code for making assumptions about the event data?

**Comment by robertknight** [comment]
I can reproduce, but as far as I can see it doesn't break client functionality. Unfortunately as long as the sidebar communicates with the host frame using `window.postMessage`, we can't easily avoid an event listener on the host page trying to handle the message.

> Is this the fault of the Wikipedia code for making assumptions about the event data?

Basically, yes. The client needs to work with pages that have code that is not ah, robust. As long as this isn't breaking any pages we care about, I'm going to close for now.
