### ISSUE TITLE
Login link seems dead in Firefox when the login popup is open but below other windows 

### ISSUE THREAD

**Issue by ymph** [hypothesis/client#650]
### Steps to reproduce
1. Start as completely logged out
2. Open a page to annotate with the client (example : https://via.hypothes.is/https://en.wikipedia.org/wiki/Hypothes.is)
3. Click on the "Log in" link in the client. This open the login popup window
4. Without closing the popup, "push" it behind some browser windows, For example by clicking on "Sign up" in the popup.
5. Go back to the first opened window/tab with the client. The click on "Log in" seems dead.

### Expected behaviour
All click on the "Log in" link should show the login popup each time it is clicked.

### Actual behaviour
When already opened, the login popup window does not receive focus and stay hidden, in the back, behind the main window. The "Log in" link appears as effectively dead. If the user bring back the login popup, it works normally. This can be very disturbing, especially for new users that do not know what to expect from the application.

### Browser/system information
Firefox 56.0 / Windows
Firefox 58.0b16 / OSX
Edge 41.16299.15.0

### Additional details
This does not seems to affect Chrome or Safari

**Comment by robertknight** [comment]
I just tested this again in the current versions of Safari, Chrome and Firefox. The issue appears to be resolved in Firefox now. If you click the "Log in" link when the popup window has been moved to the background then it gets moved to the foreground.
