### ISSUE TITLE
Boot script does not read `assetRoot` and `sidebarAppUrl` settings from `window.hypothesisConfig`

### ISSUE THREAD

**Issue by patmigliaccio** [hypothesis/client#652]
### Steps to reproduce
1. Add `window.hypothesisConfig` function that returns _custom `assetRoot` and `sidebarAppUrl`_ properties. (_Edited_)
2. Check to see if these properties are applied on boot.

### Expected behaviour
`boot/index.js` should merge properties from `window.hypothesisConfig()` in addition to those added in the `script.js-hypothesis-config` tag; allowing for `assetRoot` and `sidebarAppUrl` to be set from the `window` property.

### Actual behaviour
Properties are never added before the client is instantiated.

### Browser/system information
```
User-Agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
```

**Comment by patmigliaccio** [comment]
#653

**Comment by robertknight** [comment]
Can you please describe how you were testing this in the first place? Reading of configuration from the `hypothesisConfig` function result is working as expected using this test case: https://jsfiddle.net/hjuzu2yu/

**Comment by robertknight** [comment]
Oh, ignore my previous comment, your issue is with the `assetRoot` and `sidebarAppUrl` properties specifically which are handled in `boot/index.js` unlike the other config settings.

**Comment by patmigliaccio** [comment]
Correct - I should've made the title a bit clearer.

**Comment by patmigliaccio** [comment]
Noticing now that there is a `configFuncSettingsFrom(_window)` method in `./src/annotator/config/config-func-settings-from.js`, presuming these should be consolidated.

**Comment by robertknight** [comment]
Hi @patmigliaccio - Out of interest, can you explain what you were trying to do when you encountered the issue? The `sidebarAppUrl` and `assetRoot` variables primarily exist for the benefit of the browser extensions which need to make the client loads assets bundled with the extension, in order to benefit from the CSP bypass that assets bundled with extensions are given.

**Comment by patmigliaccio** [comment]
@robertknight - We wanted to be able load the scripts from our end instead of the Hypothesis CDN as some of the functionality we are looking to get out of the client currently isn't available (hypothesis/product-backlog#434). Since we are dynamically injecting the embed script into our application, we are setting the `sidebarAppUrl` and `assetRoot` properties via the `window.hypothesisConfig` function, instead of an additional DOM element.

**Comment by robertknight** [comment]
Are you running your own instance of the "h" service or wanting to use the production "h" service?

**Comment by patmigliaccio** [comment]
Currently running our own instance.

**Comment by robertknight** [comment]
If you are using a forked client and your own instance of h then you probably want to use your own build of the boot script as well to avoid breakage if change the list of assets that the boot script references. For example, we recently renamed some of the JS bundles.

I think the proposed change here would make sense regardless for consistency, but I'm just making sure that you don't rely on using the boot scripts hosted at cdn.hypothes.is.

**Comment by patmigliaccio** [comment]
Okay yes, we are currently using our own build of `boot.js` when injecting the script tag as well as a modified version of `app.html` which utilizes this same `boot.js`. Is this what you are describing?

**Comment by robertknight** [comment]
Yes, exactly.

**Comment by KrishnaPG** [comment]
Facing same problem, when trying to use custom built client files. One major confusion is: when the client is built, I do not see `embed.js` which the documentation says should be inserted into the html page. Also do not see `app.html` anywhere in the client build folder. Wondering if I am missing something.

Or, can one use any `app.html` as long as it contains something like below:
````
    <hypothesis-app></hypothesis-app>  
  
    <script src="/embed.js"></script>
````

**Comment by patmigliaccio** [comment]
@KrishnaPG I've been working with a modified version of `app.html` from [hypothesis/browser-extension](https://github.com/hypothesis/browser-extension/blob/master/src/client/app.html.mustache).

Making sure to include the build version `boot.js` instead of `embed.js` and including the appropriate `js-hypothesis-config` settings.

**Comment by robertknight** [comment]
@KrishnaPG - Sorry, I know this is confusing! `app.html` is currently part of our [web service](https://github.com/hypothesis/h/blob/master/h/templates/app.html.jinja2). @patmigliaccio 's advice to use a modified version of the one in the browser-extension repo should work fine.

`https://hypothes.is/embed.js` is a dummy URL which redirects to a copy of the "boot.js" script that we host on `https://cdn.hypothes.is`.

The location of "app.html" and assets can be overridden using a JSON `<script>` tag. If you activate the Chrome extension on a page you'll see that this is how it configures these parameters. This PR is just about resolving an inconsistency that we only look for these particular settings in "js-hypothesis-config" tags and not `window.hypothesisConfig`.

**Comment by robertknight** [comment]
The client currently only reads these two settings from `js-hypothesis-config` JSON script tags when it boots. This simplifies the boot script and avoids needing to add error paths that we might need if also reading from `window.hypothesisConfig`. Since we don't have a definite use case for this yet, I'm going to close it for now. 

As I noted above in https://github.com/hypothesis/client/issues/652#issuecomment-360234375, custom forks of the client should not try to use the boot script from our version of the client.
