### ISSUE TITLE
build not working on Windows

### ISSUE THREAD

**Issue by KrishnaPG** [hypothesis/client#659]
### Steps to reproduce
1. Clone the project onto a Windows machine
2. run `yarn run build` 

### Expected behaviour
Build should happen

### Actual behaviour
Errors out as below:
````
'NODE_ENV' is not recognized as an internal or external command
````

### Browser/system information
Windows OS

### Additional details
If you set as below, it worked:
````
"build": "SET NODE_ENV=production && gulp build"
````
The build works fine with the above. However, it still does not produce the `app.html` output. It asks to use the external `app.html` as shown in the below output on the build.
````
[10:48:12] Finished 'build' after 1.4 ms
[10:48:12] Sidebar app URL: https://hypothes.is/app.html
[10:48:12] Client asset root URL: http://localhost:3001/hypothesis/1.64.0/
Done in 14.07s.
````

**Comment by robertknight** [comment]
> However, it still does not produce the app.html output

"app.html" is not currently part of the client build. It is part of the "h" service.

We'll accept PRs that make the client build on Windows systems providing the build still works on Mac & Linux. It is unlikely that we'll get around to it ourselves since none of the developers at Hypothesis use Windows as far as I know.

**Comment by robertknight** [comment]
I merged a PR to address this, but I don't have a Windows system to test on at the moment and the other devs at Hypothesis are all using either macOS or Linux. I'm going to close this as fixed. If there are still issues please feel free to file a new report.
