### ISSUE TITLE
Sidebar does not scroll to new annotation when clicking "New note" button

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#660]
### Steps to reproduce
1. Go to https://elifesciences.org/articles/09560 and login. You will need to register an ORCID ID if you do not already have one.
2. Click "Annotations" at the top of the article page to open the sidebar.
3. Go to the "Page notes" tab and click the "New note" button at the top

<img width="986" alt="Article page with new note button" src="https://user-images.githubusercontent.com/2458/35620928-95222bf8-067a-11e8-8c5b-19fe7ffb1250.png">

### Expected behaviour
The sidebar should scroll so that the new annotation, including its comment input field and "Post to eLIFE" button, are clearly visible.

### Actual behaviour
The sidebar does not scroll, so it is not clear to the user what they should do next after clicking the "New note" button.

### Browser/system information
Tested in Chrome 65, Firefox 58

**Comment by xolotl** [comment]
Probably unrelated, but I’ve noticed that because eLife collapses sections of HTML on its page, when clicking on an annotation, the sidebar’s scrolling doesn’t open and reveal associated highlights. Possibly more of an issue for elife.
