### ISSUE TITLE
pdf misanchoring

### ISSUE THREAD

**Issue by judell** [hypothesis/client#661]
## Test document

http://jonudell.net/h/osftest.pdf

## Specs

Windows 10, Chrome w/current H extension

## Narrative 

Create an annotation on page 1, and an annotation on page 95. Click them alternately, expecting to scroll to page 1 or page 95 respectively.

## Behavior

A click on the page 95 card sometimes scrolls the doc to the end, but sometimes scrolls to a similar instance of the target phrase on page 95 and a spurious highlight appears.

## Screencast

http://jonudell.net/h/pdf-misanchoring-scenario.mp4

## Notes

- I began the screencast expecting to record an example of the page 95 annotation orphaning intermittently, but was unable to catch that on camera.

- It was often necessary to click the page 1 annotation twice to get the doc scrolled to page 1.

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/product-backlog/issues/740, where PDF issues have been compiled.
