### ISSUE TITLE
Client fetches groups list multiple times on startup

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#678]
### Steps to reproduce
1. Go to a page that embeds the current client (>= v1.7.0) and inspect network requests it makes

### Expected behaviour
Client should fetch groups endpoint (`/api/groups`) once

### Actual behaviour
Client fetches groups endpoint multiple times.

### Browser
You can clearly see this in Chrome. The duplicate requests are not visible in Safari.

**Comment by lyzadanger** [comment]
@robertknight I _believe_ the current set of API requests fired on app startup are as desired now, but I want to make certain. There are three, currently:

1. Fetch profile
1. Fetch user's groups
1. Fetch appropriate annotations

I think that we've resolved the multiple groups fetching requests, but wanted to check with you before I close this out.

**Comment by lyzadanger** [comment]
@robertknight Ping

**Comment by robertknight** [comment]
This has been fixed. We now make only one request to `/api/profile/groups` and one request to `/api/groups` when the client loads.
