### ISSUE TITLE
use bouncer for the page-level share link

### ISSUE THREAD

**Issue by judell** [hypothesis/client#680]
The page-level share link (Share this Page) still uses via, e.g. `https://via.hypothes.is/https://www.theguardian.com/technology/2010/jun/20/internet-everything-need-to-know` 

If you're an extension user, that's suboptimal, you would rather use the extension.

We now have this bouncer syntax:  `hyp.is/go?url=https://www.theguardian.com/technology/2010/jun/20/internet-everything-need-to-know` which resolves to the extension if available, or falls back to via otherwise.

I think we can now use the bouncer link in the Share this Page, so instead of this:

![image](https://user-images.githubusercontent.com/46509/36563933-78277226-17d0-11e8-89c4-192f670a7a80.png)

it would be like this:

![image](https://user-images.githubusercontent.com/46509/36563678-c5324786-17cf-11e8-96ba-43ed8766f22d.png)

**Comment by judell** [comment]
Here's a proposed solution:

https://github.com/hypothesis/client/compare/master...judell:master

Some questions about this:

1. What is the purpose of https://github.com/hypothesis/client/blob/master/src/sidebar/components/share-dialog.js#L27, and when would there be 0 frames at https://github.com/hypothesis/client/blob/master/src/sidebar/components/share-dialog.js#L10?

2. Why does bouncer append "#annotations:query" when there are no query params? Currently, and unchanged with this proposed fix, the redirections are like so:

From: https://hyp.is/go?url=https://example.com

To (extension):  http://example.com/#annotations:query:

To (via): https://via.hypothes.is/https://example.com#annotations:query:

If there are query params, bouncer applies them here: https://github.com/hypothesis/bouncer/blob/70ec9449de619522fcae47a50cb266ae6692a527/bouncer/views.py#L136

But when there are none, would it make sense to suppress the "#annotations:query" fragment?

**Comment by dwhly-proj** [comment]
This has been implemented: https://github.com/hypothesis/client/pull/748
