### ISSUE TITLE
replying to an annotation in search results hides the reply

### ISSUE THREAD

**Issue by tgbugs** [hypothesis/client#690]
### Steps to reproduce
1. Search for a tag
2. Reply to one of the resulting annotations

### Expected behaviour
The new reply text box appears and my cursor is placed in the edit field as it does when I am not in search results.

### Actual behaviour
The new reply annotation will be hidden behind
```
Hide replies (1)
View one more in conversation 
```
and I will have to click once to show it and then click again in the edit box to edit it.

### Browser/system information
Chrome and Firefox on linux.

### Additional details
It seems that the default behavior is to only show annotations and replies that match the search result (e.g. an annotation and a reply with the same tag will both appear expanded in the search results). I suspect that the new annotation is being identified as having no tags and therefore not matching the search results and therefore being hidden.

**Comment by lyzadanger** [comment]
This has been fixed by #2437 

More information in #2434
