### ISSUE TITLE
epubjs hypothesis cannot work

### ISSUE THREAD

**Issue by jayzhen521** [hypothesis/client#703]
There's some bug showed in chrome:
![image](https://user-images.githubusercontent.com/36140554/38007370-b5d7828a-327b-11e8-98c4-45d692240a32.png)
Steps to reproduce
1. go to http://futurepress.github.io/epub.js/examples/hypothesis.html
2. hypothesis annotation cannot run

**It seems that epub want use hypothesis for a long time, and many people ask this question.** I also want use hypothesis in my book library. I sincerely want it can be fixed.

**Comment by JCCR** [comment]
Hello, have you tried this demo?
https://cdn.hypothes.is/demos/epub/epub.js/index.html?loc=chapter_001.xhtml

Taken from here: https://web.hypothes.is/demos/epubjs/

**Comment by jayzhen521** [comment]
Thank you. It works!
source code is: https://github.com/hypothesis/epub-demos
