### ISSUE TITLE
Hypothesis in Readium and limit number of characters in annotation

### ISSUE THREAD

**Issue by mahag** [hypothesis/client#710]
Hello I am using readium-js-viewer  to view epub files with hypothesis plugin added.
Is there a way to limit number of characters in annotation?

**Comment by robertknight** [comment]
There is no way for a publisher to limit the length of annotations that users create. Can you tells us about your use case?

**Comment by mahag** [comment]
We are afraid from piracy and that the content might be copied this is why we need to limit the number of characters in annotation.
