### ISSUE TITLE
Selecting text is difficult in chrome of touch devices with Bookmarklet

### ISSUE THREAD

**Issue by hwasiti** [hypothesis/client#711]
### Steps to reproduce
1. Open chrome on a touch device
2. Open any website (most websites are affected but not all!). Example: 
https://www.thestar.com.my/news/nation/2018/04/07/bn-manifesto-najib-reveals-inclusive-pledges/
3. Load the bookmarklet. Either you have a bookmark which you can click with the address:
javascript:(function(){window.hypothesisConfig=function(){return{showHighlights:true,appType:'bookmarklet'};};var d=document,s=d.createElement('script');s.setAttribute('src','https://hypothes.is/embed.js');d.body.appendChild(s)})();

or copy paste it to the address bar. Please watchout that the 'javascript:' term will be deleted after paste, and you have to write it by yourself

4. Select a word
5. Expand the selection by moving the end of the selector downward for 2-3 lines

### Expected behaviour
Selecting only 2-3 lines

### Actual behaviour
Selecting the whole page to the end of the web page which the user never intended to do so.

## _Example after selecting this word:_

![screenshot_20180408-040058](https://user-images.githubusercontent.com/4212742/38460533-57a90ba4-3aee-11e8-974e-0d5db24e79b4.png)

## _Expanding the selection for 2 lines below will select the whole page:_ 

![screenshot_20180408-040048](https://user-images.githubusercontent.com/4212742/38460534-5d740606-3aee-11e8-9dcd-562cedba3ce0.png)

### Browser/system information
**Android 6:** Chrome latest version (65.0.3325.109), Opera latest version (45.1.2246.125351)
**Windows 10 pro x64 (Surface pro3):** Chrome latest version (Version 65.0.3325.181 (Official Build) (64-bit))
**ios 9: ipad 2:** chrome (59.0.3071.102)

### Additional details

1. To prevent this issue, moving the finger down to expand the selection to the below lines should be very slow, or the user should expand selection by moving the finger obliquely (left or right during going down).

2. ios devices seem to be less affected. The selection seems to flicker to select mistakenly the whole page, but suddenly it will follow my finger and make the correct selection. It seems the bug is still there, but the selection of ios seems in a way that it will not go down to the end of the page, when the page is mistakenly selected all to the end. So after a while the selection will return to the current position of the finger.

**Comment by hwasiti** [comment]
Thanks for the great work and update the GUI of the hypothes.is client.

Any update about this bug? Is it under your radar or have you guys got an idea why do this happen? 

I am willing to help to code and contribute, if I can do something about it... I tried to look into it, and would love if you know where to look exactly.. It is almost unusable on any touch device with chrome browser or any browser on all platforms (tested:Windows/Android/ios)... 

Mobile devices have a big chunk of browser user/market share worldwide... It would be cool if we can make hypothes.is working fine with mobile devices too.. With this bug it is almost unusable unfortunately..

**Comment by robertknight** [comment]
This is not an issue I've experienced myself when testing on iOS or Android devices, but I think this may be due to differences in the devices and or selection gestures that are being made:

> To prevent this issue, moving the finger down to expand the selection to the below lines should be very slow

On my iPhone X in Safari, if I start to make a selection and then rapidly move my finger onto the Annotate/Highlight toolbar I see a brief selection of the whole page before the toolbar has a chance to move out of the way.

In the DOM structure of the page, the toolbar is actually located right at the bottom, so my guess is that the browser is trying to select all the text between the starting position and the bottom of the page. In order to resolve this, I think we'd either need to make the toolbar invisible to the cursor while a selection is being made, or simply position it at the bottom of the page.

**Comment by hwasiti** [comment]
Hi Robert

iOS devices are less affected, and in my test, it was just like you described. But Android and Windows (if the device is touch-capable) are all affected in my tests. I tested multiple Android OS emulators and real devices and all affected. For windows, I have only the latest windows 10 version on my SP3 which shows the same behaviour as in Android.

What Android device that you have tested on?

Can you please check this link (the same link that I've tested):
[https://www.thestar.com.my/news/nation/2018/04/07/bn-manifesto-najib-reveals-inclusive-pledges/](https://www.thestar.com.my/news/nation/2018/04/07/bn-manifesto-najib-reveals-inclusive-pledges/)

As I mentioned in the original post, not all websites are affected (but seems most websites has this issue).

I have even checked an online Android emulator which shows the issue on an Android tablet that you can try yourself.

It is a Chrome extension that should be installed to use the emulator:
[https://chrome.google.com/webstore/detail/android-online-emulator/lnhnebkkgjmlgomfkkmkoaefbknopmja/related?hl=en](https://chrome.google.com/webstore/detail/android-online-emulator/lnhnebkkgjmlgomfkkmkoaefbknopmja/related?hl=en)

I could not copy-paste the links and the bookmarklet to the Android chrome inside the emulator, so to make it easy, please write this URL shortener for this Github page and then the bookmarklet and the link can be copied:
[https://bit.ly/2X448DW](https://bit.ly/2X448DW)

Here is a screenshot:
![image](https://user-images.githubusercontent.com/4212742/82939535-1271a480-9fc6-11ea-8a06-0d66d0f23cc2.png)

To reproduce the issue, there is no need to rapidly move the finger onto the Annotate/Highlight toolbar. Just select a word and pull down the selector handle down for 1 or a few lines.

**Comment by garibarba** [comment]
This issue is very annoying for me. I cannot consistently select text for highlighting on my laptop's chrome touchscreen.

**Comment by hwasiti** [comment]
This issue is partially solved:
https://github.com/hypothesis/product-backlog/issues/878
