### ISSUE TITLE
misencoded PDF title in an annotation POST results in 500 response

### ISSUE THREAD

**Issue by judell** [hypothesis/client#715]
When the client loads on https://assets.documentcloud.org/documents/4424701/Wilbur-Ross-memo-2018-03-26-2.pdf, the doctitle it acquires and sends in a POST payload is as shown:

![image](https://user-images.githubusercontent.com/46509/38648519-77208fc4-3da6-11e8-85bb-3878955e3f65.png)

If I capture and replay the POST without that weird (misencoded?) title, it works fine.

This doesn't affect a few other DocumentCloud PDFs I've checked, I suspect it's a rare anomaly.

**Comment by robertknight** [comment]
I wasn't able to reproduce just now. This might have been fixed by a PDF.js upgrade.
