### ISSUE TITLE
Problems with accented characters in the link?

### ISSUE THREAD

**Issue by SteelWagstaff** [hypothesis/client#729]
We've been having issues with file names that have accented characters--when it comes to replace the link with the HTML5 audio or video embed element, the routine fails. Let's say we use something like `http://test.com/tèst.mp3`. What I'd expect is for the link to be replaced by an HTML5 audio player, but what actually happens is that the link is just inserted as a link--the embed replace never takes place.

I think I've traced it to this line in the code: https://github.com/hypothesis/client/blob/a5ae4aa0fbf5ede8cb52de5f032dcc892d9a37e4/src/sidebar/media-embedder.js#L304

What's happening is that the link.href has been converted into something that looks like this: `http://test.com/t%C3%A8st.mp3` while the link text remains `http://test.com/tèst.mp3`. These strings don't parse as equal and hence the rest of the function is never called. I think this could be fixed by adding this an additional condition to the if statement in the line cited earlier:
`decodeURI(link.href) !==  link.textContent`. Would you be open to a simple pull request that added this to that line?

**Comment by robertknight** [comment]
Fixed by #738
