### ISSUE TITLE
Editing last orphan for a page defaults to the 'Annotations' tab.

### ISSUE THREAD

**Issue by sheetaluk** [hypothesis/client#74]
### Steps to reproduce:
1. Navigate to a group on the page which has one orphaned annotation.
2. Click on the edit button for that card
3. Make a change to the text and save.
### Expected behaviour:

The changes against that orphaned annotation are saved.
The orphans tab stays selected.
### Actual behaviour:

The changes against that orphaned annotation are saved.
The annotations tab is selected.
### Browser:

Tested on Chrome
### Additional details:

The update action for an annotation is a remove followed by an add. So, while editing the last orphaned annotation for a page, when the old annotation is removed, before it is replaced with the new(edited) one, the orphans count decreases to zero, satisfying this condition in `annotation-ui.js`:

```
if (selectedTab === uiConstants.TAB_ORPHANS &&
  countIf(annots, metadata.isOrphan) === 0) {
  selectedTab = uiConstants.TAB_ANNOTATIONS;
}
```

The solution is probably to add an action in `annotation-ui.js` for `UPDATE_ANNOTATIONS`.

**Comment by lyzadanger** [comment]
This issue appears to have been fixed at some point. This behavior is no longer present.
