### ISSUE TITLE
target_uri malformed when annotating https://www.nytimes.com/editorial-standards/ethical-journalism.html

### ISSUE THREAD

**Issue by judell** [hypothesis/client#743]
To reproduce: annotate https://www.nytimes.com/editorial-standards/ethical-journalism.html

What happens: The annotation's target uri is `ttps://www.nytimes.com/editorial-standards/ethical-journalism.html instead of https://www.nytimes.com/editorial-standards/ethical-journalism.html`

Example: https://hyp.is/wXiBqHM-Eeik7Vsc8poeNg

https://hypothes.is/api/annotations/wXiBqHM-Eeik7Vsc8poeNg says:

`"target": [{"source": "ttps://www.nytimes.com/editorial-standards/ethical-journalism.html",`

and 

`"uri": "ttps://www.nytimes.com/editorial-standards/ethical-journalism.html"`

What's expected, obviously, is a uri that starts with `https:`

I checked the database, the only annotations for which target_uri starts with `ttps:` are those three. 

Quite peculiar.

**Comment by robertknight** [comment]
I don't know how this happened originally but I was unable to reproduce using the browser extension or Via.
