### ISSUE TITLE
A page with body styled "white-space: pre" (or with forced <br> line endings) messes with sidebar sync to page

### ISSUE THREAD

**Issue by judell** [hypothesis/client#752]
Example: http://jonudell.info/h/white-space-pre.html#annotations:6K7brpQjEeibqXMiQFpQ5Q

Expected: Client scrolls the page to the target.

Actual: Client scrolls the page to the bottom. Clicking the annotation card doesn't scroll the page to the target. 

Hmm. I figured that removing the style and adding a &lt;br> to every line would solve the problem, but it doesn't! I could swear I've been able to get annotation cards to scroll to the right place in a line-oriented page before, but I don't think anything's changed in a long time that would affect that, so maybe I'm misremembering?

The solution, in this case, was to carve the line-oriented file into paragraph-sized chunks, and then use `p { white-space: pre; }`.

**Comment by robertknight** [comment]
I've retested with the current Hypothesis client in Chrome (using the extension) and Safari (using the bookmarklet) and am no longer able to reproduce the issue. The client scrolls to the expected position.
