### ISSUE TITLE
JS error for annotating PDFs in IE 11

### ISSUE THREAD

**Issue by klemay** [hypothesis/client#762]
This comes from [one of our partners](https://hypothesis.zendesk.com/agent/tickets/2903), who is in the process of integrating Hypothesis.

### Steps to reproduce
1. In IE 11, attempt to annotate a PDF (examples can be found in the ticket or [here in Slack](https://hypothes-is.slack.com/archives/C03QZM0K4/p1535567961000100?thread_ts=1535567912.000100&cid=C03QZM0K4). This is a partner's staging environment so I don't want to make the urls public)
2. Highlight text and click "Annotate"

### Expected behaviour
Sidebar opens up, you're able to add an annotation

### Actual behaviour
Nothing happens. Browser throws a console error:
`SCRIPT65535: Argument not optional`

### Additional details
As [discussed in Slack](https://hypothes-is.slack.com/archives/C03QZM0K4/p1535567912000100), @robertknight noticed:

- We’re calling `document.createNodeIterator` and omitting some arguments that are supposed to be optional but are not in IE 11 (cf. https://github.com/hypothesis/client/blob/b7f4a83622550072620036677856af4744298eb6/src/annotator/range-util.js#L51)
- This line is probably buggy: https://github.com/hypothesis/client/blob/b7f4a83622550072620036677856af4744298eb6/src/annotator/anchoring/pdf.coffee#L288

**Comment by robertknight** [comment]
Hypothesis v1.95.0 now fails with a different error when clicking the "Annotate" button in IE 11:

<img width="997" alt="screenshot 2018-10-22 19 59 53" src="https://user-images.githubusercontent.com/2458/47312940-923ecc80-d635-11e8-9833-1e540ef3a9cb.png">

Viewing annotations that were already created in other browsers does appear to work.

**Comment by sheetaluk** [comment]
I saw that... trying to figure out why. I dont know if this is related to the previous error or a different one.

**Comment by robertknight** [comment]
This was fixed in Hypothesis v1.96.0.
