### ISSUE TITLE
can an embedded client’s share link omit hyp.is?

### ISSUE THREAD

**Issue by judell** [hypothesis/client#765]
For APA (and others, e.g. Atypon), via’s no-cookie policy is a showstopper. But when the client is embedded, there’s no need for via. 

So what’s the problem? Share links. 

An embedded client provides hyp.is links that resolve, unnecessarily and problematically, through via. Could an embedded client be configured to (and perhaps default to) plain (non-hyp.is) share links?

**Comment by dwhly** [comment]
> Could an embedded client be configured to (and perhaps default to) plain (non-hyp.is) share links?

I'm not sure what a "non-hyp.is" share link is.  AFAIK we have no such thing.  There is an outstanding issue though that would address this: https://github.com/hypothesis/product-backlog/issues/720
