### ISSUE TITLE
"Leave group" from client not working

### ISSUE THREAD

**Issue by klemay** [hypothesis/client#774]
### Steps to reproduce
1. Activate Hypothesis and open group scope selector
2. Click on the "x" next to the name of the group you wish to leave
3. Click "OK" on the pop-up which asks you to confirm that you want to leave the group

### Expected behaviour
You leave the group, and the group is no longer visible in the groups control

### Actual behaviour
Nothing happens

### Browser/system information
User who reported this says they tried several browsers; I'm able to reproduce in Chrome, Safari, and Firefox for Mac. 

### Additional details
Note:  it is still possible to leave groups by going to the group activity page and using the "Leave this group" link. The user who reported this bug has been notified of this workaround.

**Comment by robertknight** [comment]
I'm going to take a look at this now since I think it must be a very recent regression.

**Comment by robertknight** [comment]
The regression occurred in 46e4bbadc991d550ca9706b5237e35d68675a6cc which changed the name of the `user` parameter in the `DELETE /api/groups/{pubid}/members/{user}` to `DELETE /api/groups/{pubid}/members/{userid}`.

**Comment by robertknight** [comment]
It seems quite unlikely that any clients other than the Hypothesis client are using this particular API, especially in a way that this would be a breaking change, so I think it will be easiest to [update the client](https://github.com/hypothesis/client/blob/cf7241a80e6f10d9a37d6c210e137caacb76cbd2/src/sidebar/services/groups.js#L172).

We really could use tests in h to guard against unexpected API changes.
