### ISSUE TITLE
Major clash on websites with a global AMD module loader

### ISSUE THREAD

**Issue by renehamburger** [hypothesis/client#779]
Several (or possibly all) of your bundles (e.g. `polyfill.bundle.js`, `jquery.bundle.js` or `unorm.bundle.js`) define global `require()` functions for module loading. On websites which use AMD module loaders themselves, this leads to unresolved modules and exceptions, when the host code calls require after your bundles have been loaded and overwritten this function.

This can happen regularly when hypothes.is is loaded early via a browser extension. But even when it's loaded later, this may happen, e.g. when host code is executed as a result of a user action and requires a module.

You can observe this issue on Moodle, if you activate the browser extension and then navigate to the [calendar on the Moodle demo site](https://school.demo.moodle.net/calendar/view.php) and log in as guest.

There's little doubt that a browser extension should avoid defining global variables at all, or only define them within a unique namespace. Wrapping each of your bundles with an IIFE should resolve this issue, since Browserify never defines `require`  explicitly on window but just as `require = `. So wrapping it should do the trick (see [here](https://github.com/browserify/browserify/issues/403)).

**Comment by robertknight** [comment]
Thank-you for the detailed report @renehamburger. I opened a PR which resolves the issue by customizing the name of the exported require using a combination of Browserify's `externalRequireName` option and an IIFE wrapper.

In the context of the browser extension there are more global ways to avoid conflicts, eg. running the code as a content script that is isolated from the page, but that is a bigger task.
