### ISSUE TITLE
Bookmarklet: sidebar won't open on HTML page of specific journal article

### ISSUE THREAD

**Issue by klemay** [hypothesis/client#781]
**NOTE** since this appears to be pretty isolated, I'm adding it to the "To Review" column of the Bug Backlog. I don't think engineers need to look into this for now. 

This one's a little weird, because I'm seeing it when using the bookmarklet & Via (Firefox and Safari) but NOT when using the Chrome (extension and Via work). And it's only on this one article— other pages and articles from this website appear to work fine. This was reported by a user here: https://hypothesis.zendesk.com/agent/tickets/3145

### Steps to reproduce
1. In Firefox or Safari, view this HTML article: http://www.irrodl.org/index.php/irrodl/article/view/3620/4734
2. Activate the Hypothesis bookmarklet

OR

1. In Firefox in Safari, visit https://via.hypothes.is/http://www.irrodl.org/index.php/irrodl/article/view/3620/4734

### Expected behaviour
Hypothesis activates over the page and users can annotate

### Actual behaviour
The chevron does not open the sidebar. Instead the page freezes and the console shows:

<img width="580" alt="screen shot 2018-10-01 at 1 24 47 pm" src="https://user-images.githubusercontent.com/12087705/46304725-750a6700-c57d-11e8-96b9-62a4c829e757.png">

(note that the warning about passwords appears in FF even when Hypothesis is not activated and does not seem to be relevant here— the Bookmarklet works on other articles hosted on this website and on other http sites).

### Browser/system information
Encountered in Safari and Firefox for Mac, but not for Chrome. 

### Additional details
Interestingly, this appears to be isolated to the HTML page of this one journal article. I don't see this error when I visit any of the following:

- http://www.irrodl.org/index.php/irrodl/issue/view/94 (page for the issue in which the article appears)
- http://www.irrodl.org/index.php/irrodl/article/view/3601 (abstract page for the article)
- http://www.irrodl.org/index.php/irrodl/article/view/3601/4769 (page that hosts PDF version of the article)
- http://www.irrodl.org/index.php/irrodl/article/view/3620/4734 (HTML version of a different article from the same journal)
- http://www.irrodl.org/index.php/irrodl/article/view/3528/4729 (HTML version of a 2nd article from the same version)

**Comment by lyzadanger** [comment]
Found this by Googling the specific error message, in case it's helpful: https://github.com/openannotation/annotator/blob/master/locale/annotator.pot#L34

**Comment by robertknight** [comment]
The functions mentioned in the error message have been completely replaced or re-written since this issue was filed. I'm no longer able to reproduce. I do see a different issue on http://www.irrodl.org/index.php/irrodl/article/view/3620/4734, which is that all the content is inside an iframe, so you can't annotate it using the bookmarklet. That's a known limitation of the bookmarklet currently though.
