### ISSUE TITLE
H client won't open at Zenodo

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#782]
### Steps to reproduce
1. Go to https://zenodo.org/record/1443395#.W7TQ8xPYrOR
2. Try to launch the Chrome extension

### Expected behaviour
The sidebar should appear

### Actual behaviour
It does not.

### Browser/system information
Recent chrome

### Additional details
JS Console prints:
zenodo.705beba8.js:1 Uncaught Error: See almond README: incorrect module build, no module name
    at define (zenodo.705beba8.js:1)
    at FragmentAnchor.js:3
    at Object.6 (FragmentAnchor.js:11)
    at o (_prelude.js:1)
    at _prelude.js:1
    at Object.39../range (types.coffee:1)
    at o (_prelude.js:1)
    at _prelude.js:1
    at Object.36../types (html.coffee:1)
    at o (_prelude.js:1)

**Comment by lyzadanger** [comment]
Reviewing some long-standing issues in the queue: @dwhly I am able to open the sidebar (current extension, version 1.507, Chrome 85) on the URL you provided. Are you still seeing issues?

I do see some JS errors in the console, but they're not from our source.

**Comment by robertknight** [comment]
The files referenced in the stack trace Dan posted above no longer exist in the code, so I think we can assume this is fixed.
