### ISSUE TITLE
Deploying a release that is not the latest merge to master can fail

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#810]
Attempting to deploy a release from Jenkins which is not the latest merge to master can fail as follows:

1. Merge PR A 
2. Wait a minute or so and merge PR B
3. Wait for Jenkins build of PR A and PR B to finish QA deploy
4. Attempt to deploy first build (PR A) to prod.

Step 4 will create a Git tag and a commit on the master branch for the release and attempt to push that to GitHub. However this will fail because the release commit was not made against the latest version of master, but the commit before PR B was merged.

See also this [Slack discussion](https://hypothes-is.slack.com/archives/C1M8NH76X/p1541678684060500)

To resolve this, we'll either need to change the release process to avoid actually creating commits in the process, or ensure that Jenkins merges the release commit to master rather than attempting to force-push it.

**Comment by seanh** [comment]
Jenkins is trying to do a release commit on top of the latest commit that it has (which is the commit that Jenkins has tested, and that the developer has tested on QA). Wouldn't merging with other commits from GitHub mean the release commit would not represent the same code that has been tested?

**Comment by robertknight** [comment]
After some Slack discussion we concluded that avoiding having to commit to master as part of the release would be best. We can do this by:

- Removing CHANGELOG.md from the repo. The info will still be available in GitHub releases.
- Having a dummy version in package.json on master and then generating the monotonically increasing version number for a release based on the last Git tag.

**Comment by robertknight** [comment]
The first part of this, removing the CHANGELOG, is happening in https://github.com/hypothesis/client/pull/911
