### ISSUE TITLE
return of window.hypothesisConfig does not seem to be included into configuration

### ISSUE THREAD

**Issue by Gozala** [hypothesis/client#816]
### Steps to reproduce
1. Define `window.hypothesisConfig = () => { debugger; return { assetRoot: "../client-repo-clone" }; }`
2. And load hypothesis client by using `build/boot.js`.

### Expected behaviour
Tell us what should happen.

I would expect provided configuration through `window.hypothesisConfig` to be taken into account.

### Actual behaviour

From what I can see by the time `hypothesisConfig` is invoked client has already injected bunch of scripts / links and even though config is pulled in it's not really taken into account.

### Browser/system information
Firefox night on OSX but it's really agnostic of configuration.

**Comment by Gozala** [comment]
My Actual goal is to provide (`onProfileRequest`)[https://h.readthedocs.io/projects/client/en/latest/publishers/config/#cmdoption-arg-onprofilerequest] but I have no luck with providing even basic configuration.

**Comment by robertknight** [comment]
`window.hypothesisConfig` definitely works. We use it all over the place. Try using it to set the `openSidebar` configuration option for example.

`onProfileRequest` is only respected however when using "third party accounts" where the website automatically logs the user into an account they manage (ie. not created through the h service's web UI) which typically corresponds to some existing account on their website. This is done for security reasons - to prevent an arbitrary website from easily redirecting links in the sidebar part of the client.

**Comment by Gozala** [comment]
> `window.hypothesisConfig` definitely works. We use it all over the place. Try using it to set the `openSidebar` configuration option for example.

@robertknight Turns out the issue I was experiencing was caused by following piece of code:

https://github.com/hypothesis/client/blob/9c6ecbd28a19fa3d385fc194fc678a4218a577d1/src/annotator/config/is-browser-extension.js#L11-L13

I've being working on hypothesis client for [beaker browser](https://beakerbrowser.com/) that loads it from [`dat://` protocol](http://datproject.org/) which hypothesis client mistakenly took for browser extension and took alternate path leading it to ignore config.

**Comment by robertknight** [comment]
I'd be happy to accept a PR to invert the check to match only the schemes used by Chrome and Firefox extensions (`chrome-extension://` and `moz-extension://`),  since those are the only extensions we currently build.
