### ISSUE TITLE
new annotation not init when has annotations selected

### ISSUE THREAD

**Issue by kikyous** [hypothesis/client#827]
### Steps to reproduce
1. select text and create a highlight
2. click highlight in page,  right sidebar show a button (Show all annotations (2))
3. after this, all new create annotation does't init (not post data to server), so when page close, all new 
annotation lost.

**Comment by klemay** [comment]
We are unable to reproduce this, so I am closing this issue. If you need help with using Hypothesis, please email support@hypothes.is for additional help and troubleshooting.
