### ISSUE TITLE
Sidebar doesn't scroll to editor (Site report)

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#83]
### Steps to reproduce
1. Go here: https://via.hypothes.is/https://www.commonsense.org/education/privacy/blog/digital-redlining-access-privacy
2. Scroll midway down the page, so that there are a fair number of annotations above you.
3. Select text, click "Annotate"

### Expected behaviour
The sidebar should open and scroll to an open editor

### Actual behaviour
The sidebar opens and remains fixed at the top of the cards showing.  The open editor does exist, but must be scrolled into view.

### Browser/system information
Via + Recent chrome

**Comment by jeremydean** [comment]
Here's more from a classroom of users:

>When students in class are attempting to annotate a website (all are using Chrome with the H extension, and are annotating as part of a H group specific to the class), as soon as one student posts an annotation, all the other students who are in the process of writing are "ejected" from their individual annotation or page note window and the annotations panel reloads / returns to the top of the list of annotations. That means that a given student has to then scroll down, attempt to find the window in which he or she was typing (among 25+ students worth of annotations), start typing again, and attempt to quickly post before someone else does. Otherwise, they again are interrupted, have to scroll down, find the window, etc. This caused much frustration in class and has thus far soured student interest in our Hypothes.is work, which for me is a big problem. I'm using H in all 4 of my classes, and in-class H work will be part of each class. That will be pretty much impossible if students keep getting interrupted by other student posts. 

>Can we find a way to delay the reloading / updating / refreshing of H for a person currently in the process of annotating a page; i.e., someone with an open annotation or open page note window?. As soon as that person posts, it then would be great if the document refresh could happen.

**Comment by dwhly** [comment]
I just confirmed the further distinction noted by @jeremydean together with him and captured a video of this happening at the above page.  The video shows that while I have the editor window open with a little text in it, Jeremy then completes an annotation on the same page, which somehow forces a "refresh" on my sidebar too scrolling the sidebar to the top, so that my editor window-- still open and active-- is no longer visible.

https://drive.google.com/file/d/0B0yW-dSdEYAcYlJ1cXkyQ1ZvVnM/view

**Comment by robertknight** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Ak2TVOAg&#x2F;443-annotation-updates-received-over-the-web-socket-result-in-anchoring-status-being-lost"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Annotation updates received over the web socket result in anchoring status being lost</a>

**Comment by dwhly** [comment]
@robertknight:  @jeremydean and I experimented with the recent release, and notice that the editor still hops around a bunch, occasionally off screen when another user is annotating.  

Here's a video.
https://drive.google.com/file/d/0B0yW-dSdEYAcM1BWMTZUUGpRWVk/view

I open an editor and jeremy begins several annotations, you can see the sidebar scrolling around.

**Comment by dwhly** [comment]
However, the titled problem on this issue *is* fixed, so it should probably be renamed.

**Comment by nickstenning** [comment]
Both issues described here do appear to be fixed in v0.39.0
