### ISSUE TITLE
Sidebar display issues

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#84]
### Steps to reproduce
1. Go here: http://ccc.coastal.edu/index.php/task/102-badge-3-2/
### Expected behaviour

Sidebar displays normally
### Actual behaviour

Issues with sidebar icons
### Browser/system information

Chrome

![screenshot 2016-09-01 22 04 24](https://cloud.githubusercontent.com/assets/1413074/18193202/267231d4-7090-11e6-8656-58453c85d2db.png)

**Comment by robertknight** [comment]
This is caused by CSS on the page which sets the opacity of the buttons to 0.2.

**Comment by nickstenning** [comment]
I've folded the details into a bug to track this and a number of closely related reports: hypothesis/client#244.
