### ISSUE TITLE
Add custom header to all API requests

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#890]
As part of planning our API and product strategy, it is exceedingly helpful to be able to gather metrics about the use of our API. By adding a custom header to requests that the client makes against the API, we will be able to quickly discern API traffic that _isn't_ generated by the client. This will help us understand usage and what impacts API changes will have on other users.

It was discussed that the value of the header might contain version information, as well.

With luck, this might be a simple change!

**Comment by dwhly** [comment]
Related to: https://github.com/hypothesis/product-backlog/issues/696

**Comment by robertknight** [comment]
Do you have an idea of what service(s) you will use to gather and visualize API usage metrics? If so, are there any preferences or constraints on the name and format of the header that we would need to use?

The only restriction from the client side is that we can't set headers in the [forbidden header name](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name) set. One thing I learned from this page which surprised me - it _is_ apparently allowed to set the `User-Agent` header.

**Comment by lyzadanger** [comment]
If we were tracking more generic requests, using `X-Client-Version` might be a reasonable approach, but I would suggest something _more_ custom as we are intending only _our_ client to send this header. Thus, perhaps `X-Hypothesis-Client-Version` might be appropriate?

**Comment by robertknight** [comment]
Providing such a header works with whatever tools we're planning to use to analyze the data, that's fine with me.

**Comment by hmstepanek** [comment]
https://github.com/hypothesis/client/pull/930
