### ISSUE TITLE
Empty string shown in _No results for “”_ when no search results

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#9]
![untitled screencast - edited 24](https://cloud.githubusercontent.com/assets/22498/16523449/6da5ec7e-3f9b-11e6-9488-6f8ab31a084d.gif)

**Comment by uzhne** [comment]
I just signed up for hypothesis and encountered a similar bug but the text is "No results for “function(){return a.getState().filterQuery}”"

**Comment by robertknight** [comment]
I can reproduce @uzhne's issue:

<img width="477" alt="screenshot 2018-06-12 11 53 36" src="https://user-images.githubusercontent.com/2458/41286410-46dd32ba-6e37-11e8-84f8-5b07f8aa58dc.png">
