### ISSUE TITLE
Sort order for Page Notes is ill-defined

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#96]
The default sort order for annotations is to sort by location in the document. For Page Notes, this doesn't make sense and the ideal sort order hasn't been specified, so it is whatever happens to come out of the implementation.

Now for the fun part: In the implementation, Page Notes are sorted by location, but the value `Number.POSITIVE_INFINITY` is used as the value of the location for all notes. Since:

1. In JavaScript `Number.POSITIVE_INFINITY < Number.POSITIVE_INFINITY` is false
2. The sort function passed to `Array.sort()` always returns 0 due to (1)
3. Stability of `Array.sort()` is implementation defined (stable in IE, Firefox, unstable in Chrome [1])
4. There is no guarantee of the order in which Page Notes are stored in the app state anyway

This means that the order in which page notes are sorted is unpredictable.

[1] _Compare the result of `[1,2,3,4,5,6,7,8,9,10,11].sort(() => 0)` in Chrome and Firefox_

**Comment by robertknight** [comment]
And just because I was curious: Chrome uses the classic combination of quick sort + insertion sort for short arrays. Hence sort order is stable for arrays of [less than 11 elements](https://github.com/v8/v8/blob/bf85ca531510879c77b3fd707d498ada9677cb74/src/js/array.js#L764)

**Comment by robertknight** [comment]
My suggestion would be that we sort by date of creation by default. This would match the behavior of a typical commenting system where comments are not attached to any specific part of a document.

**Comment by dwhly** [comment]
> My suggestion would be that we sort by date of creation by default.

Very strong endorsement here from me.  This is a good starting point that we can adjust later if we want, but gets us  at least a designated sort as a starting point.
