### ISSUE TITLE
Empty annotations reverting to edit mode

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#98]
Possibly related to #97 , in this screencast of H you can see empty annotations appearing to revert to Edit mode when scrolling up between 0:30 and 0:40 in this video.

@jeremydean can you provide any more details of what you recall about this issue?

**Comment by judell** [comment]
Where's the video?

**Comment by jeremydean** [comment]
Here:

@robertknight 

i'm annotating as one identity in one window (chrome on left), another in the second (via). at some point moving back and forth adding annotations as each id to the same doc, the PDF on the right leaps to another point in the text. when i scroll back down to the bottom where i was working, i see three annotations open that had been saved. 

http://www.screencast.com/t/9bdzzoHoRT

at least in previous versions of the extension, i was able to reliably reproduce this by simply annotating a doc a lot (20-30 annotations) with two accounts at the same time in two windows.

**Comment by robertknight** [comment]
I believe this bug is now obsolete because the client no longer automatically updates when other users annotate on the page you are viewing, instead the user has to click a button to see changes, when it is convenient for them to do so.
