### ISSUE TITLE
Can't add annotation to a group without being it private first

### ISSUE THREAD

**Issue by ImaCrea** [hypothesis/client#987]
### Steps to reproduce
I have a private group, let's call it GRP.
1. Open a webpage and click on bookmarklet to open h web client (I'm on Firefox)
2. I select a part of text and highlight it.
3. I open the right panel, and I see on the top area of it I'm in deed adding highlight to GRP *but* there's a lockpad icon. Meaning the highlight is added to the group but no one can see it, as it's private. (I want everybody in the group to be able to see it.)
4. I click on the edit button. I click on the arrow on the button "Post only to me" -> "Post to GRP". *BUT* I can't click on it to apply the change. So I go in the text box and I type a space, then the button is enabled and I can finally make it visible to the group.
5. I go back to my article, and I highlight some other part. *Again* the highlight shows a padlock, meaning I have to go all the way again to edit and all to make it visible to the group...

### Expected behaviour

1. Changing the visibility of a highlight inside a group shouldn't need to open edit and type a fake space in order to click on the button. Best would be to directly click on the padlock to switch it to *visible for the group*.
2. Once I set for a highlight a certain kind of publishing settings, here *in GRP and visible*, it should keep that info so next highlights gets a same setting by default.

### Actual behaviour
as said before;
4. I click on the edit button. I click on the arrow on the button "Post only to me" -> "Post to GRP". *BUT* I can't click on it to apply the change. So I go in the text box and I type a space, then the button is enabled and I can finally make it visible to the group.
5. I go back to my article, and I highlight some other part. *Again* the highlight shows a padlock, meaning I have to go all the way again to edit and all to make it visible to the group...

### Browser/system information
Firefox 65.0.1 64bit Ubuntu version running on Elementary OS Juno.

**Comment by klemay** [comment]
Hi @ImaCrea - we're doing a bit of cleanup in our repros and are just now seeing this issue you opened. This is definitely unexpected behavior, so if you are still experiencing this please email support@hypothes.is for additional help/troubleshooting.
